#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# directories #

# blackbox

console.inf "Creating directories [ blackbox ]."
echo

system_directories_list=(
	.blackbox
)

for directory in ${system_directories_list[@]}
do
	console.fwd "Creating directory [ ${directory} ]."
	echo

	# create directory and set permissions

	[ ! -d "$PROOT_DIRECTORY"/home/"$user_name"/"${directory}" ] && "$PROOT_DIRECTORY"/home/"$user_name"/"${directory}" || :
	
	# set ownership
	
	chown ${uid}:${gid} -R "$PROOT_DIRECTORY"/home/"$user_name"/"${directory}"
done

# write configuration files

console.inf "Writing configuration files [ blackbox ]."
echo

bash "$PROOT_DIRECTORY"/tmp/blackbox-configuration
bash "$PROOT_DIRECTORY"/tmp/blackbox-menu
bash "$PROOT_DIRECTORY"/tmp/blackbox-theme
