#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write menu file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackbox/styles/"${theme}"

FILE