#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write menu file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackbox/styles/"${theme}"
rootCommand: bsetroot -solid #232629

*backgroundColor: #313437

*borderColor: #232629
*borderWidth: 1

*button.pressed.appearance: flat solid
*button.pressed.foregroundColor: #ffffff
*button.pressed.backgroundColor: #313437
*button.appearance: parentrelative
*button.foregroundColor: #000000

*font: Sans-9:style=Regular

*marginWidth: 1

menu.title.appearance: flat solid
menu.title.backgroundColor: #313437
menu.title.foregroundColor: #000000
menu.title.textColor: #000000
menu.title.alignment: center

menu.frame.appearance: flat solid
menu.frame.textColor: #000000
menu.frame.foregroundColor: black
menu.frame.disabledColor: #666666
menu.frame.alignment: left

menu.active.appearance: flat solid
menu.active.backgroundColor: #2980b9
menu.active.foregroundColor: #ffffff
menu.active.textColor: #ffffff

slit.appearance: flat solid
slit.backgroundColor: #313437
slit.marginWidth: 4

toolbar.appearance: flat solid
toolbar.alignment: left
toolbar*textColor: #000000
toolbar.label.appearance: parentrelative
toolbar.clock.appearance: parentrelative
toolbar.windowLabel.appearance: parentrelative
toolbar.marginWidth: 4

window*alignment: center

window.button.focus.appearance: parentrelative
window.button.focus.foregroundColor: #ffffff
window.button.unfocus.appearance: parentrelative
window.button.unfocus.foregroundColor: #666666

window.grip.focus.appearance: flat solid
window.grip.focus.backgroundColor: #2980b9
window.grip.unfocus.appearance: flat solid

window.handleHeight: 2
window.handle.focus.appearance: flat solid
window.handle.unfocus.appearance: flat solid

window.label.focus.appearance: parentrelative
window.label.focus.textColor: #ffffff
window.label.unfocus.appearance: parentrelative
window.label.unfocus.textColor: #666666
window.label.marginWidth: 1

window.title.focus.appearance: flat solid
window.title.unfocus.appearance: flat solid
FILE