#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write configuration file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackboxrc
session.screen0.slit.placement:                  BottomRight
session.screen0.slit.direction:                  Horizontal
session.screen0.slit.onTop:                      True
session.screen0.slit.autoHide:                   False
session.screen0.toolbar.onTop:                   False
session.screen0.toolbar.autoHide:                True
session.screen0.toolbar.placement:               TopCenter
session.screen0.toolbar.widthPercent:            80
session.screen0.enableToolbar:                   True
session.screen0.workspaces:                      4
session.screen0.workspaceNames:                  [ 1 ],[ 2 ],[ 3 ],[ 4 ]
session.screen0.strftimeFormat:                  %I:%M %p
session.opaqueMove:                              True
session.maximumColors:                           0
session.menuFile:                                /home/nathanel/.blackbox/menu
session.shadeWindowWithMouseWheel:               True
session.edgeSnapThreshold:                       0
session.styleFile:                               home/nathanel/.blackbox/styles/Red
session.focusNewWindows:                         True
session.rowPlacementDirection:                   LeftToRight
session.imageDither:                             OrderedDither
session.changeWorkspaceWithMouseWheel:           True
session.toolbarActionsWithMouseWheel:            True
session.autoRaiseDelay:                          200
session.windowPlacement:                         CenterPlacement
session.fullMaximization:                        False
session.focusModel:                              ClickToFocus
session.doubleClickInterval:                     250
session.placementIgnoresShaded:                  True
session.windowSnapThreshold:                     10
session.disableBindingsWithScrollLock:           False
session.focusLastWindow:                         True
session.opaqueResize:                            True
session.colPlacementDirection:                   TopToBottom
FILE

# write menu file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackbox/menu
[begin] (Menu)
	[submenu] (Applications)
		[submenu] (Shells)
			[exec] (Bash)  {x-terminal-emulator  -T "Bash" -e sh -c "/bin/bash --login"}
		[end]
		[submenu] (System)
			[submenu] (Administration)
			[exec] (Pager)  {/usr/bin/bbpager}
			[exec] (Run)  {/usr/bin/bbrun}
			[exec] (Mail) {/usr/bin/bbmail}
			[end]
			[submenu] (Monitoring)
			[end]
		[end]
		[submenu] (Graphics)
			[exec] (LeoCAD) {/usr/bin/leocad}
		[end]
	[end]
	[submenu] (Blackbox)
		[config] (Configuration)
		[submenu] (Styles)
		[stylesdir] (~/.blackbox/styles)
		[stylesdir] (/usr/share/blackbox/styles)
		[end]
		[workspaces] (Workspaces)
		[end]
[sep]
[reconfig] (Reconfigure)
[restart] (Restart)
[exit] (Exit)
		
[end]
FILE