#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write menu file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackbox/menu
[begin] (Menu)
	[exec] (Bash)  {x-terminal-emulator -e /bin/bash}
	[exec] (Nano)  {x-terminal-emulator -e /usr/bin/nano}
	[exec] (LeoCAD) {/usr/bin/leocad}
	[sep]
	[submenu] (Blackbox)
		[submenu] (Utilities)
			[exec] (Pager) {/usr/bin/bbpager}
			[exec] (Run)  {/usr/bin/bbrun}
			[exec] (Mail) {/usr/bin/bbmail}
		[end]
		[config] (Configuration)
		[submenu] (Styles)
		[stylesdir] (/usr/share/blackbox/styles)
		[end]
		[workspaces] (Workspaces)
		[sep]
		[reconfig] (Reconfigure)
		[restart] (Restart)
		[exit] (Exit)
		[end]
[end]
FILE