#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write configuration file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.blackboxrc
session.menuFile:                                /usr/share/blackbox/menu
session.styleFile:                               /usr/share/blackbox/styles/Theme
session.autoRaiseDelay:                          200
session.changeWorkspaceWithMouseWheel:           True
session.colPlacementDirection:                   TopToBottom
session.disableBindingsWithScrollLock:           False
session.doubleClickInterval:                     250
session.edgeSnapThreshold:                       0
session.focusLastWindow:                         True
session.focusModel:                              ClickToFocus
session.focusNewWindows:                         True
session.fullMaximization:                        False
session.imageDither:                             FloydSteinbergDither
session.maximumColors:                           0
session.opaqueMove:                              True
session.opaqueResize:                            True
session.placementIgnoresShaded:                  True
session.rowPlacementDirection:                   LeftToRight
session.screen0.enableToolbar:                   True
session.screen0.slit.autoHide:                   False
session.screen0.slit.direction:                  Horizontal
session.screen0.slit.onTop:                      True
session.screen0.slit.placement:                  BottomLeft
session.screen0.strftimeFormat:                  %I:%M %p
session.screen0.toolbar.autoHide:                True
session.screen0.toolbar.onTop:                   False
session.screen0.toolbar.placement:               TopLeft
session.screen0.toolbar.widthPercent:            100
session.screen0.workspaceNames:                  [ 1 ],[ 2 ],[ 3 ],[ 4 ]
session.screen0.workspaces:                      4
session.shadeWindowWithMouseWheel:               True
session.toolbarActionsWithMouseWheel:            True
session.windowPlacement:                         CenterPlacement
session.windowSnapThreshold:                     10
FILE