#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# write configuration file

cat <<- FILE > "$PROOT_DIRECTORY"/home/"$user_name"/.config/i3/config
# i3 configuration #

# startup #

# exec_always --no-startup-id APPLICATION OPTIONS

# lock screen - xss-lock - uses loginctl lock-session to lock your screen

exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# modifiers #

# 'xmodmap' output:

# shift		Shift_L (0x32) | Shift_R (0x3e)
# lock		Caps_Lock (0x42)
# control	Control_L (0x25) | Control_R (0x69)
# mod1		Alt_L (0x40) | Alt_R (0x6c) | Meta_L (0xcd)
# mod2		Num_Lock (0x4d)
# mod3
# mod4		Super_L (0x85) | Super_R (0x86) | Super_L (0xce) | Hyper_L (0xcf)
# mod5		ISO_Level3_Shift (0x5c) | Mode_switch (0xcb)

set \$modifier Mod1
set \$windows Mod4

# workspaces #

set \$workspace1			"1"
set \$workspace2			"2"
set \$workspace3			"3"
set \$workspace4			"4"
set \$workspace4			"4"
set \$workspace4			"5"
set \$workspace4			"6"
set \$workspace4			"7"
set \$workspace4			"8"

# information bar

set \$info_bar "i3status"

# launcher

set \$launcher "i3-dmenu-desktop"

# menu

set \$menu "dmenu_run -nf '#FFFFFF' -nb '#000000' -sb '#000000' -sf '#815FA3' -fn 'monospace-10' -p 'dmenu prompt &gt;"

# network manager

set \$network_manager "nm-applet"

# terminal

set \$terminal "xfce4-terminal"

# colors #

# A - border
# B - background
# C - text
# D - indicator
# E - child border

# color class				[  A  ]	[  B  ]	[  C  ]	[  D  ]	[  E  ]

client.focused				#000000	#000000 #FFFFFF	#FFFFFF	#000000
client.focused_inactive		#000000	#000000 #666666	#666666	#000000
client.unfocused			#000000	#666666 #000000	#000000	#000000
client.urgent				#000000	#000000 #FF0000	#FF0000	#000000
client.placeholder			#000000	#000000 #815FA3	#815FA3	#000000
client.background			#000000

bar {
	colors {
		background			#000000
		statusline			#FFFFFF
		separator			#666666
		
		focused_workspace	#000000	#000000	#FFFFFF
		active_workspace	#000000	#000000	#FFFFFF
		inactive_workspace	#000000	#000000	#666666
		urgent_workspace	#000000	#000000	#FF0000
		binding_mode		#000000	#000000	#815FA3
	}
}

# windows #

# disable window titlebars

# for_window [class="^.*"] border pixel 2

# window title format

# for_window [class=".*"] title_format "<b>%title</b>"

# window title color

# for_window [class="(?i)class_name"] title_format "<span foreground='color'>%title</span>"

# window title alignment - left | center | right

title_align center

# window size - floating

floating_minimum_size 800 x 600
floating_maximum_size -1 x -1

# window modifier - floating

floating_modifier \$modifier

# fonts

font pango:Sans Regular 10

# bindings #

# open launcher

bindsym \$modifier+r exec --no-startup-id \$launcher

# open terminal

bindsym \$modifier+t exec \$terminal

# kill application instance

bindsym \$modifier+x kill

# change focus

bindsym \$modifier+Left focus left
bindsym \$modifier+Down focus down
bindsym \$modifier+Up focus up
bindsym \$modifier+Right focus right

# move focused window

bindsym \$modifier+Shift+Left move left
bindsym \$modifier+Shift+Down move down
bindsym \$modifier+Shift+Up move up
bindsym \$modifier+Shift+Right move right

# horizontal split - vertical layout

bindsym \$modifier+h split h

# vertical split - horizontal layout

bindsym \$modifier+v split v

# toggle floating

bindsym \$modifier+space floating toggle

# toggle fullscreen

bindsym \$modifier+f fullscreen toggle

# change container layout  - split / stacked / tabbed

bindsym \$modifier+s layout toggle split
bindsym \$modifier+k layout stacking
bindsym \$modifier+b layout tabbed

# change window focus - tiling / floating

bindsym \$modifier+Shift+space focus mode_toggle

# focus parent container

bindsym \$modifier+p focus parent

# focus child container

bindsym \$modifier+d focus child

# move floating container to the center of all outputs

bindsym \$mod+Shift+c move absolute position center

# move container to the current position of the cursor

bindsym \$mod+Shift+m move position mouse

# switch workspace

bindsym \$modifier+1 workspace number \$workspace1
bindsym \$modifier+2 workspace number \$workspace2
bindsym \$modifier+3 workspace number \$workspace3
bindsym \$modifier+4 workspace number \$workspace4
bindsym \$modifier+5 workspace number \$workspace5
bindsym \$modifier+6 workspace number \$workspace6
bindsym \$modifier+7 workspace number \$workspace7
bindsym \$modifier+8 workspace number \$workspace8

# move focused container to workspace

bindsym \$modifier+Shift+1 move container to workspace number \$workspace1
bindsym \$modifier+Shift+2 move container to workspace number \$workspace2
bindsym \$modifier+Shift+3 move container to workspace number \$workspace3
bindsym \$modifier+Shift+4 move container to workspace number \$workspace4
bindsym \$modifier+Shift+5 move container to workspace number \$workspace5
bindsym \$modifier+Shift+6 move container to workspace number \$workspace6
bindsym \$modifier+Shift+7 move container to workspace number \$workspace7
bindsym \$modifier+Shift+8 move container to workspace number \$workspace8

# reload i3 configuration

bindsym \$modifier+q reload

# restart i3

bindsym \$modifier+Shift+q restart

# exit i3 (logs you out of your X session)

bindsym \$modifier+Shift+x exec "i3-nagbar -t warning -m 'Exit session?' -B 'Yes' 'i3-msg exit'"

# resize window  - bindings are triggered when entering the resize mode (you can also use the mouse)

# enter resize mode

bindsym \$modifier+z mode "resize"

mode "resize" {
	# reset window width and height to specified size
	bindsym \$modifier+Shift+z resize set 800 px  600 px
	
	# shrink window width
	bindsym Left resize shrink width 10 px
	# shrink window height
	bindsym Up resize shrink height 10 px
	# grow window height
	bindsym Down resize grow height 10 px
	# grow window width
	bindsym Right resize grow width 10 px
	
	# exit resize mode
	bindsym \$modifier+z mode "default"
}

# display workspace information bar - i3bar + i3status

bar {
	status_command \$info_bar
	
	binding_mode_indicator no
	font pango:Sans Regular 10
	hidden_state hide
	mode hide
	modifier Mod1
	position bottom
	separator_symbol " / "
	strip_workspace_name no
	strip_workspace_numbers no
	workspace_buttons yes
}
FILE

cat << 'FILE' >> /home/$USER/.config/i3status/config
general {
	output_format = "i3bar"
	
	color_bad = '#ff0000'
	color_degraded = '#ebcb8b'
	color_good = '#2f343f'
	color_separator = '#ffffff'
	colors = false
	interval = 5
	markup = pango

}
order += "tztime local"
order += "battery 0"
order += "cpu_temperature 0"
order += "cpu_temperature 1"
order += "cpu_temperature 2"
order += "cpu_temperature 3"
order += "cpu_temperature 4"
order += "cpu_temperature 5"
order += "cpu_temperature 6"
order += "cpu_temperature 7"
order += "disk /"
order += "ethernet eth0"
order += "wireless wlan0"

load {
	format = "%5min Load"
}

battery 0 {
	last_full_capacity = true
	format = " %status %remaining (%emptytime %consumption) %percentage"
	path = "/sys/class/power_supply/battery/uevent"
	format_down = "No Battery"
	status_chr = "Charging"
	status_bat = "Battery"
	status_unk = "N/A"
	status_full = "Full"
	low_threshold = 15

}

cpu_temperature 0 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone0/temp"
}

cpu_temperature 1 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone1/temp"
}

cpu_temperature 2 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone2/temp"
}

cpu_temperature 3 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone3/temp"
}

cpu_temperature 4 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone4/temp"
}

cpu_temperature 5 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone5/temp"
}

cpu_temperature 6 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone6/temp"
}

cpu_temperature 7 {
	format = "%degrees °C"
	path = "/sys/class/thermal/thermal_zone7/temp"
}

disk "/" {
	format = "[ %free | $avail | %total ]"
}

ethernet eth0 {
	format_up = "E: (%quality at %essid, %bitrate / %frequency) %ip"
	format_down = "Down"
}

wireless wlan0 {
	format_up = "W: (%quality at %essid, %bitrate / %frequency) %ip"
	format_down = "Down"
}

tztime local {
	format = "%time"
	format_time = "%a %-d %b %H:%M"
}
FILE
