#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# write configuration file

cat <<- 'FILE' > "$PROOT_DIRECTORY"/home/"$user_name"/.config/i3status/config
# i3status configuration #

general {
	output_format = "i3bar"
	
	color_bad = '#ff0000'
	color_degraded = '#ebcb8b'
	color_good = '#2f343f'
	color_separator = '#ffffff'
	colors = true
	interval = 1
	markup = pango
}

order += "cpu_temperature 0"
order += "cpu_temperature 1"
order += "cpu_temperature 2"
order += "cpu_temperature 3"
order += "cpu_temperature 4"
order += "cpu_temperature 5"
order += "cpu_temperature 6"
order += "cpu_temperature 7"
order += "disk /"
order += "memory"
order += "battery 0"

cpu_temperature 0 {
	format = "[ CPU 0 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone0/temp"
	format_above_threshold = " [ CPU 0 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 1 {
	format = "[ CPU 1 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone1/temp"
	format_above_threshold = " [ CPU 1 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 2 {
	format = "[ CPU 2 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone2/temp"
	format_above_threshold = " [ CPU 2 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 3 {
	format = "[ CPU 3 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone3/temp"
	format_above_threshold = " [ CPU 3 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 4 {
	format = "[ CPU 4 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone4/temp"
	format_above_threshold = " [ CPU 4 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 5 {
	format = "[ CPU 5 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone5/temp"
	format_above_threshold = " [ CPU 5 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 6 {
	format = "[ CPU 6 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone6/temp"
	format_above_threshold = " [ CPU 6 %degress °C + ]"
	max_threshold = 70
}

cpu_temperature 7 {
	format = "[ CPU 7 • %degrees °C ]"
	path = "/sys/class/thermal/thermal_zone7/temp"
	format_above_threshold = " [ CPU 7 %degress °C + ]"
	max_threshold = 70
}

disk "/" {
	format = "\[ SSD %avail • %total \]"
}

memory {
	format = "[ RAM %used • %available ]"
	format_degraded = "MEMORY < %available"
	threshold_degraded = "1G"
}

battery 0 {
	format = "[ %percentage • %status ] "
	path = "/sys/class/power_supply/battery/uevent"
	last_full_capacity = false
	threshold_type = percentage
	low_threshold = 15
	format_down = "X"
	status_chr = "C"
	status_bat = "B"
	status_full = "F"
	status_unk = "?"
}
FILE