#!/bin/bash

# dependencies #

[[ -z $(command -v frobulate) ]] && curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator

. "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="01-21-2022"

# usage #

# prompt

frobulate.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# override main source list file

sed -i									\
	-e 's/ˆ\# deb-src/deb-src/g'		\
	-e '/ˆ\#.*/d'						\
	-e '/ˆ$/d'							/etc/apt/sources.list

# update lists

frobulate.log "apt update" &

frobulate.progress "Forcing refresh..."
echo
