#!/bin/bash

# dependencies #

. "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-22-2021"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

command_expand=$(command -v unminimize)

# defaults #

# functions #

# unminimize system image

console.silence "yes | ${command_expand}" &

console.progress "Expanding..."
echo