#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="07-05-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

color="#2f343f"

edge_value="50"

font_size="10"
regular_font="Sans"
monospace_font="Monospace"

cursor_theme="Adwaita"
icon_theme="Papirus-Dark"
window_theme="Arc-Dark"

# functions ////////////////////////////////////////////////////////////////////

translate_color () {
	# convert hexadecimal to rgba integer range

	read hex <<< "${1}"

	[[ ${hex:0:1} = "#" ]] && hex=${hex:1:6}

	# translate hexadecimal  value

	r=$((16#${hex:0:2}))
	g=$((16#${hex:2:2}))
	b=$((16#${hex:4:2}))

	# calculate float-point integer value

	r_integer=$(( 1000000 * $r / 256 ))
	g_integer=$(( 1000000 * $g / 256 ))
	b_integer=$(( 1000000 * $b / 256 ))

	a_integer=$(( 256 / 256 ))

	# assign rgba gamut

	r=0.${r_integer}
	g=0.${g_integer}
	b=0.${b_integer}

	a=${a_integer}.000000
}

# translate color

translate_color "${color}"

# reset 'xfce4-panel' settings

properties_list=(
	'/panels'
	'/plugins'
)

for property in ${properties_list[@]}
do
	xfconf-query -r -R -v -c 'xfce4-panel' -p "${property}"
done

# set 'xfce4-session' settings

xfconf-query --create -c 'parole'                      -p '/parole/plugins' -t string -s 'tray-icon.so;parole-notify.so;parole-mpris2.so'
xfconf-query --create -c 'parole'                      -p '/plugins/tray/minimize-to-tray' -t bool -s 'true'
xfconf-query --create -c 'parole'                      -p '/plugins/tray/remember-quit-action' -t bool -s 'true'
xfconf-query --create -c 'parole'                      -p '/subtitles/font' -t string -s 'Sans 20'
xfconf-query --create -c 'xfce4-screensaver'           -p '/lock/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/lock/saver-activation/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/lock/status-messages/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/lock/user-switching/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/saver/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/saver/fullscreen-inhibit' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/saver/idle-activation/enabled' -t bool -s 'false'
xfconf-query --create -c 'xfce4-screensaver'           -p '/saver/mode' -t int -s '0'
xfconf-query --create -c 'xfce4-notifyd'               -p '/log-level' -t int -s '0'
xfconf-query --create -c 'xfce4-notifyd'               -p '/log-level-apps' -t int -s '0'
xfconf-query --create -c 'xfce4-notifyd'               -p '/notify-location' -t int -s '2'
xfconf-query --create -c 'xfce4-notifyd'               -p '/primary-monitor' -t int -s '0'
xfconf-query --create -c 'xfce4-appfinder'             -p '/actions' -t string -s ''
xfconf-query --create -c 'xfce4-appfinder'             -p '/always-center' -t bool -s 'true'
xfconf-query --create -c 'xfce4-appfinder'             -p '/category-icon-size' -t int -s '0'
xfconf-query --create -c 'xfce4-appfinder'             -p '/enable-service' -t bool -s 'true'
xfconf-query --create -c 'xfce4-appfinder'             -p '/icon-view' -t bool -s 'true'
xfconf-query --create -c 'xfce4-appfinder'             -p '/item-icon-size' -t int -s '3'
xfconf-query --create -c 'xfce4-appfinder'             -p '/last/pane-position' -t int -s '180'
xfconf-query --create -c 'xfce4-appfinder'             -p '/last/window-height' -t int -s '400'
xfconf-query --create -c 'xfce4-appfinder'             -p '/last/window-width' -t int -s '400'
xfconf-query --create -c 'xfce4-appfinder'             -p '/sort-by-frecency' -t bool -s 'true'
xfconf-query --create -c 'xfce4-appfinder'             -p '/text-beside-icons' -t bool -s 'true'
xfconf-query --create -c 'xsettings'                   -p '/Gdk/WindowScalingFactor' -t int -s '1'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/ButtonImages' -t bool -s 'false'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/CanChangeAccels' -t bool -s 'false'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/ColorPalette' -t string -s 'rgb(38,50,56);rgb(255,152,0);rgb(139,195,74);rgb(255,193,7);rgb(3,169,244);rgb(233,30,99);rgb(0,150,136);rgb(207,216,220);rgb(55,71,79);rgb(255,167,77);rgb(156,204,101);rgb(255,160,0);rgb(129,212,250);rgb(173,20,87);rgb(38,166,154);rgb(236,239,241)'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/CursorThemeName' -t string -s "${cursor_theme}"
xfconf-query --create -c 'xsettings'                   -p '/Gtk/CursorThemeSize' -t int -s '0'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/DecorationLayout' -t string -s 'menu'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/DialogsUseHeader' -t bool -s 'true'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/FontName' -t string -s "${regular_font} ${font_size}"
xfconf-query --create -c 'xsettings'                   -p '/Gtk/IconSizes' -t string -s ''
xfconf-query --create -c 'xsettings'                   -p '/Gtk/KeyThemeName' -t string -s ''
xfconf-query --create -c 'xsettings'                   -p '/Gtk/MenuBarAccel' -t string -s 'F10'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/MenuImages' -t bool -s 'true'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/MonospaceFontName' -t string -s "${monospace_font} ${font_size}"
xfconf-query --create -c 'xsettings'                   -p '/Gtk/TitlebarMiddleClick' -t string -s 'lower'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/ToolbarIconSize' -t int -s '3'
xfconf-query --create -c 'xsettings'                   -p '/Gtk/ToolbarStyle' -t string -s 'icons'
xfconf-query --create -c 'xsettings'                   -p '/Net/CursorBlink' -t bool -s 'true'
xfconf-query --create -c 'xsettings'                   -p '/Net/CursorBlinkTime' -t int -s '1200'
xfconf-query --create -c 'xsettings'                   -p '/Net/DndDragThreshold' -t int -s '8'
xfconf-query --create -c 'xsettings'                   -p '/Net/DoubleClickDistance' -t int -s '5'
xfconf-query --create -c 'xsettings'                   -p '/Net/DoubleClickTime' -t int -s '400'
xfconf-query --create -c 'xsettings'                   -p '/Net/EnableEventSounds' -t bool -s 'false'
xfconf-query --create -c 'xsettings'                   -p '/Net/EnableInputFeedbackSounds' -t bool -s 'false'
xfconf-query --create -c 'xsettings'                   -p '/Net/IconThemeName' -t string -s "${icon_theme}"
xfconf-query --create -c 'xsettings'                   -p '/Net/SoundThemeName' -t string -s 'default'
xfconf-query --create -c 'xsettings'                   -p '/Net/ThemeName' -t string -s "${window_theme}"
xfconf-query --create -c 'xsettings'                   -p '/Xft/Antialias' -t string -s '-1'
xfconf-query --create -c 'xsettings'                   -p '/Xft/HintStyle' -t string -s 'hintnone'
xfconf-query --create -c 'xsettings'                   -p '/Xft/Hinting' -t string -s '-1'
xfconf-query --create -c 'xsettings'                   -p '/Xft/RGBA' -t string -s 'none'
xfconf-query --create -c 'thunar'                      -p '/default-view' -t string -s 'ThunarDetailsView'
xfconf-query --create -c 'thunar'                      -p '/hidden-bookmarks' -t string -s 'file:///' -a
xfconf-query --create -c 'thunar'                      -p '/last-details-view-column-widths' -t string -s '50,50,136,50,50,50,50,50,616,50,50,72,50,281'
xfconf-query --create -c 'thunar'                      -p '/last-details-view-zoom-level' -t string -s 'THUNAR_ZOOM_LEVEL_50_PERCENT'
xfconf-query --create -c 'thunar'                      -p '/last-icon-view-zoom-level' -t string -s 'THUNAR_ZOOM_LEVEL_100_PERCENT'
xfconf-query --create -c 'thunar'                      -p '/last-location-bar' -t string -s 'ThunarLocationButtons'
xfconf-query --create -c 'thunar'                      -p '/last-separator-position' -t int -s '200'
xfconf-query --create -c 'thunar'                      -p '/last-show-hidden' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/last-side-pane' -t string -s 'ThunarShortcutsPane'
xfconf-query --create -c 'thunar'                      -p '/last-sort-column' -t string -s 'THUNAR_COLUMN_NAME'
xfconf-query --create -c 'thunar'                      -p '/last-sort-order' -t string -s 'GTK_SORT_ASCENDING'
xfconf-query --create -c 'thunar'                      -p '/last-view' -t string -s 'ThunarDetailsView'
xfconf-query --create -c 'thunar'                      -p '/last-window-height' -t int -s '600'
xfconf-query --create -c 'thunar'                      -p '/last-window-maximized' -t bool -s 'false'
xfconf-query --create -c 'thunar'                      -p '/last-window-width' -t int -s '1000'
xfconf-query --create -c 'thunar'                      -p '/misc-exec-shell-scripts-by-default' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/misc-middle-click-in-tab' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/misc-open-new-window-as-tab' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/misc-single-click' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/misc-single-click-timeout' -t int -s '1000'
xfconf-query --create -c 'thunar'                      -p '/misc-thumbnail-draw-frames' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/misc-thumbnail-max-file-size' -t int -s '1048576'
xfconf-query --create -c 'thunar'                      -p '/misc-volume-management' -t bool -s 'true'
xfconf-query --create -c 'thunar'                      -p '/shortcuts-icon-size' -t string -s 'THUNAR_ICON_SIZE_24'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace0/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace0/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace0/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace1/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace1/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace1/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace2/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace2/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace2/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace3/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace3/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace3/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace4/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace4/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace4/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace5/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace5/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace5/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace6/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace6/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace6/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace7/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace7/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace7/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace8/color-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace8/image-style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace8/last-image' -t string -s '/data/data/com.termux/files/home/.dextop/dextop-blue.svg'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace0/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace1/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace2/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace3/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace4/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace5/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace6/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace7/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace8/rgba1' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace0/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace1/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace2/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace3/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace4/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace5/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace6/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace7/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/screen0/monitorscreen/workspace8/rgba2' -t double -s ${r} -t double -s ${g} -t double -s ${b} -t double -s ${a}
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/single-workspace-mode' -t bool -s 'true'
xfconf-query --create -c 'xfce4-desktop'               -p '/backdrop/single-workspace-number' -t int -s '0'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/file-icons/show-filesystem' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/file-icons/show-home' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/file-icons/show-removable' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/file-icons/show-trash' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/font-size' -t double -s '10.0'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/gravity' -t int -s '4'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/icon-size' -t int -s '32'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/show-hidden-files' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/show-thumbnails' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/show-tooltips' -t bool -s 'false'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/style' -t int -s '1'
xfconf-query --create -c 'xfce4-desktop'               -p '/desktop-icons/use-custom-font-size' -t bool -s 'true'
xfconf-query --create -c 'xfce4-desktop'               -p '/windowlist-menu/show-sticky-once' -t bool -s 'true'
xfconf-query --create -c 'xfce4-desktop'               -p '/windowlist-menu/show-submenus' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Alt>F2/startup-notify' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Alt>F3/startup-notify' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Alt>space' -t string -s 'xfce4-appfinder --collapsed'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>c' -t string -s 'xfce4-find-cursor'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>e' -t string -s 'termux-email'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>f' -t string -s 'thunar'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>m' -t string -s 'xfce4-settings-manager'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>s' -t string -s 'xfce4-taskmanager'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary><Alt>t' -t string -s 'xfce4-terminal'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Primary>grave' -t string -s 'xfdesktop --menu'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/<Super>r/startup-notify' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/commands/custom/override' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>m' -t string -s 'maximize_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>q' -t string -s 'close_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>t' -t string -s 'shade_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>p' -t string -s 'stick_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>d' -t string -s 'move_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>r' -t string -s 'resize_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>h' -t string -s 'hide_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>Down' -t string -s 'down_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_1' -t string -s 'move_window_workspace_1_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_2' -t string -s 'move_window_workspace_2_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_3' -t string -s 'move_window_workspace_3_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_4' -t string -s 'move_window_workspace_4_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_5' -t string -s 'move_window_workspace_5_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_6' -t string -s 'move_window_workspace_6_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_7' -t string -s 'move_window_workspace_7_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_8' -t string -s 'move_window_workspace_8_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>KP_9' -t string -s 'move_window_workspace_9_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>Left' -t string -s 'left_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>Right' -t string -s 'right_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>Up' -t string -s 'up_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>a' -t string -s 'above_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>d' -t string -s 'show_desktop_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>equal' -t string -s 'add_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>h' -t string -s 'maximize_horiz_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>minus' -t string -s 'del_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>v' -t string -s 'maximize_vert_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Alt>x' -t string -s 'switch_application_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>Down' -t string -s 'move_window_down_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>Left' -t string -s 'move_window_left_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>Right' -t string -s 'move_window_right_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>Up' -t string -s 'move_window_up_workspace_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>f' -t string -s 'fullscreen_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>h' -t string -s 'fill_horiz_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>r' -t string -s 'raiselower_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>v' -t string -s 'fill_vert_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift><Alt>w' -t string -s 'fill_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>Down' -t string -s 'tile_down_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>ISO_Left_Tab' -t string -s 'cycle_reverse_windows_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>KP_1' -t string -s 'tile_down_left_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>KP_3' -t string -s 'tile_down_right_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>KP_7' -t string -s 'tile_up_left_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>KP_9' -t string -s 'tile_up_right_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>Left' -t string -s 'tile_left_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>Right' -t string -s 'tile_right_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary><Shift>Up' -t string -s 'tile_up_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F1' -t string -s 'workspace_1_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F2' -t string -s 'workspace_2_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F3' -t string -s 'workspace_3_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F4' -t string -s 'workspace_4_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F5' -t string -s 'workspace_5_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F6' -t string -s 'workspace_6_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F7' -t string -s 'workspace_7_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F8' -t string -s 'workspace_8_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>F9' -t string -s 'workspace_9_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Primary>Tab' -t string -s 'cycle_windows_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Shift><Alt>Page_Down' -t string -s 'lower_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Shift><Alt>Page_Up' -t string -s 'raise_window_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/<Alt>grave' -t string -s 'popup_menu_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/Down' -t string -s 'down_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/Escape' -t string -s 'cancel_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/Left' -t string -s 'left_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/Right' -t string -s 'right_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/Up' -t string -s 'up_key'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/xfwm4/custom/override' -t bool -s 'true'
xfconf-query --create -c 'xfce4-keyboard-shortcuts'    -p '/providers' -t string -s 'xfwm4' -t string -s 'commands'
xfconf-query --create -c 'xfce4-panel'                 -p '/configver' -t int -s '2'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels' -t int -s '1' -a
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/dark-mode' -t bool -s 'false'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/autohide-behavior' -t int -s '1'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/plugin-ids' -t int -s '1' -t int -s '2' -t int -s '3' -t int -s '4' -t int -s '5' -t int -s '6' -t int -s '7' -t int -s '8' -t int -s '9' -a
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/position' -t string -s 'p=9;x=0;y=0'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/position-locked' -t bool -s 'true'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/popdown-speed' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/panels/panel-1/size' -t int -s '32'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-1' -t string -s 'showdesktop'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-2' -t string -s 'separator'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-2/style' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-3' -t string -s 'directorymenu'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-3/base-directory' -t string -s '/data/data/com.termux/files/home'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-4' -t string -s 'separator'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-4/style' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-5' -t string -s 'pager'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-5/rows' -t int -s '1'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-6' -t string -s 'separator'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-6/style' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7' -t string -s 'systray'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7/hide-new-items' -t bool -s 'false'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7/icon-size' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7/known-legacy-items' -t string -s 'task manager' -a
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7/single-row' -t bool -s 'true'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-7/square-icons' -t bool -s 'true'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-8' -t string -s 'separator'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-8/style' -t int -s '0'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-9' -t string -s 'pulseaudio'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-9/enable-keyboard-shortcuts' -t bool -s 'true'
xfconf-query --create -c 'xfce4-panel'                 -p '/plugins/plugin-9/mpris-players' -t string -s 'parole'
xfconf-query --create -c 'xfwm4'                       -p '/general/activate_action' -t string -s 'switch'
xfconf-query --create -c 'xfwm4'                       -p '/general/borderless_maximize' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/box_move' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/box_resize' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/button_layout' -t string -s 'OTS'
xfconf-query --create -c 'xfwm4'                       -p '/general/button_offset' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/button_spacing' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/click_to_focus' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_apps_only' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_draw_frame' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_hidden' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_minimized' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_minimum' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_preview' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_raise' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_tabwin_mode' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/cycle_workspaces' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/double_click_action' -t string -s 'maximize'
xfconf-query --create -c 'xfwm4'                       -p '/general/double_click_distance' -t int -s '5'
xfconf-query --create -c 'xfwm4'                       -p '/general/double_click_time' -t int -s '250'
xfconf-query --create -c 'xfwm4'                       -p '/general/easy_click' -t string -s 'Alt'
xfconf-query --create -c 'xfwm4'                       -p '/general/focus_delay' -t int -s '250'
xfconf-query --create -c 'xfwm4'                       -p '/general/focus_hint' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/focus_new' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/frame_border_top' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/frame_opacity' -t int -s '100'
xfconf-query --create -c 'xfwm4'                       -p '/general/full_width_title' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/horiz_scroll_opacity' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/inactive_opacity' -t int -s '100'
xfconf-query --create -c 'xfwm4'                       -p '/general/maximized_offset' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/mousewheel_rollup' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/move_opacity' -t int -s '100'
xfconf-query --create -c 'xfwm4'                       -p '/general/placement_mode' -t string -s 'center'
xfconf-query --create -c 'xfwm4'                       -p '/general/placement_ratio' -t int -s '20'
xfconf-query --create -c 'xfwm4'                       -p '/general/popup_opacity' -t int -s '100'
xfconf-query --create -c 'xfwm4'                       -p '/general/prevent_focus_stealing' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/raise_delay' -t int -s '250'
xfconf-query --create -c 'xfwm4'                       -p '/general/raise_on_click' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/raise_on_focus' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/raise_with_any_button' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/repeat_urgent_blink' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/resize_opacity' -t int -s '100'
xfconf-query --create -c 'xfwm4'                       -p '/general/scroll_workspaces' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/shadow_delta_height' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/shadow_delta_width' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/shadow_delta_x' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/shadow_delta_y' -t string -s '-3'
xfconf-query --create -c 'xfwm4'                       -p '/general/shadow_opacity' -t int -s '50'
xfconf-query --create -c 'xfwm4'                       -p '/general/show_app_icon' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/show_dock_shadow' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/show_frame_shadow' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/show_popup_shadow' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/snap_resist' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/snap_to_border' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/snap_to_windows' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/snap_width' -t int -s "${edge_value}"
xfconf-query --create -c 'xfwm4'                       -p '/general/theme' -t string -s "${window_theme}"
xfconf-query --create -c 'xfwm4'                       -p '/general/tile_on_move' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_alignment' -t string -s 'center'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_font' -t string -s "${regular_font} ${font_size}"
xfconf-query --create -c 'xfwm4'                       -p '/general/title_horizontal_offset' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_shadow_active' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_shadow_inactive' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_vertical_offset_active' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/title_vertical_offset_inactive' -t int -s '0'
xfconf-query --create -c 'xfwm4'                       -p '/general/titleless_maximize' -t bool -s 'true'
xfconf-query --create -c 'xfwm4'                       -p '/general/toggle_workspaces' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/unredirect_overlays' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/urgent_blink' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/use_compositing' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/vblank_mode' -t string -s 'auto'
xfconf-query --create -c 'xfwm4'                       -p '/general/workspace_count' -t int -s '9'
xfconf-query --create -c 'xfwm4'                       -p '/general/workspace_names' -t string -s 'Workspace 01' -t string -s 'Workspace 02' -t string -s 'Workspace 03' -t string -s 'Workspace 04' -t string -s 'Workspace 05' -t string -s 'Workspace 06' -t string -s 'Workspace 07' -t string -s 'Workspace 08' -t string -s 'Workspace 09'
xfconf-query --create -c 'xfwm4'                       -p '/general/wrap_cycle' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/wrap_layout' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/wrap_resistance' -t int -s "${edge_value}"
xfconf-query --create -c 'xfwm4'                       -p '/general/wrap_windows' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/wrap_workspaces' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/zoom_desktop' -t bool -s 'false'
xfconf-query --create -c 'xfwm4'                       -p '/general/zoom_pointer' -t bool -s 'false'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/show-status-icon' -t bool -s 'true'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/window-height' -t int -s '600'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/window-width' -t int -s '600'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/interface/handle-position' -t int -s '100'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/interface/more-precision' -t bool -s 'false'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/interface/more-process-tree' -t bool -s 'true'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/interface/refresh-rate' -t int -s '500'
xfconf-query --create -c 'xfce4-taskmanager'           -p '/interface/show-all-processes' -t bool -s 'true'

# set 'xfce4-terminal' settings

mkdir -p "${HOME}"/.config/xfce4/terminal

cat << 'FILE' > "${HOME}"/.config/xfce4/terminal/terminalrc
[Configuration]
MiscAlwaysShowTabs=FALSE
MiscBell=FALSE
MiscBellUrgent=FALSE
MiscBordersDefault=TRUE
MiscCursorBlinks=FALSE
MiscCursorShape=TERMINAL_CURSOR_SHAPE_BLOCK
MiscDefaultGeometry=80x24
MiscInheritGeometry=FALSE
MiscMenubarDefault=FALSE
MiscMouseAutohide=FALSE
MiscMouseWheelZoom=TRUE
MiscToolbarDefault=FALSE
MiscConfirmClose=TRUE
MiscCycleTabs=TRUE
MiscTabCloseButtons=TRUE
MiscTabCloseMiddleClick=TRUE
MiscTabPosition=GTK_POS_TOP
MiscHighlightUrls=TRUE
MiscMiddleClickOpensUri=FALSE
MiscCopyOnSelect=TRUE
MiscShowRelaunchDialog=TRUE
MiscRewrapOnResize=TRUE
MiscUseShiftArrowsToScroll=FALSE
MiscSlimTabs=FALSE
MiscNewTabAdjacent=FALSE
MiscSearchDialogOpacity=100
MiscShowUnsafePasteDialog=FALSE
MiscRightClickAction=TERMINAL_RIGHT_CLICK_ACTION_CONTEXT_MENU
FontName=Monospace 10
ScrollingBar=TERMINAL_SCROLLBAR_NONE
ColorForeground=#ececefeff1f1
ColorBackground=#2f2f34343f3f
ColorPalette=#263238;#ff9800;#8bc34a;#ffc107;#03a9f4;#e91e63;#009688;#cfd8dc;#37474f;#ffa74d;#9ccc65;#ffa000;#81d4fa;#ad1457;#26a69a;#eceff1
FILE

# restart applications and modules

applications_list=(
	xfce4-panel
	xfce4-terminal
)

for application in ${applications_list[@]}
do
	pkill -9 "${application}"
done
