#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="05-25-2024"

# usage ////////////////////////////////////////////////////////////////////////

# prompt

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

failsafe_intent () {

	# ref.: https://github.com/termux/termux-packages/issues/10871

	# run failsafe termux package and repository update:
	# mitigate general deployment setup issues
	# mitigate skipped packages on install

	frobulator.fwd "Please wait${marker_elp}"
	echo

	yes | apt update       > "${sink}" 2>&1

	yes | apt full-upgrade > "${sink}" 2>&1

}

failsafe_intent

frobulator.update

frobulator.upgrade

list=(
	curl
	sudo
)

# run failsafe package install:
# prevents container side dependencies mismatch

frobulator.failsafe ${list[@]} &

frobulator.process "Please wait"

list=()
