#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-r|--root)
			USERNAME="root"

			login_option="root"

			shift
		;;
			
		-u|--username)
			USERNAME="${2}"

			login_option="user"

			shift
		;;

		-a|--application)
			APPLICATION="${2}"

			login_option="application"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} | [USERNAME] | [APPLICATION] | [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-r, --root \t\t Specify 'root' as user for session login."
			echo -e "-u, --username \t Specify 'user' for session login."
			echo -e "-a, --application \t Specify application to start on session login."
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

			"")
				# handle empty argument:
				# use default values specified in script

				:
			;;

		*)
			echo
			echo -e "Usage: ${script} | [USERNAME] | [APPLICATION] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# verify user existence:
# loop through container's /etc/passwd and make sure 'user' exists
# and corresponds to 'username' then source environment variables from file
# default to 'root' if 'username' is invalid, not specified or does not exist

last_entry="$(tail -n 1 "${CONTAINER_DIRECTORY}"/etc/passwd)"

# authentication #

console.fwd "Authenticating..."
echo

while read -r entry
do
	IFS=':'

	read USER _ USER_ID GROUP_ID GECOS HOME SHELL <<< "${entry}"

	IFS=','

	read FULL_NAME ROOM_NUMBER WORK_PHONE HOME_PHONE USER_EMAIL <<< "${GECOS}"

	# reset IFS

	IFS=' '

	# messages:
	# verify login options and parameters
	
	if [[ -z "${USERNAME}" ]]
	then
		USERNAME="root"
		
		console.wrn "No user name - Defaulting [ '${USERNAME}' ]."
		echo

		# break out of loop - empty "${USERNAME}" - default to 'root'

		break
	fi

	if [[ "${login_option}" == "root" ]]
	then
		console.wrn "Logging in [ '${USERNAME}' ]."
		echo

		# break out of loop - login as 'root'

		break
	fi

	if [[ "${USERNAME}" == "${USER}" ]]
	then
		console.scs "Valid user name [ '${USERNAME}' ]."
		echo

		# break out of loop - matching "${USERNAME}"

		break
	fi

	if [[ "${entry}" == "${last_entry}" ]]
	then
		USERNAME="root"
	
		console.err "Invalid user name - Defaulting [ '${USERNAME}' ]."
		echo
	fi

	# specify login defaults
	
	if [[ -z "${USERNAME}" ]] ||  [[ "${login_option}" == "root" ]] || [[ "${entry}" == "${last_entry}" ]]
	then
		USER="root"
		USER_ID=0
		GROUP_ID=0
		FULL_NAME="root"
		HOME="/root"
		SESSION_NAME="CONSOLE"
		SHELL="/usr/bin/bash"
	fi

done < "${CONTAINER_DIRECTORY}"/etc/passwd

# system #

# explicit 'proot' command setup defaults:
# used to specify the desktop session:
# login format / environment /pathnv'

# set path:
# in order of retreival

PATH=""

# container

[ -d "${CONTAINER_DIRECTORY}"/usr/local/sbin ]									&& PATH+="/usr/local/sbin:"
[ -d "${CONTAINER_DIRECTORY}"/usr/local/bin ]									&& PATH+="/usr/local/bin:"
[ -d "${CONTAINER_DIRECTORY}"/usr/sbin ]										&& PATH+="/usr/sbin:"
[ -d "${CONTAINER_DIRECTORY}"/usr/sbin ]										&& PATH+="/usr/bin:"
[ -d "${CONTAINER_DIRECTORY}"/sbin ]											&& PATH+="/sbin:"
[ -d "${CONTAINER_DIRECTORY}"/bin ]												&& PATH+="/bin:"

# termux

[ -d "${PREFIX}"/sbin ]															&& PATH+="${PREFIX}/sbin:"
[ -d "${PREFIX}"/bin ]															&& PATH+="${PREFIX}/bin:"

# android

[ -d /system/sbin ]																&& PATH+="/system/sbin:"
[ -d /system/bin ]																&& PATH+="/system/bin:"

PATH="${PATH}"

# set environment

COLORTERM="truecolor"
DISPLAY=":1"
EDITOR="nano"
HOME="/home/${USER}"
LANG="C.UTF-8"
LOCALHOST="127.0.0.1"
PAGER="less"
SHELL="/usr/bin/bash"
TMPDIR="/tmp"

# base

[ "${desktop_option}" = "none" ]												&& SESSION_NAME="CONSOLE"

# i3 #

[ -f "${CONTAINER_DIRECTORY}"/usr/bin/i3 ]										&& SESSION_NAME="I3WM"

[ "${desktop_option}" = "i3wm" ]												&& SESSION="i3wm"
[ "${desktop_option}" = "i3wm" ]												&& SESSION_LOADER="i3"

[ "${desktop_option}" = "i3wm" ]												&& BROWSER="surf"
[ "${desktop_option}" = "i3wm" ]												&& EMULATOR="st"
[ "${desktop_option}" = "i3wm" ]												&& RUNNER="dmenu"
[ "${desktop_option}" = "i3wm" ]												&& VISUAL="nano"

# xfce #

[ -f "${CONTAINER_DIRECTORY}"/usr/bin/xfwm4 ]									&& SESSION_NAME="XFCE"

[ "${desktop_option}" = "xfce" ]												&& SESSION="xfce"
[ "${desktop_option}" = "xfce" ]												&& SESSION_LOADER="xfce4-session"
[ "${desktop_option}" = "xfce" ]												&& SETTINGS_MANAGER="xfsettingsd"
[ "${desktop_option}" = "xfce" ]												&& WINDOW_MANAGER="xfwm4"

[ "${desktop_option}" = "xfce" ]												&& BROWSER="midori"
[ "${desktop_option}" = "xfce" ]												&& EMULATOR="xfce4-terminal"
[ "${desktop_option}" = "xfce" ]												&& RUNNER="xfce4-appfinder"
[ "${desktop_option}" = "xfce" ]												&& VISUAL="mousepad"

# defaults #

[ -z "${MOUNT_DIRECTORY}" ]														&& MOUNT_DIRECTORY="${PREFIX%/*}/mnt"
[ -z "${CONTAINER_DIRECTORY}" ]													&& CONTAINER_DIRECTORY="${PREFIX%/*}/img"

[ -z "${BROWSER}" ]																&& BROWSER="${BROWSER}"
[ -z "${COLORTERM}" ]															&& COLORTERM="${COLORTERM}"
[ -z "${SESSION}" ]																&& SESSION="${SESSION}"
[ -z "${EDITOR}" ]																&& EDITOR="${EDITOR}"
[ -z "${PAGER}" ]																&& PAGER="${PAGER}"
[ -z "${RUNNER}" ]																&& RUNNER="${RUNNER}"
[ -z "${SHELL}" ]																&& SHELL="${SHELL}"
[ -z "${TERMINAL}" ]															&& TERMINAL="${TERM}"
[ -z "${VISUAL}" ]																&& VISUAL="${VISUAL}"

# verify application argument

if [ ! -z "${APPLICATION}" ]
then
	console.scs "Valid application name" "[ ${APPLICATION} ]"
	echo
	
	if [ ! -f "${CONTAINER_DIRECTORY}"/usr/bin/"${APPLICATION}" ]
	then
		console.err "Invalid application name" "[ ${APPLICATION} ]"
		echo
		
		unset "${APPLICATION}"
	fi

	console.fwd "Starting application" "[ ${SESSION_NAME} // ${USER} // ${APPLICATION} ]"
	echo
else
	console.fwd "Starting session" "[ ${SESSION_NAME} // ${USER} ]"
	echo
fi

# clear #

console.clear

# assume termux-exec is present - unset LD_PRELOAD

unset LD_PRELOAD

# setup 'proot' command arguments

unset "${session_command}"

session_command+="proot"
session_command+=" --kill-on-exit"
session_command+=" --link2symlink"
session_command+=" --rootfs=${CONTAINER_DIRECTORY}"
session_command+=" --change-id=${USER_ID}:${GROUP_ID}"
session_command+=" --pwd=${HOME}"
[ -d "/apex" ]                         && session_command+=" --bind=/apex"
[ -d "/data" ]                         && session_command+=" --bind=/data"
[ -d "/dev" ]                          && session_command+=" --bind=/dev"
[ -e "/dev/urandom" ]                  && session_command+=" --bind=/dev/urandom:/dev/random"
[ -e "/linkerconfig/ld.config.txt" ]   && session_command+=" --bind=/linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt"
[ -f "/plat_property_contexts" ]       && session_command+=" --bind=/plat_property_contexts:/plat_property_contexts"
[ -f "/property_contexts" ]            && session_command+=" --bind=/property_contexts:/property_contexts"
[ -d "/proc" ]                         && session_command+=" --bind=/proc"
[ -d "/proc/self/fd" ]                 && session_command+=" --bind=/proc/self/fd:/dev/fd"
[ -e "/proc/self/fd/0" ]               && session_command+=" --bind=/proc/self/fd/0:/dev/stdin"
[ -e "/proc/self/fd/1" ]               && session_command+=" --bind=/proc/self/fd/1:/dev/stdout"
[ -e "/proc/self/fd/2" ]               && session_command+=" --bind=/proc/self/fd/2:/dev/stderr"
[ -d "/storage" ]                      && session_command+=" --bind=/storage"
[ -d "/sys" ]                          && session_command+=" --bind=/sys"
[ -d "/system" ]                       && session_command+=" --bind=/system"
[ -d "/vendor" ]                       && session_command+=" --bind=/vendor"
[ -d "${PREFIX%/*}"/home ]             && session_command+=" --bind=${PREFIX%/*}/home:/home/${USER}"
[ -d "${PREFIX%/*}"/storage/external ] && session_command+=" --bind=${PREFIX%/*}/storage/external:/media/external"
[ -d "${PREFIX%/*}"/storage/internal ] && session_command+=" --bind=${PREFIX%/*}/storage/internal:/media/internal"
[ -x "${PREFIX%/*}"/usr/bin/htop ]     && session_command+=" --bind="${PREFIX%/*}"/usr/bin/top:/usr/bin/htop"
[ -x "${PREFIX%/*}"/usr/bin/kill ]     && session_command+=" --bind="${PREFIX%/*}"/usr/bin/kill:/usr/bin/kill"
[ -x "${PREFIX%/*}"/usr/bin/pgrep ]    && session_command+=" --bind="${PREFIX%/*}"/usr/bin/pgrep:/usr/bin/pgrep"
[ -x "${PREFIX%/*}"/usr/bin/pkill ]    && session_command+=" --bind="${PREFIX%/*}"/usr/bin/pkill:/usr/bin/pkill"
[ -x "${PREFIX%/*}"/usr/bin/ps ]       && session_command+=" --bind="${PREFIX%/*}"/usr/bin/ps:/usr/bin/ps"
[ -x "${PREFIX%/*}"/usr/bin/top ]      && session_command+=" --bind="${PREFIX%/*}"/usr/bin/top:/usr/bin/top"
session_command+=" env -i"
session_command+=" ANDROID_ART_ROOT=${ANDROID_ART_ROOT}"
session_command+=" ANDROID_DATA=${ANDROID_DATA}"
session_command+=" ANDROID_I18N_ROOT=${ANDROID_I18N_ROOT}"
session_command+=" ANDROID_ROOT=${ANDROID_ROOT}"
session_command+=" ANDROID_RUNTIME_ROOT=${ANDROID_RUNTIME_ROOT}"
session_command+=" ANDROID_TZDATA_ROOT=${ANDROID_TZDATA_ROOT}"
session_command+=" BOOTCLASSPATH=${BOOTCLASSPATH}"
session_command+=" DEX2OATBOOTCLASSPATH=${DEX2OATBOOTCLASSPATH}"
session_command+=" PREFIX=${PREFIX}"
session_command+=" MAIN_DIRECTORY=${PREFIX%/*}"
session_command+=" BINARIES_DIRECTORY=${PREFIX}/bin"
session_command+=" LIBRARIES_DIRECTORY=${PREFIX}/lib"
session_command+=" CONTAINER_DIRECTORY=${CONTAINER_DIRECTORY}"
session_command+=" MOUNT_DIRECTORY=${MOUNT_DIRECTORY}"
session_command+=" SESSION=${SESSION}"
session_command+=" SESSION_NAME=${SESSION_NAME}"
session_command+=" SESSION_LOADER=${SESSION_LOADER}"
session_command+=" SETTINGS_MANAGER=${SETTINGS_MANAGER}"
session_command+=" WINDOW_MANAGER=${WINDOW_MANAGER}"
session_command+=" APPLICATION=${APPLICATION}"
session_command+=" BROWSER=${BROWSER}"
session_command+=" EDITOR=${EDITOR}"
session_command+=" PAGER=${PAGER}"
session_command+=" RUNNER=${RUNNER}"
session_command+=" VISUAL=${VISUAL}"
session_command+=" COLORTERM=${COLORTERM}"
session_command+=" DISPLAY=${DISPLAY}"
session_command+=" HOME=${HOME}"
session_command+=" LANG=${LANG}"
session_command+=" LOCALHOST=${LOCALHOST}"
session_command+=" PATH=${PATH}"
session_command+=" SHELL=${SHELL}"
session_command+=" TERM=${TERMINAL}"
session_command+=" TMPDIR=${TMPDIR}"
session_command+=" USER=${USER}"
session_command+=" XDG_RUNTIME_DIR=/run/user/${USER_ID}"
session_command+=" XDG_CACHE_HOME=${HOME}/.cache"
session_command+=" XDG_CONFIG_HOME=${HOME}/.config"
session_command+=" XDG_DATA_HOME=${HOME}/.local/share"
session_command+=" XDG_DATA_DIRS=/usr/local/share:/usr/share"
session_command+=" XDG_CONFIG_DIRS=/etc/xdg"
session_command+=" XAUTHORITY=${XDG_RUNTIME_DIR}/.Xauthority"
session_command+=" ${SHELL} --login"

# execute 'proot'

exec ${session_command}
