#!/bin/bash

# dependencies #

[[ -z $(command -v console) ]] && curl -s -L get.trmnl.me/console/console > "${PREFIX}"/bin/console

. "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="01-21-2022"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

command_expand=$(command -v unminimize)

# defaults #

# functions #

# unminimize system image

console.silence "yes | ${command_expand}" &

console.progress "Expanding..."
echo
