#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# functions #

# set network

# hostname

echo '${HOSTNAME}'																> "${ROOT_DIRECTORY}"/etc/hostname

# hosts

echo '# IPv4 #'																	>  "${ROOT_DIRECTORY}"/etc/hosts

echo '127.0.0.1	localhost.localdomain'											>> "${ROOT_DIRECTORY}"/etc/hosts
echo '127.0.0.1	localhost'														>> "${ROOT_DIRECTORY}"/etc/hosts

echo '# IPv6 #'																	>> "${ROOT_DIRECTORY}"/etc/hosts

echo '::1			localhost.localdomain'										>> "${ROOT_DIRECTORY}"/etc/hosts
echo '::1			localhost'													>> "${ROOT_DIRECTORY}"/etc/hosts
echo '::1			ip6-localhost'												>> "${ROOT_DIRECTORY}"/etc/hosts
echo '::1			ip6-loopbak'												>> "${ROOT_DIRECTORY}"/etc/hosts
echo 'fe00::0		ip6-localnet'												>> "${ROOT_DIRECTORY}"/etc/hosts
echo 'fe00::0		ip6-mcastprefix'											>> "${ROOT_DIRECTORY}"/etc/hosts
echo 'ff02::1		ip6-allnodes'												>> "${ROOT_DIRECTORY}"/etc/hosts
echo 'ff02::2		ip6-allrouters'												>> "${ROOT_DIRECTORY}"/etc/hosts
echo 'ff02::3		ip6-allhosts'												>> "${ROOT_DIRECTORY}"/etc/hosts

# nameserver

echo 'nameserver 1.1.1.1'														>  "${ROOT_DIRECTORY}"/etc/resolv.conf
echo 'nameserver 1.0.0.1'														>> "${ROOT_DIRECTORY}"/etc/resolv.conf