#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-26-2023"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-c|--console)
			environment="console"
		;;

		-e|--environment)
			environment="${2}"
		;;

		-t|--termux)
			option="termux"
		;;

		-n|--container)
			option="container"
		;;

		-b|--backup)
			option="backup"
		;;

		-u|--update)
			option="update"
			update="${2}"

			if [ "${update}" = "utility" ]
			then
				utility="${3}"

				shift
			fi

			if [ "${update}" = "shell" ]
			then
				shell="${3}"

				shift
			fi

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -c | -e [Environment] | -t | -n | -b | -u [Update Type] [Utility Name] | [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-c, --console        Setup Console access to environment and utilities only."
			echo
			echo -e "-e, --environment    Setup desktop environment and utilities."
			echo
			echo -e "                     [ i3 ]"
			echo -e "                     [ xfce ] [ Default ]"
			echo
			echo -e "-t, --termux         Setup Termux environment and utilities only."
			echo
			echo -e "-n, --container      Setup Container environment and utilities only."
			echo
			echo -e "-b, --backup         Backup Termux user configuration files."
			echo
			echo -e "-u, --update         Update application packages and utilities."
			echo
			echo -e "                     [ all ]"
			echo -e "                     [ dextop ] [ Default ]"
			echo -e "                     [ utility ]"
			echo -e "                     [ additions ]"
			echo -e "                     [ shell ]"
			echo -e "                     [ termux ]"
			echo -e "                     [ preferences ]"
			echo
			echo -e "-h, --help           Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} -c | -e [Environment] | -t | -n | -b | -u [Update] [Name] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# clear ////////////////////////////////////////////////////////////////////////

frobulator.clear

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y-%H-%M-%S")

# defaults /////////////////////////////////////////////////////////////////////

if [ ! -f "${HOME}"/.dextop/dextop-environment ]
then
	if [ -z "${environment}" ]
	then
		environment="xfce"

		frobulator.flag "${environment}" "${HOME}"/.dextop dextop-environment

		unset environment
	fi
fi

if [ ! -f "${HOME}"/.dextop/dextop-session ]
then
	if [ -z "${session}" ]
	then
		if [[ $(cat "${HOME}"/.dextop/dextop-environment) = "i3" ]]
		then
			session="i3"
		fi

		if [[ $(cat "${HOME}"/.dextop/dextop-environment) = "xfce" ]]
		then
			session="xfce4-session"
		fi

		frobulator.flag "${session}" "${HOME}"/.dextop dextop-session

		unset session
	fi
fi

if [ -z "${utility}" ]
then
	utility="all"
fi

if [ -z "${shell}" ]
then
	shell="all"
fi

if [ -z "${ROOT}" ]
then
	ROOT=("${PREFIX}"/cnt/*/*)
fi

# functions ////////////////////////////////////////////////////////////////////

failsafe_intent () {

	frobulator.stp "Please wait..."
	echo
	
	yes | apt update 			> "${sink}" 2>&1

	yes | apt install root-repo > "${sink}" 2>&1
	
	yes | apt install x11-repo 	> "${sink}" 2>&1
	
	yes | apt update 			> "${sink}" 2>&1

	yes | apt upgrade 			> "${sink}" 2>&1 &
	
	frobulator.progress "upgrade"

}

environment_intent () {

	# generate container environement

	# set path:
	# in order of retreival

	PATH=""

	# container

	[ -d "${ROOT}"/usr/local/sbin ] && PATH+="/usr/local/sbin:"
	[ -d "${ROOT}"/usr/local/bin ]  && PATH+="/usr/local/bin:"
	[ -d "${ROOT}"/usr/sbin ]       && PATH+="/usr/sbin:"
	[ -d "${ROOT}"/usr/bin ]        && PATH+="/usr/bin:"
	[ -d "${ROOT}"/sbin ]           && PATH+="/sbin:"
	[ -d "${ROOT}"/bin ]            && PATH+="/bin:"

	# termux

	[ -d "${HOME}"/.local/sbin ] && PATH+="${HOME}/.local/sbin:"
	[ -d "${HOME}"/.local/bin ]  && PATH+="${HOME}/.local/bin:"
	[ -d "${HOME}"/.sbin ]       && PATH+="${HOME}/.sbin:"
	[ -d "${HOME}"/.bin ]        && PATH+="${HOME}/.bin:"

	[ -d "${PREFIX}"/sbin ]      && PATH+="${PREFIX}/sbin:"
	[ -d "${PREFIX}"/bin ]       && PATH+="${PREFIX}/bin:"

	# android

	[ -d /system/sbin ] && PATH+="/system/sbin:"
	[ -d /system/bin ]  && PATH+="/system/bin:"

	PATH="${PATH}"
}

container_intent () {

	# make container setup location known

	if [ $# -eq 0 ]
	then
		ROOT=("${PREFIX}"/cnt/*/*)

		export ROOT="${ROOT}"

		return
	fi

	# define root system default setup parameters

	USER_ID="0"
	GROUP_ID="0"

	ROOT_HOME="/root"

	LANG="C.UTF-8"

	# run container setup commands through 'proot'

	# assume 'termux-exec' is installed

	unset LD_PRELOAD

	# generate environement paths

	environment_intent

	# run as 'root' with default system parameters

	proot																	\
		--kill-on-exit														\
		--link2symlink														\
		--rootfs="${ROOT}"													\
		--change-id="${USER_ID}":"${GROUP_ID}"								\
		--pwd="${ROOT_HOME}"												\
		--bind=/apex:/apex													\
		--bind=/data:/data													\
		--bind=/dev:/dev													\
		--bind=/dev/urandom:/dev/random										\
		--bind=/linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt		\
		--bind=/proc:/proc													\
		--bind=/proc/self/fd:/dev/fd										\
		--bind=/proc/self/fd/0:/dev/stdin									\
		--bind=/proc/self/fd/1:/dev/stdout									\
		--bind=/proc/self/fd/2:/dev/stderr									\
		--bind=/storage:/storage											\
		--bind=/sys:/sys													\
		--bind=/system:/system												\
		--bind=/vendor:/vendor												\
		--bind=/data/data/com.termux/files/home:"${ROOT_HOME}"				\
			env 															\
				--ignore-environment										\
					PREFIX="${PREFIX}"										\
					PATH="${PATH}"											\
					HOME="${ROOT_HOME}"										\
					LANG="${LANG}"											\
					TERM="${TERM}"											\
																			${@}
}

architecture_intent () {

	# list supported processor architechtures

	cpu_architectures=(
		aarch64
		arm
		amd64
		i*86
		x86_64
	)

	# test processor architecture string

	device_architecture="$(uname -m)"

	for i in ${!cpu_architectures[@]}
	do
		if [[ "${device_architecture}" != "${cpu_architectures[i]}" ]]
		then

			frobulator.scs "Supported device architecture" "[ ${device_architecture} ]"
			echo

			frobulator.fwd "Proceeding..."
			echo

			break
		else
			frobulator.wrn "Unsupported device architecture" "[ ${device_architecture} ]"
			echo

			frobulator.fwd "Aborting..."
			echo

			frobulator.stp "Exiting."
			echo

			exit 1
		fi
	done

	clear
}

reload_intent () {

	# termux settings reload:
	# update command line interface with dextop settings

	unset settings_command

	settings_command+="am broadcast"
	settings_command+=" --user 0"
	settings_command+=" -a com.termux.app.reload_style"
	settings_command+=" com.termux"

	frobulator.silence "${settings_command}"
}

backup_intent () {

	backup_name="dextop-backup"
	backup_extension="tar.gz"

	backup_directory="${HOME}"

	backup_archive="${backup_name}-${stamp}.${backup_extension}"

	frobulator.inf "Generating backup" "[ ${backup_archive} ]"
	echo

	tar											\
		--create								\
		--gzip									\
			--exclude="${backup_name}"*			\
				--file="${backup_archive}"		"${backup_directory}" > "${sink}" 2>&1 &

	frobulator.progress "archive" "[ ${backup_directory} ]"
}

preferences_intent () {

	# termux settings and properties

	settings_list+=(
		termux-colors
		termux-font
		termux-properties
		termux-reload-settings
	)

	frobulator.download get.trmnl.me "${HOME}"/.local/bin ${settings_list[@]}

	frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-colors     colors.properties
	frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-font       font.ttf
	frobulator.link "${HOME}"/.local/bin "${HOME}"/.termux termux-properties termux.properties

	reload_intent

	settings_list=()
}

dextop_intent () {

	# load dextop deployment script

	frobulator.download run.dxtp.app "${HOME}"/.local/bin dextop
}

utility_intent () {

	# load dextop utilities

	utilities_list+=(
		termux-packages
		termux-failsafe
		termux-update
		termux-storage
		termux-additions
		container-expansion
		container-image
		container-packages
		container-failsafe
		container-session
		container-settings
		container-user
	)

	if [[ "${option}" = "update" ]]
	then
		if [[ ${utilities_list[@]} =~ "${utility}" ]]
		then
			frobulator.download get.dxtp.app "${HOME}"/.local/bin "${utility}"

		elif [[ "${utility}" = "all" ]]
		then
			frobulator.download get.dxtp.app "${HOME}"/.local/bin ${utilities_list[@]}

		else
			frobulator.err "Unknown utility name" "[ '${utility}' ]"
			echo

			frobulator.fwd "Listing known utilities..."
			echo

			frobulator.timeout

			IFS=$'\n'

			printf "${marker_nul} %s\n" ${utilities_list[@]}

			echo

			IFS=''

			frobulator.msg "Review utility name spelling and try again."
			echo

			frobulator.inf "Update all known utilities using 'all' argument."
			echo

			exit 1
		fi
	else
		frobulator.download get.dxtp.app "${HOME}"/.local/bin ${utilities_list[@]}
	fi

	utilities_list=()
}

shell_intent () {

	# load shell files

	shell_list+=(
		bash-aliases
		bash-configuration
		bash-functions
		bash-login
		bash-logout
		bash-profile
	)

	if [[ "${option}" = "update" ]]
	then
		if [[ ${shell_list[@]} =~ "${shell}" ]]
		then
			frobulator.download get.trmnl.me "${HOME}"/.local/bin "${shell}"

		elif [[ "${shell}" = "all" ]]
		then
			frobulator.download get.trmnl.me "${HOME}"/.local/bin ${shell_list[@]}

		else
			frobulator.err "Unknown shell item name" "[ '${shell}' ]"
			echo

			frobulator.fwd "Listing known shell items..."
			echo

			frobulator.timeout

			IFS=$'\n'

			printf "${marker_nul} %s\n" ${shell_list[@]}

			echo

			IFS=''

			frobulator.msg "Review shell item name spelling and try again."
			echo

			frobulator.inf "Update all known shell items using 'all' argument."
			echo

			exit 1
		fi

	else
		frobulator.download get.trmnl.me "${HOME}"/.local/bin ${shell_list[@]}

		if [ -z "${option}" ] || [ "${option}" = "termux" ]
		then
			# link to user home

			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-aliases       .bash_aliases
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-configuration .bashrc
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-configuration .bash_configuration
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-functions     .bash_functions
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-login         .bash_login
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-logout        .bash_logout
			frobulator.link "${HOME}"/.local/bin "${HOME}"      bash-profile       .bash_profile

			frobulator.file "${HOME}" .hushlogin
		fi

		if [ "${option}" = "termux" ]
		then
			:
		else
			# link to root home

			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-aliases       .bash_aliases
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-configuration .bashrc
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-configuration .bash_configuration
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-functions     .bash_functions
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-login         .bash_login
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-logout        .bash_logout
			frobulator.link "${HOME}"/.local/bin "${ROOT}"/root bash-profile       .bash_profile

			frobulator.file "${ROOT}"/root .hushlogin
		fi
	fi

	shell_list=()

}

directories_intent () {

	# generate dextop required directories

	directories_list+=(
		bkp
		cnt
		img
		mnt
		media
		storage
	)

	frobulator.directory "${PREFIX}" ${directories_list[@]}

	directories_list=()

	# generate home directory structure

	directories_list+=(
		Desktop
		Documents
		Downloads
		Music
		Pictures
		Public
		Templates
		Videos
	)

	frobulator.directory "${HOME}" ${directories_list[@]}

	directories_list=()

	# generate root directory structure

	directories_list+=(
		bin
		bkp
		cnt
		etc
		img
		lib
		mnt
		opt
		tmp
		media
		storage
	)

	for directory in ${directories_list[@]}
	do
        frobulator.link "${PREFIX}" "${PREFIX%/*}" "${directory}"
    done

	directories_list=()
}

bookmarks_intent () {

	# generate file browser bookmarks

	directories_list=(
		"${PREFIX}"/cnt
		"${PREFIX}"/media/external
		"${PREFIX}"/media/internal
	)

	labels_list=(
		Container
		External
		Internal
	)

	for (( i=0 ; i<${#directories_list[@]} ; i++ ))
	do
		if [ -d "${directory}" ]
		then
			frobulator.write "file://${directories_list[$i]} ${labels_list[$i]}" "${HOME}"/.config/gtk-3.0 bookmarks
		fi
	done

	directories_list=()

	labels_list=()
}

additions_intent () {

	# load additions files

	additions_list+=(
		dextop-additions
	)

	frobulator.download get.dxtp.app "${HOME}"/.local/bin ${additions_list[@]}

	additions_list=()
}

backgrounds_intent () {

	# load background files

	backgrounds_list=(
		dextop-black.svg
		dextop-blue.svg
		dextop-coral.svg
		dextop-grey.svg
	)

	frobulator.download get.dxtp.app "${HOME}"/.dextop ${backgrounds_list[@]}

	backgrounds_list=()
}

icons_intent () {

	# select icon themes

	icons_list+=(
		Adwaita
		Papirus
		Papirus-Dark
		Papirus-Light
		default
		hicolor
	)

	# keep icon theme selections

	frobulator.keep "${PREFIX}"/share/icons ${icons_list[@]}

	icons_list=()

	# link icons theme directories

	frobulator.link "${PREFIX}"/share "${HOME}" icons .icons
}

themes_intent () {

	# select themes

	files_list+=(
		Arc
		Arc-Dark
		Arc-Darker
		Arc-Lighter
	)

	# keep theme selections

	frobulator.keep "${ROOT}"/usr/share/themes ${files_list[@]}

	files_list=()

	# link theme directories

	frobulator.link "${ROOT}"/usr/share "${HOME}" themes .themes
}

session_intent () {

	# start session

	cd "${HOME}"

	"${PREFIX}"/bin/login
}

# architecture check ///////////////////////////////////////////////////////////

frobulator.log "architecture_intent"

# options //////////////////////////////////////////////////////////////////////

if [ "${option}" = "backup" ]
then
	backup_intent
fi

if [ "${option}" = "update" ]
then

	if [[ "${update}" = [aA][lL][lL] ]]
	then
		frobulator.inf "Updating" "[ ${update} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		preferences_intent
		
		dextop_intent

		utility_intent

		additions_intent

		shell_intent

		"${HOME}"/.local/bin/termux-update
		
		frobulator.cpt "Complete" "[ Update // All ]"
		echo
	fi

	if [[ "${update}" = [dD][eE][xX][tT][oO][pP] ]]
	then
		frobulator.inf "Updating" "[ ${update} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		dextop_intent
		
		frobulator.cpt "Complete" "[ Update // Dextop ]"
		echo
	fi

	if [[ "${update}" = [uU][tT][iI][lL][iI][tT][yY] ]]
	then

		frobulator.inf "Updating" "[ ${utility} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		utility_intent
		
		frobulator.cpt "Complete" "[ Update // Utility ]"
		echo
	fi
	
	if [[ "${update}" = [pP][rR][eE][fF][eE][rR][eE][nN][cC][eE][sS] ]]
	then

		frobulator.inf "Updating" "[ ${utility} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		preferences_intent

		frobulator.cpt "Complete" "[ Update // Preferences ]"
		echo
	fi

	if [[ "${update}" = [sS][hH][eE][lL][lL] ]]
	then

		frobulator.inf "Updating" "[ ${shell} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		shell_intent
		
		frobulator.cpt "Complete" "[ Update // Shell ]"
		echo
	fi

	if [[ "${update}" = [aA][dD][dD][iI][tT][iI][oO][nN][sS] ]]
	then
		frobulator.inf "Updating" "[ ${update} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		additions_intent

		frobulator.cpt "Complete" "[ Update // Additions ]"
		echo
	fi

	if [[ "${update}" = [tT][eE][rR][mM][uU][xX] ]]
	then
		frobulator.inf "Updating" "[ ${update} ]"
		echo

		frobulator.fwd "Updating..."
		echo

		"${HOME}"/.local/bin/termux-update
		
		frobulator.cpt "Complete" "[ Update // Termux ]"
		echo

	fi

	exit
fi

# setup ////////////////////////////////////////////////////////////////////////

if [ ! -f "${HOME}"/.dextop/dextop-setup-checkpoint ]
then
	# dextop ///////////////////////////////////////////////////////////////////

	# failsafe
	
	failsafe_intent
	
	# backup

	if [ ! -f "${HOME}"/.dextop/dextop-backup-checkpoint ]
	then
		backup_intent

		frobulator.file "${HOME}"/.dextop dextop-backup-checkpoint
	fi

	# preferences

	if [ ! -f "${HOME}"/.dextop/dextop-preferences-checkpoint ]
	then
		preferences_intent

		frobulator.file "${HOME}"/.dextop dextop-preferences-checkpoint
	fi

	#  utilities

	if [ ! -f "${HOME}"/.dextop/dextop-utilities-checkpoint ]
	then
		utility_intent

		frobulator.file "${HOME}"/.dextop dextop-utilities-checkpoint
	fi

	# directories

	if [ ! -f "${HOME}"/.dextop/dextop-directories-checkpoint ]
	then
		directories_intent

		frobulator.file "${HOME}"/.dextop dextop-directories-checkpoint
	fi

	# additions

	if [ ! -f "${HOME}"/.dextop/dextop-additions-checkpoint ]
	then
		additions_intent

		frobulator.file "${HOME}"/.dextop dextop-additions-checkpoint
	fi

	# backgrounds

	if [ ! -f "${HOME}"/.dextop/dextop-backgrounds-checkpoint ]
	then
		backgrounds_intent

		frobulator.file "${HOME}"/.dextop dextop-backgrounds-checkpoint
	fi

	# automatic login

	if [ ! -f "${HOME}"/.dextop/dextop-login-checkpoint ]
	then
		frobulator.write login "${HOME}"/.dextop dextop-login

		frobulator.file "${HOME}"/.dextop dextop-login-checkpoint
	fi

	# automatic logout

	if [ ! -f "${HOME}"/.dextop/dextop-logout-checkpoint ]
	then
		frobulator.file "${HOME}"/.dextop dextop-logout

		frobulator.file "${HOME}"/.dextop dextop-logout-checkpoint
	fi

	# automatic update

	if [ ! -f "${HOME}"/.dextop/dextop-update-checkpoint ]
	then
		frobulator.file "${HOME}"/.dextop dextop-update

		frobulator.file "${HOME}"/.dextop dextop-update-checkpoint
	fi

	# audio

	if [ ! -f "${HOME}"/.dextop/dextop-audio-checkpoint ]
	then
		frobulator.file "${HOME}"/.dextop dextop-audio

		frobulator.file "${HOME}"/.dextop dextop-audio-checkpoint
	fi

	# ticker

	if [ ! -f "${HOME}"/.dextop/dextop-ticker-checkpoint ]
	then
		frobulator.write 0 "${HOME}"/.dextop dextop-ticker

		frobulator.file "${HOME}"/.dextop dextop-ticker-checkpoint
	fi

	# termux ///////////////////////////////////////////////////////////////////

	# termux additions

	if [ ! -f "${HOME}"/.dextop/dextop-termux-additions-checkpoint ]
	then
		"${HOME}"/.local/bin/termux-additions

		frobulator.file "${HOME}"/.dextop dextop-termux-additions-checkpoint
	fi

	# termux storage

	if [ ! -f "${HOME}"/.dextop/dextop-termux-storage-checkpoint ]
	then
		"${HOME}"/.local/bin/termux-storage

		frobulator.file "${HOME}"/.dextop dextop-termux-storage-checkpoint
	fi

	# termux failsafe

	if [ ! -f "${HOME}"/.dextop/dextop-termux-failsafe-checkpoint ]
	then
		"${HOME}"/.local/bin/termux-failsafe

		frobulator.file "${HOME}"/.dextop dextop-termux-failsafe-checkpoint
	fi
	
	# termux packages

	if [ ! -f "${HOME}"/.dextop/dextop-termux-packages-checkpoint ]
	then
		"${HOME}"/.local/bin/termux-packages

		frobulator.file "${HOME}"/.dextop dextop-termux-packages-checkpoint
	fi

	# container ////////////////////////////////////////////////////////////////

	# container image

	if [ ! -f "${HOME}"/.dextop/dextop-container-image-checkpoint ]
	then
		"${HOME}"/.local/bin/container-image

		frobulator.file "${HOME}"/.dextop dextop-container-image-checkpoint
	fi

	# container initialization

	if [ ! -f "${HOME}"/.dextop/dextop-container-initialization-checkpoint ]
	then
		container_intent

		frobulator.file "${HOME}"/.dextop dextop-container-initialization-checkpoint
	fi

	# container expansion

	if [ ! -f "${HOME}"/.dextop/dextop-container-expansion-checkpoint ]
	then
		container_intent "${HOME}"/.local/bin/container-expansion

		frobulator.file "${HOME}"/.dextop dextop-container-expansion-checkpoint
	fi

	# container failsafe

	if [ ! -f "${HOME}"/.dextop/dextop-container-failsafe-checkpoint ]
	then
		"${HOME}"/.local/bin/container-failsafe

		frobulator.file "${HOME}"/.dextop dextop-container-failsafe-checkpoint
	fi

	# container packages

	if [ ! -f "${HOME}"/.dextop/dextop-container-packages-checkpoint ]
	then
		container_intent "${HOME}"/.local/bin/container-packages

		frobulator.file "${HOME}"/.dextop dextop-container-packages-checkpoint
	fi

	# container user

	if [ ! -f "${HOME}"/.dextop/dextop-container-user-checkpoint ]
	then
		container_intent "${HOME}"/.local/bin/container-user

		frobulator.file "${HOME}"/.dextop dextop-container-user-checkpoint
	fi

	# dextop ///////////////////////////////////////////////////////////////////

	# shell

	if [ ! -f "${HOME}"/.dextop/dextop-shell-checkpoint ]
	then
		shell_intent

		frobulator.file "${HOME}"/.dextop dextop-shell-checkpoint
	fi

	# bookmarks

	if [ ! -f "${HOME}"/.dextop/dextop-bookmarks-checkpoint ]
	then
		bookmarks_intent

		frobulator.file "${HOME}"/.dextop dextop-bookmarks-checkpoint
	fi

	# icons

	if [ ! -f "${HOME}"/.dextop/dextop-icons-checkpoint ]
	then
		icons_intent

		frobulator.file "${HOME}"/.dextop dextop-icons-checkpoint
	fi

	# themes

	if [ ! -f "${HOME}"/.dextop/dextop-themes-checkpoint ]
	then
		themes_intent

		frobulator.file "${HOME}"/.dextop dextop-themes-checkpoint
	fi

	# setup move

	if [ ! -f "${HOME}"/.dextop/dextop-move-checkpoint ]
	then
		mv "${HOME}"/dextop "${HOME}"/.local/bin/dextop

		frobulator.file "${HOME}"/.dextop dextop-move-checkpoint
	fi

	# setup checkpoint

	frobulator.file "${HOME}"/.dextop dextop-setup-checkpoint
fi

# result ///////////////////////////////////////////////////////////////////////

if [ -z "${option}" ]
then
	frobulator.result "${HOME}"/.dextop dextop-setup-checkpoint "dextop setup"
	echo

	frobulator.timeout 5
fi

# clear ////////////////////////////////////////////////////////////////////////

frobulator.clear

# session //////////////////////////////////////////////////////////////////////

if [ "${option}" = "update" ]
then
	:
else
	session_intent
fi
