#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="07-03-2023"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-a|--activity)
			option="activity"
			activity="${2}"

			shift
		;;

		-n|--handle)
			option="handle"
			handle="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -a [Activity]| -n [Handle] | [OPTION]"
			echo
			echo -e "Options"
			echo
			echo -e "-a, --activity        Run native Android activities via Dextop environement defaults."
			echo
			echo -e "                     [ google-chrome ]"
			echo -e "                     [ google-mail ]"
			echo -e "                     [ terminal ]"
			echo
			echo -e "-n, --handle          Run desktop environment handles through native Android applications."
			echo
			echo -e "                     [ email ]   - mailto:"
			echo -e "                     [ link ]    - https:"
			echo -e "                     [ message ] - sms:"
			echo
			echo -e "-h, --help            Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} -a [Activity]| -n [Handle] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# activities

google_chrome="com.android.chrome/com.google.android.apps.chrome.Main"
google_mail="com.google.android.gm/.GmailActivity"
terminal="com.termux/com.termux.app.TermuxActivity"

# handles

link="https:"
message="sms:"
email="mailto:"

# functions ////////////////////////////////////////////////////////////////////

activity_intent () {
	am start							\
		-n "${activity}" > /dev/null 2>&1
	}

handle_intent () {
	am start							\
		-a android.intent.action.VIEW	\
		-d "${handle}" > /dev/null 2>&1
}

if [ "${option}" = "activity" ]
then
	activity_intent
fi

if [ "${option}" = "handle" ]
then
	activity_handle
fi
