#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="12-07-2024"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-a|--activity)
			option="activity"
			activity_option="${2}"

			shift
		;;

		-c|--action)
			option="action"
			action_option="${2}"

			shift
		;;

		-n|--handle)
			option="handle"
			handle_option="${2}"

			shift
		;;

		-h|--help)
			echo
			echo -e "Usage: ${script} -a [Activity] | -c [Action] | -n [Handle] | [OPTION]"
			echo
			echo -e "Options"
			echo
			echo -e "-a, --activity        Run desktop environment activities through native Android application activities."
			echo
			echo -e "                      [ google-chrome ] | [ chrome ]"
			echo -e "                      [ google-mail ]   | [ gmail ]"
			echo -e "                      [ terminal ]"
			echo
			echo -e "-c, --action          Run desktop environment activities through native Android application actions."
			echo
			echo -e "                      [ email ]   | [ mail ]"
			echo -e "                      [ browser ] | [ link ] | [ web ]"
			echo -e "                      [ message ] | [ text ] | [ sms ]"
			echo
			echo -e "-n, --handle          Handle desktop environment mimetypes through native Android applications."
			echo
			echo -e "                      [ email ]   | [ mail ]"
			echo -e "                      [ browser ] | [ link ] | [ web ]"
			echo -e "                      [ message ] | [ text ] | [ sms ]"
			echo
			echo -e "-h, --help            Show help and usage information."
			echo
			echo -e "'${script}' [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} -a [Activity] | -c [Action] | -n [Handle] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# activities

# service actions //////////////////////////////////////////////////////////////

# android.app.action.DEVICE_ADMIN_SERVICE
# android.intent.action.RESOLVE_INSTANT_APP_PACKAGE
# android.intent.action.RESPOND_VIA_MESSAGE
# android.intent.action.TTS_SERVICE
# android.media.browse.MediaBrowserService
# android.net.action.RECOMMEND_NETWORKS
# android.nfc.cardemulation.action.HOST_APDU_SERVICE
# android.nfc.cardemulation.action.HOST_NFCF_SERVICE
# android.nfc.cardemulation.action.OFF_HOST_APDU_SERVICE
# android.service.autofill.AutofillService
# android.service.carrier.CarrierMessagingService
# android.service.chooser.ChooserTargetService
# android.service.dreams.DreamService
# android.service.notification.ConditionProviderService
# android.service.notification.NotificationAssistantService
# android.service.notification.NotificationListenerService
# android.service.resolver.ResolverRankerService
# android.service.trust.TrustAgentService
# android.service.voice.VoiceInteractionService
# android.service.vr.VrListenerService
# android.service.wallpaper.WallpaperService
# android.speech.RecognitionService
# android.telecom.CallScreeningService
# android.telecom.ConnectionService
# android.telecom.InCallService
# android.telephony.VisualVoicemailService
# android.telephony.action.EmbmsDownload
# android.telephony.action.EmbmsStreaming
# android.view.InputMethod

# activity actions /////////////////////////////////////////////////////////////

# android.app.action.ADD_DEVICE_ADMIN
# android.app.action.MANAGED_PROFILE_PROVISIONED
# android.app.action.PROVISIONING_SUCCESSFUL
# android.app.action.PROVISION_FINALIZATION
# android.app.action.PROVISION_MANAGED_DEVICE
# android.app.action.PROVISION_MANAGED_DEVICE_FROM_TRUSTED_SOURCE
# android.app.action.PROVISION_MANAGED_PROFILE
# android.app.action.SET_NEW_PARENT_PROFILE_PASSWORD
# android.app.action.SET_NEW_PASSWORD
# android.app.action.START_ENCRYPTION
# android.app.action.STATE_USER_SETUP_COMPLETE
# android.appwidget.action.APPWIDGET_BIND
# android.appwidget.action.APPWIDGET_CONFIGURE
# android.appwidget.action.APPWIDGET_PICK
# android.bluetooth.adapter.action.REQUEST_BLE_SCAN_ALWAYS_AVAILABLE
# android.bluetooth.adapter.action.REQUEST_DISCOVERABLE
# android.bluetooth.adapter.action.REQUEST_ENABLE
# android.content.pm.action.CONFIRM_PIN_APPWIDGET
# android.content.pm.action.CONFIRM_PIN_SHORTCUT
# android.content.pm.action.SESSION_DETAILS
# android.intent.action.ALL_APPS
# android.intent.action.ANSWER
# android.intent.action.APPLICATION_PREFERENCES
# android.intent.action.APP_ERROR
# android.intent.action.ASSIST
# android.intent.action.ATTACH_DATA
# android.intent.action.BUG_REPORT
# android.intent.action.CALL
# android.intent.action.CALL_BUTTON
# android.intent.action.CALL_EMERGENCY
# android.intent.action.CALL_PRIVILEGED
# android.intent.action.CARRIER_SETUP
# android.intent.action.CHOOSER
# android.intent.action.CREATE_DOCUMENT
# android.intent.action.CREATE_LIVE_FOLDER
# android.intent.action.CREATE_SHORTCUT
# android.intent.action.DELETE
# android.intent.action.DIAL
# android.intent.action.DISMISS_ALARM
# android.intent.action.DISMISS_TIMER
# android.intent.action.EDIT
# android.intent.action.EVENT_REMINDER
# android.intent.action.FACTORY_TEST
# android.intent.action.GET_CONTENT
# android.intent.action.INSERT
# android.intent.action.INSERT_OR_EDIT
# android.intent.action.INSTALL_FAILURE
# android.intent.action.INSTALL_INSTANT_APP_PACKAGE
# android.intent.action.INSTALL_PACKAGE
# android.intent.action.INSTANT_APP_RESOLVER_SETTINGS
# android.intent.action.MAIN
# android.intent.action.MANAGE_APP_PERMISSIONS
# android.intent.action.MANAGE_NETWORK_USAGE
# android.intent.action.MANAGE_PERMISSIONS
# android.intent.action.MANAGE_PERMISSION_APPS
# android.intent.action.MEDIA_SEARCH
# android.intent.action.MUSIC_PLAYER
# android.intent.action.OPEN_DOCUMENT
# android.intent.action.OPEN_DOCUMENT_TREE
# android.intent.action.PASTE
# android.intent.action.PICK
# android.intent.action.PICK_ACTIVITY
# android.intent.action.POWER_USAGE_SUMMARY
# android.intent.action.PROCESS_TEXT
# android.intent.action.QUICK_VIEW
# android.intent.action.REVIEW_PERMISSIONS
# android.intent.action.RINGTONE_PICKER
# android.intent.action.RUN
# android.intent.action.SEARCH
# android.intent.action.SEARCH_LONG_PRESS
# android.intent.action.SEND
# android.intent.action.SENDTO
# android.intent.action.SEND_MULTIPLE
# android.intent.action.SET_ALARM
# android.intent.action.SET_TIMER
# android.intent.action.SET_WALLPAPER
# android.intent.action.SHOW_ALARMS
# android.intent.action.SHOW_APP_INFO
# android.intent.action.SHOW_SUSPENDED_APP_DETAILS
# android.intent.action.SHOW_TIMERS
# android.intent.action.SNOOZE_ALARM
# android.intent.action.SYNC
# android.intent.action.SYSTEM_TUTORIAL
# android.intent.action.UNINSTALL_PACKAGE
# android.intent.action.UPGRADE_SETUP
# android.intent.action.VIEW
# android.intent.action.VIEW_DOWNLOADS
# android.intent.action.VOICE_ASSIST
# android.intent.action.VOICE_COMMAND
# android.intent.action.WEB_SEARCH
# android.media.action.DISPLAY_AUDIO_EFFECT_CONTROL_PANEL
# android.media.action.IMAGE_CAPTURE
# android.media.action.IMAGE_CAPTURE_SECURE
# android.media.action.MEDIA_PLAY_FROM_SEARCH
# android.media.action.STILL_IMAGE_CAMERA
# android.media.action.STILL_IMAGE_CAMERA_SECURE
# android.media.action.TEXT_OPEN_FROM_SEARCH
# android.media.action.VIDEO_CAMERA
# android.media.action.VIDEO_CAPTURE
# android.media.action.VIDEO_PLAY_FROM_SEARCH
# android.media.tv.action.REQUEST_CHANNEL_BROWSABLE
# android.net.conn.CAPTIVE_PORTAL
# android.net.scoring.CHANGE_ACTIVE
# android.net.scoring.CUSTOM_ENABLE
# android.net.wifi.PICK_WIFI_NETWORK
# android.net.wifi.action.REQUEST_SCAN_ALWAYS_AVAILABLE
# android.nfc.action.NDEF_DISCOVERED
# android.nfc.action.TAG_DISCOVERED
# android.nfc.action.TECH_DISCOVERED
# android.nfc.cardemulation.action.ACTION_CHANGE_DEFAULT
# android.os.storage.action.MANAGE_STORAGE
# android.provider.MediaStore.RECORD_SOUND
# android.provider.Telephony.ACTION_CHANGE_DEFAULT
# android.provider.action.QUICK_CONTACT
# android.provider.action.VOICE_SEND_MESSAGE_TO_CONTACTS
# android.provider.calendar.action.HANDLE_CUSTOM_EVENT
# android.search.action.SEARCH_SETTINGS
# android.service.wallpaper.CROP_AND_SET_WALLPAPER
# android.settings.ACCESSIBILITY_SETTINGS
# android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS
# android.settings.ACTION_PRINT_SETTINGS
# android.settings.ADD_ACCOUNT_SETTINGS
# android.settings.AIRPLANE_MODE_SETTINGS
# android.settings.APN_SETTINGS
# android.settings.APPLICATION_DETAILS_SETTINGS
# android.settings.APPLICATION_DEVELOPMENT_SETTINGS
# android.settings.APPLICATION_SETTINGS
# android.settings.APP_NOTIFICATION_SETTINGS
# android.settings.BATTERY_SAVER_SETTINGS
# android.settings.BLUETOOTH_SETTINGS
# android.settings.CAPTIONING_SETTINGS
# android.settings.CAST_SETTINGS
# android.settings.CHANNEL_NOTIFICATION_SETTINGS
# android.settings.DATA_ROAMING_SETTINGS
# android.settings.DATA_USAGE_SETTINGS
# android.settings.DATE_SETTINGS
# android.settings.DEVICE_INFO_SETTINGS
# android.settings.DISPLAY_SETTINGS
# android.settings.DREAM_SETTINGS
# android.settings.ENTERPRISE_PRIVACY_SETTINGS
# android.settings.FINGERPRINT_ENROLL
# android.settings.HARD_KEYBOARD_SETTINGS
# android.settings.HOME_SETTINGS
# android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS
# android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS
# android.settings.INPUT_METHOD_SETTINGS
# android.settings.INPUT_METHOD_SUBTYPE_SETTINGS
# android.settings.INTERNAL_STORAGE_SETTINGS
# android.settings.LOCALE_SETTINGS
# android.settings.LOCATION_SOURCE_SETTINGS
# android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS
# android.settings.MANAGE_APPLICATIONS_SETTINGS
# android.settings.MANAGE_DEFAULT_APPS_SETTINGS
# android.settings.MANAGE_UNKNOWN_APP_SOURCES
# android.settings.MEMORY_CARD_SETTINGS
# android.settings.NETWORK_OPERATOR_SETTINGS
# android.settings.NFCSHARING_SETTINGS
# android.settings.NFC_PAYMENT_SETTINGS
# android.settings.NFC_SETTINGS
# android.settings.NIGHT_DISPLAY_SETTINGS
# android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS
# android.settings.PRIVACY_SETTINGS
# android.settings.QUICK_LAUNCH_SETTINGS
# android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
# android.settings.REQUEST_SET_AUTOFILL_SERVICE
# android.settings.SECURITY_SETTINGS
# android.settings.SETTINGS
# android.settings.SHOW_REGULATORY_INFO
# android.settings.SOUND_SETTINGS
# android.settings.STORAGE_VOLUME_ACCESS_SETTINGS
# android.settings.SYNC_SETTINGS
# android.settings.USAGE_ACCESS_SETTINGS
# android.settings.USER_DICTIONARY_SETTINGS
# android.settings.VOICE_CONTROL_AIRPLANE_MODE
# android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE
# android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE
# android.settings.VOICE_INPUT_SETTINGS
# android.settings.VPN_SETTINGS
# android.settings.VR_LISTENER_SETTINGS
# android.settings.WEBVIEW_SETTINGS
# android.settings.WIFI_IP_SETTINGS
# android.settings.WIFI_SETTINGS
# android.settings.WIRELESS_SETTINGS
# android.settings.ZEN_MODE_PRIORITY_SETTINGS
# android.settings.action.MANAGE_OVERLAY_PERMISSION
# android.settings.action.MANAGE_WRITE_SETTINGS
# android.speech.tts.engine.CHECK_TTS_DATA
# android.speech.tts.engine.GET_SAMPLE_TEXT
# android.speech.tts.engine.INSTALL_TTS_DATA
# android.telephony.action.CONFIGURE_VOICEMAIL
# android.telephony.action.MANAGE_SUBSCRIPTION_PLANS
# android.telephony.euicc.action.MANAGE_EMBEDDED_SUBSCRIPTIONS
# android.telephony.euicc.action.PROVISION_EMBEDDED_SUBSCRIPTION
# android.contacts.action.FILTER_CONTACTS

# broadcast actions ////////////////////////////////////////////////////////////

# android.accounts.LOGIN_ACCOUNTS_CHANGED
# android.accounts.action.ACCOUNT_REMOVED
# android.app.action.ACTION_PASSWORD_CHANGED
# android.app.action.ACTION_PASSWORD_EXPIRING
# android.app.action.ACTION_PASSWORD_FAILED
# android.app.action.ACTION_PASSWORD_SUCCEEDED
# android.app.action.APPLICATION_DELEGATION_SCOPES_CHANGED
# android.app.action.APP_BLOCK_STATE_CHANGED
# android.app.action.DEVICE_ADMIN_DISABLED
# android.app.action.DEVICE_ADMIN_DISABLE_REQUESTED
# android.app.action.DEVICE_ADMIN_ENABLED
# android.app.action.DEVICE_OWNER_CHANGED
# android.app.action.INTERRUPTION_FILTER_CHANGED
# android.app.action.LOCK_TASK_ENTERING
# android.app.action.LOCK_TASK_EXITING
# android.app.action.NEXT_ALARM_CLOCK_CHANGED
# android.app.action.NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED
# android.app.action.NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED
# android.app.action.NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED
# android.app.action.NOTIFICATION_POLICY_CHANGED
# android.app.action.PROFILE_OWNER_CHANGED
# android.app.action.PROFILE_PROVISIONING_COMPLETE
# android.app.action.SYSTEM_UPDATE_POLICY_CHANGED
# android.appwidget.action.APPWIDGET_DELETED
# android.appwidget.action.APPWIDGET_DISABLED
# android.appwidget.action.APPWIDGET_ENABLED
# android.appwidget.action.APPWIDGET_HOST_RESTORED
# android.appwidget.action.APPWIDGET_RESTORED
# android.appwidget.action.APPWIDGET_UPDATE
# android.appwidget.action.APPWIDGET_UPDATE_OPTIONS
# android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED
# android.bluetooth.adapter.action.CONNECTION_STATE_CHANGED
# android.bluetooth.adapter.action.DISCOVERY_FINISHED
# android.bluetooth.adapter.action.DISCOVERY_STARTED
# android.bluetooth.adapter.action.LOCAL_NAME_CHANGED
# android.bluetooth.adapter.action.SCAN_MODE_CHANGED
# android.bluetooth.adapter.action.STATE_CHANGED
# android.bluetooth.device.action.ACL_CONNECTED
# android.bluetooth.device.action.ACL_DISCONNECTED
# android.bluetooth.device.action.ACL_DISCONNECT_REQUESTED
# android.bluetooth.device.action.BOND_STATE_CHANGED
# android.bluetooth.device.action.CLASS_CHANGED
# android.bluetooth.device.action.FOUND
# android.bluetooth.device.action.NAME_CHANGED
# android.bluetooth.device.action.PAIRING_REQUEST
# android.bluetooth.device.action.UUID
# android.bluetooth.devicepicker.action.DEVICE_SELECTED
# android.bluetooth.devicepicker.action.LAUNCH
# android.bluetooth.headset.action.VENDOR_SPECIFIC_HEADSET_EVENT
# android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED
# android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.hearingaid.profile.action.ACTIVE_DEVICE_CHANGED
# android.bluetooth.hearingaid.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.hearingaid.profile.action.PLAYING_STATE_CHANGED
# android.bluetooth.hiddevice.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.input.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.pan.profile.action.CONNECTION_STATE_CHANGED
# android.bluetooth.pbap.profile.action.CONNECTION_STATE_CHANGED
# android.content.pm.action.SESSION_COMMITTED
# android.hardware.action.NEW_PICTURE
# android.hardware.action.NEW_VIDEO
# android.hardware.hdmi.action.OSD_MESSAGE
# android.hardware.input.action.QUERY_KEYBOARD_LAYOUTS
# android.hardware.usb.action.USB_ACCESSORY_ATTACHED
# android.hardware.usb.action.USB_ACCESSORY_DETACHED
# android.hardware.usb.action.USB_DEVICE_ATTACHED
# android.hardware.usb.action.USB_DEVICE_DETACHED
# android.intent.action.ACTION_POWER_CONNECTED
# android.intent.action.ACTION_POWER_DISCONNECTED
# android.intent.action.ACTION_SHUTDOWN
# android.intent.action.AIRPLANE_MODE
# android.intent.action.APPLICATION_RESTRICTIONS_CHANGED
# android.intent.action.BATTERY_CHANGED
# android.intent.action.BATTERY_LOW
# android.intent.action.BATTERY_OKAY
# android.intent.action.BOOT_COMPLETED
# android.intent.action.CAMERA_BUTTON
# android.intent.action.CLOSE_SYSTEM_DIALOGS
# android.intent.action.CONFIGURATION_CHANGED
# android.intent.action.CONTENT_CHANGED
# android.intent.action.DATA_SMS_RECEIVED
# android.intent.action.DATE_CHANGED
# android.intent.action.DEVICE_STORAGE_LOW
# android.intent.action.DEVICE_STORAGE_OK
# android.intent.action.DOCK_EVENT
# android.intent.action.DOWNLOAD_COMPLETE
# android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED
# android.intent.action.DREAMING_STARTED
# android.intent.action.DREAMING_STOPPED
# android.intent.action.DROPBOX_ENTRY_ADDED
# android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE
# android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE
# android.intent.action.FACTORY_RESET
# android.intent.action.FETCH_VOICEMAIL
# android.intent.action.GTALK_CONNECTED
# android.intent.action.GTALK_DISCONNECTED
# android.intent.action.HEADSET_PLUG
# android.intent.action.HEADSET_PLUG
# android.intent.action.INPUT_METHOD_CHANGED
# android.intent.action.INTENT_FILTER_NEEDS_VERIFICATION
# android.intent.action.LOCALE_CHANGED
# android.intent.action.LOCKED_BOOT_COMPLETED
# android.intent.action.MANAGE_PACKAGE_STORAGE
# android.intent.action.MASTER_CLEAR_NOTIFICATION
# android.intent.action.MEDIA_BAD_REMOVAL
# android.intent.action.MEDIA_BUTTON
# android.intent.action.MEDIA_CHECKING
# android.intent.action.MEDIA_EJECT
# android.intent.action.MEDIA_MOUNTED
# android.intent.action.MEDIA_NOFS
# android.intent.action.MEDIA_REMOVED
# android.intent.action.MEDIA_SCANNER_FINISHED
# android.intent.action.MEDIA_SCANNER_SCAN_FILE
# android.intent.action.MEDIA_SCANNER_STARTED
# android.intent.action.MEDIA_SHARED
# android.intent.action.MEDIA_UNMOUNTABLE
# android.intent.action.MEDIA_UNMOUNTED
# android.intent.action.MY_PACKAGE_REPLACED
# android.intent.action.MY_PACKAGE_SUSPENDED
# android.intent.action.MY_PACKAGE_UNSUSPENDED
# android.intent.action.NEW_OUTGOING_CALL
# android.intent.action.NEW_VOICEMAIL
# android.intent.action.PACKAGES_SUSPENDED
# android.intent.action.PACKAGES_UNSUSPENDED
# android.intent.action.PACKAGE_ADDED
# android.intent.action.PACKAGE_CHANGED
# android.intent.action.PACKAGE_DATA_CLEARED
# android.intent.action.PACKAGE_FIRST_LAUNCH
# android.intent.action.PACKAGE_FULLY_REMOVED
# android.intent.action.PACKAGE_INSTALL
# android.intent.action.PACKAGE_NEEDS_VERIFICATION
# android.intent.action.PACKAGE_REMOVED
# android.intent.action.PACKAGE_REPLACED
# android.intent.action.PACKAGE_RESTARTED
# android.intent.action.PACKAGE_VERIFIED
# android.intent.action.PHONE_STATE
# android.intent.action.PROVIDER_CHANGED
# android.intent.action.PROXY_CHANGE
# android.intent.action.QUERY_PACKAGE_RESTART
# android.intent.action.REBOOT
# android.intent.action.SCREEN_OFF
# android.intent.action.SCREEN_ON
# android.intent.action.SIM_STATE_CHANGED
# android.intent.action.SPLIT_CONFIGURATION_CHANGED
# android.intent.action.TIMEZONE_CHANGED
# android.intent.action.TIME_SET
# android.intent.action.TIME_TICK
# android.intent.action.UID_REMOVED
# android.intent.action.UMS_CONNECTED
# android.intent.action.UMS_DISCONNECTED
# android.intent.action.USER_PRESENT
# android.intent.action.USER_UNLOCKED
# android.intent.action.WALLPAPER_CHANGED
# android.media.ACTION_SCO_AUDIO_STATE_UPDATED
# android.media.AUDIO_BECOMING_NOISY
# android.media.RINGER_MODE_CHANGED
# android.media.SCO_AUDIO_STATE_CHANGED
# android.media.VIBRATE_SETTING_CHANGED
# android.media.action.CLOSE_AUDIO_EFFECT_CONTROL_SESSION
# android.media.action.HDMI_AUDIO_PLUG
# android.media.action.MICROPHONE_MUTE_CHANGED
# android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION
# android.media.tv.action.CHANNEL_BROWSABLE_REQUESTED
# android.media.tv.action.INITIALIZE_PROGRAMS
# android.media.tv.action.PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT
# android.media.tv.action.PREVIEW_PROGRAM_BROWSABLE_DISABLED
# android.media.tv.action.WATCH_NEXT_PROGRAM_BROWSABLE_DISABLED
# android.net.conn.BACKGROUND_DATA_SETTING_CHANGED
# android.net.conn.CONNECTIVITY_CHANGE
# android.net.conn.RESTRICT_BACKGROUND_CHANGED
# android.net.nsd.STATE_CHANGED
# android.net.scoring.SCORER_CHANGED
# android.net.scoring.SCORE_NETWORKS
# android.net.wifi.NETWORK_IDS_CHANGED
# android.net.wifi.RSSI_CHANGED
# android.net.wifi.SCAN_RESULTS
# android.net.wifi.STATE_CHANGE
# android.net.wifi.WIFI_STATE_CHANGED
# android.net.wifi.aware.action.WIFI_AWARE_STATE_CHANGED
# android.net.wifi.p2p.CONNECTION_STATE_CHANGE
# android.net.wifi.p2p.DISCOVERY_STATE_CHANGE
# android.net.wifi.p2p.PEERS_CHANGED
# android.net.wifi.p2p.STATE_CHANGED
# android.net.wifi.p2p.THIS_DEVICE_CHANGED
# android.net.wifi.rtt.action.WIFI_RTT_STATE_CHANGED
# android.net.wifi.supplicant.CONNECTION_CHANGE
# android.net.wifi.supplicant.STATE_CHANGE
# android.nfc.action.ADAPTER_STATE_CHANGED
# android.nfc.action.TRANSACTION_DETECTED
# android.os.action.DEVICE_IDLE_MODE_CHANGED
# android.os.action.POWER_SAVE_MODE_CHANGED
# android.provider.Telephony.SECRET_CODE
# android.provider.Telephony.SIM_FULL
# android.provider.Telephony.SMS_CB_RECEIVED
# android.provider.Telephony.SMS_DELIVER
# android.provider.Telephony.SMS_RECEIVED
# android.provider.Telephony.SMS_REJECTED
# android.provider.Telephony.SMS_SERVICE_CATEGORY_PROGRAM_DATA_RECEIVED
# android.provider.Telephony.WAP_PUSH_DELIVER
# android.provider.Telephony.WAP_PUSH_RECEIVED
# android.provider.action.DEFAULT_SMS_PACKAGE_CHANGED
# android.provider.action.EXTERNAL_PROVIDER_CHANGE
# android.provider.action.SYNC_VOICEMAIL
# android.security.STORAGE_CHANGED
# android.security.action.KEYCHAIN_CHANGED
# android.security.action.KEY_ACCESS_CHANGED
# android.security.action.TRUST_STORE_CHANGED
# android.speech.tts.TTS_QUEUE_PROCESSING_COMPLETED
# android.speech.tts.engine.TTS_DATA_INSTALLED
# android.telephony.action.DEFAULT_SMS_SUBSCRIPTION_CHANGED
# android.telephony.action.DEFAULT_SUBSCRIPTION_CHANGED
# android.telephony.action.REFRESH_SUBSCRIPTION_PLANS
# android.telephony.action.SIM_APPLICATION_STATE_CHANGED
# android.telephony.action.SIM_CARD_STATE_CHANGED
# android.telephony.action.SIM_SLOT_STATUS_CHANGED
# android.telephony.action.SUBSCRIPTION_CARRIER_IDENTITY_CHANGED
# android.telephony.euicc.action.NOTIFY_CARRIER_SETUP_INCOMPLETE
# android.telephony.euicc.action.OTA_STATUS_CHANGED

# discreet applications

google_chrome="com.android.chrome/com.google.android.apps.chrome.Main"
google_chrome_beta="com.chrome.beta/com.google.android.apps.chrome.Main"
google_mail="com.google.android.gm/.GmailActivity"
terminal="com.termux/com.termux.app.TermuxActivity"

# android actions

camera="android.media.action.IMAGE_CAPTURE"

# mimetype handles

email="mailto:"
link="https:"
message="sms:"

# functions ////////////////////////////////////////////////////////////////////

activity_intent () {

	activity="${1}"

	am start							\
		--user 0						\
		-n "${activity}"				> "${sink}" 2>&1
	}

action_intent () {

	action="${1}"

	am start							\
		--user 0						\
		-a "${action}"					> "${sink}" 2>&1
}

handle_intent () {

	handle="${1}"

	am start							\
		--user 0						\
		-a android.intent.action.VIEW	\
		-d "${handle}"					> "${sink}" 2>&1
}

# options //////////////////////////////////////////////////////////////////////

if [[ "${option}" = [aA][cC][tT][iI][vV][iI][tT][yY] ]]
then
	if [[ "${activity_option}" = "google-chrome" ]] || \
	   [[ "${activity_option}" = "chrome"        ]]
	then
		activity="${google_chrome}"

	elif [[ "${activity_option}" = "google-mail" ]] || \
		[[ "${activity_option}" = "gmail"        ]]
	then
		activity="${google_mail}"

	elif [[ "${activity_option}" = "terminal"    ]]
	then
		activity="${terminal}"

	else
		frobulator.err "Unrecognized activity option" "[ ${activity_option} ]"
		echo

		exit 1
	fi

	activity_intent "${activity}"

elif [[ "${option}" = [hH][aA][nN][dD][lL][eE] ]]
then
	if [[ "${handle_option}" = "email"     ]] || \
	   [[ "${handle_option}" = "mail"      ]]
	then
		handle="${email}"

	elif [[ "${handle_option}" = "browser" ]] || \
		[[ "${handle_option}" = "link"     ]] || \
		[[ "${handle_option}" = "web"      ]]
	then
		handle="${link}"

	elif [[ "${handle_option}" = "message" ]] || \
	     [[ "${handle_option}" = "text"    ]] || \
	     [[ "${handle_option}" = "sms"     ]]
	then
		handle="${message}"

	else
		frobulator.err "Unrecognized handle option" "[ ${handle_option} ]"
		echo

		exit 1
	fi

elif [[ "${option}" = [aA][cC][tT][iI][oO][nN] ]]
then
	if [[ "${actio_option}" = "camera"     ]] || \
	   [[ "${handle_option}" = "photo"     ]]
	   [[ "${handle_option}" = "selfie"    ]]
	then
		handle="${camera}"
	else
		frobulator.err "Unrecognized handle option" "[ ${handle_option} ]"
		echo

		exit 1
	fi

	handle_intent "${handle}"
fi
