#!/bin/bash

# dependencies #

curl -sL get.cnsl.app/console > "${PREFIX}"/bin/console && source "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-t|--termux)
			dextop_option="termux"
		;;
		
		-p|--proot)
			dextop_option="proot"
		;;
				
		-h|--help)
			echo
			echo -e "USAGE:"
			echo
			echo -e "-t, --termux \t\t Setup Termux environment - VNC setup not included."
			echo -e "-p, --proot \t\t Setup Proot environment - VNC setup included."
			echo
			echo -e "-h, --help \t\t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# clear

console.clear

# prompt #

console.script "Initializing setup [ ${script%-*} ]"
echo

# variables #

# set defaults

[ -z "${dextop_option}" ] && dextop_option="proot"

# export variables

echo '# variables #'															>> "${PREFIX}"/bin/dextop

echo "export version=${version}"												>> "${PREFIX}"/bin/dextop

echo '# dextop #'																>> "${PREFIX}"/bin/dextop

echo 'export MAIN_DIRECTORY="${PREFIX%/*}"'										>> "${PREFIX}"/bin/dextop
echo 'export BINARIES_DIRECTORY="${PREFIX}"/bin'								>> "${PREFIX}"/bin/dextop
echo 'export LIBRARIES_DIRECTORY="${PREFIX}"/lib'								>> "${PREFIX}"/bin/dextop
echo 'export SOURCES_DIRECTORY="${PREFIX}"/etc/apt'								>> "${PREFIX}"/bin/dextop
echo 'export BACKUP_DIRECTORY="${MAIN_DIRECTORY}"/bkp'							>> "${PREFIX}"/bin/dextop
echo 'export IMAGE_DIRECTORY="${MAIN_DIRECTORY}"/img'							>> "${PREFIX}"/bin/dextop
echo 'export ISO_DIRECTORY="${MAIN_DIRECTORY}"/iso'								>> "${PREFIX}"/bin/dextop
echo 'export MOUNT_DIRECTORY="${MAIN_DIRECTORY}"/mnt'							>> "${PREFIX}"/bin/dextop
echo 'export PROC_DIRECTORY="${MAIN_DIRECTORY}"/proc'							>> "${PREFIX}"/bin/dextop

# source variables

[ -f "${PREFIX}"/bin/dextop ] && source "${PREFIX}"/bin/dextop

# values #

utilities_list=(
	termux-utilities
	termux-setup
	proot-utilities
	proot-setup
	vnc-utilities
	vnc-setup
)

# download #

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${utilities_list[@]}

# values #

termux_list=(
	termux-setup
)

proot_list=(
	proot-setup
)

vnc_list=(
	vnc-setup
)

# initialize setup list

setup_list=()

# options #

# termux

if [[ "${dextop_option}" = "termux" ]]
then
	# populate setup list
	
	setup_list+=(
		${termux_list[@]}
		)
fi

# proot

if [[ "${dextop_option}" = "proot" ]]
then
	# populate setup list

	setup_list+=(
		${termux_list[@]}
		${proot_list[@]}
		${vnc_list[@]}
	)
fi

# setup #

for setup in ${setup_list[@]}
do
	"${BINARIES_DIRECTORY}"/"${setup}"
	
	console.clear
done

# close terminal after setup

console.scs "Dextop setup complete."
echo

console.countdown "Closing terminal to load changes in" 5

kill -9 $(pgrep -f "${SHELL}")