#!/bin/bash

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# globals #

export INITIAL_DIRECTORY="${PWD}"
export SETUP_DIRECTORY="${PREFIX%/*}"
export BINARIES_DIRECTORY="${PREFIX}"/bin
export LIBRARIES_DIRECTORY="${PREFIX}"/lib
export ROOT_DIRECTORY="${SETUP_DIRECTORY}"/img
export BIND_DIRECTORY="${SETUP_DIRECTORY}"/mnt
export FAKE_DIRECTORY="${SETUP_DIRECTORY}"/fake

# setup variables #
