#!/bin/bash

# globals #

export INITIAL_DIRECTORY="${PWD}"
export SETUP_DIRECTORY="${PREFIX%/*}"
export BINARIES_DIRECTORY="${PREFIX}"/bin
export LIBRARIES_DIRECTORY="${PREFIX}"/lib
export PROOT_DIRECTORY="${SETUP_DIRECTORY}"/img
export BIND_DIRECTORY="${SETUP_DIRECTORY}"/mnt

# setup variables #
