#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/termux-globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# hostname

console.inf "Setting hostname."
echo

echo "${hostname}" > "${PROOT_DIRECTORY}"/etc/hostname

# hosts

console.inf "Setting host address."
echo

cat <<- FILE > "${PROOT_DIRECTORY}"/etc/hosts
127.0.0.1 localhost.localdomain
127.0.0.1 localhost
127.0.0.1 "${hostname}"
FILE

# nameserver

console.inf "Setting namserver address."
echo

cat <<- 'FILE' > "${PROOT_DIRECTORY}"/etc/resolv.conf
nameserver 8.8.8.8
FILE