#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="06-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# variables #

case "${DISTRIBUTION_NAME}" in
	ubuntu)
		iso_url="http://cdimage.ubuntu.com/ubuntu-base/releases/${DISTRIBUTION_VERSION}/release"
		iso_archive="ubuntu-base-${DISTRIBUTION_VERSION}-base-${iso_architecture}.tar.gz"
	;;
esac

image_directories () {
	# populate required directories and structure

	console.inf "Creating required deployment directories."
	echo

	directories_list=(
		"${BACKUP_DIRECTORY}"
		"${IMAGE_DIRECTORY}"
		"${ISO_DIRECTORY}"
		"${ROOT_DIRECTORY}"
		"${MOUNT_DIRECTORY}"
	)

	console.directory "${MAIN_DIRECTORY}" ${directories_list[@]}
}

image_archive () {
	# archive previous deployments to backup directory

	# set IFS

	IFS=$'\n'

	deployments_list=()

	for deployment in $(find "${IMAGE_DIRECTORY}" -maxdepth 2 -type d ! -wholename "${IMAGE_DIRECTORY}")
	do
		deployments_list+=("${deployment}")
	done

	console.inf "Number of deployments" ${#deployments_list[@]}
	echo

	select deployment_selection in ${deployments_list[@]}
	do
		ROOT_DIRECTORY="${deployment_selection}"

		console.inf "Archiving. [ ${deployment_selection} ]"
		echo

		break
	done

	console.inf "Archiving selected deployment."
	echo

	tar												\
		--create									\
		--verbose									\
		--gzip										\
		--preserve-permissions						\
			--file="${BACKUP_DIRECTORY}/${1}"		\
			--exclude="${ROOT_DIRECTORY}/${1}"		\
			--one-file-system "${ROOT_DIRECTORY}"	|| :
}

image_restore () {
	# restore backed up deployment to image directory

	# set IFS

	IFS=$'\n'

	archives_list=()

	for archive in $(find "${BACKUP_DIRECTORY}" -maxdepth 2 -type f -iname "*.tar.gz" ! -wholename "${BACKUP_DIRECTORY}")
	do
		archives_list+=("${archive}")
	done

	console.inf "Number of archives" ${#archives_list[@]}
	echo

	select archive_selection in ${archives_list[@]}
	do
		console.inf "Restoring. [ ${archive_selection} ]"
		echo

		break
	done

	IFS='-'

	archive_label="${archive_selection##*/}"

	read archive_name archive_release _ _ _ _ _ _ _ <<< $(echo "${archive_label}")

	console.inf "Extracting selected archive."
	echo

	tar												\
		--extract									\
			--file="${archive_selection}"			\
			--directory="/"
}

image_wipe () {
	# wipe image directory contents

	console.inf "Wiping previous deployments."
	echo

	rm -rf "${IMAGE_DIRECTORY}"/*
}

image_move () {
	# move same distribution/release directory contents

	console.inf "Moving deployments."

	for directory in $(find "${IMAGE_DIRECTORY}" -maxdepth 2 -type d ! -wholename "${IMAGE_DIRECTORY}")
	do
		directories_list+=("${directory}")
	done

	for deployment in ${directories_list[@]}
	do
		if [[ "${deployment}" == "${DISTRIBUTION_NAME}/${DISTRIBUTION_RELEASE}" ]]
		then
			mv "${deployment}" "${deployment}-${stamp}"
		fi
	done
}

image_unpack () {
	# shorthand

	# proot -l tar -xzf "${1}" -X "${2}" || :

	# exclude archive directories: dev | proc | sys | system
	# 'proot-launch' will bind and mount those device directories to proot

	ROOT_DIRECTORY="${ROOT_DIRECTORY}"

	console.inf "Extracting new deployment."
	echo

	cd "${ROOT_DIRECTORY}" || exit 1

	proot												\
		--link2symlink									\
			tar 										\
				--extract								\
					--file="${1}"						\
					--exclude='dev'						\
					--exclude='proc'					\
					--exclude='sys'						\
					--exclude='system' 2> /dev/null		|| :
}

# run setup

console.inf "Initializing deployment setup."
echo

console.fwd "Initializing..."
echo

if [[ ! -d "${IMAGE_DIRECTORY}" || -z "$(ls ${IMAGE_DIRECTORY})" ]]
then
	image_directories
else
	if [[ -z "$(ls ${IMAGE_DIRECTORY})" ]]
	then
		console.inf "Image directory clean:"
		echo

		console.wrn "Image directory does not contain any previous deployments"
		echo

		console.fwd "Proceeding..."
		echo
	else
		if [[ ! -z "$(ls ${IMAGE_DIRECTORY})" ]]
		then
			console.usr "Archive deployments?"
			echo

			read reply

			if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
			then
				image_archive "${DISTRIBUTION_NAME}-${DISTRIBUTION_RELEASE}-backup-${stamp}.tar.gz"

				unset reply
			else
				if [[ -z "$(ls ${BACKUP_DIRECTORY})" ]]
				then
					console.inf "Backup directory clean:"
					echo

					console.wrn "Backup directory does not contain any archives."
					echo

					console.fwd "Proceeding..."
					echo
				else
					if [[ ! -z "$(ls ${BACKUP_DIRECTORY})" ]]
					then
						console.usr "Restore deployments?"
						echo

						read reply

						if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
						then
							image_restore

							unset reply
						else
							if [[ ! -z "$(ls ${IMAGE_DIRECTORY})" ]] && [[ "${LOAD_DIRECTORY}" == "${DISTRIBUTION_NAME}/${DISTRIBUTION_RELEASE}" ]]
							then
								console.wrn "Image directory contains previous deployments."
								echo

								console.err "Deployment matches setup settings [ ${DISTRIBUTION_NAME}/${DISTRIBUTION_RELEASE} ]"
								echo

								console.usr "Archive matching deployment?"
								echo

								read reply

								if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
								then
									image_archive "${DISTRIBUTION_NAME}-${DISTRIBUTION_RELEASE}-backup-${stamp}.tar.gz"

									unset reply
								else
									console.err "Cannot deploy over existing image with same configuration."
									echo

									console.usr "Wipe image directory?"
									echo

									read reply

									if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
									then
										image_wipe

										unset reply
									else
										console.err "Cannot deploy over existing image with same configuration."
										echo

										console.usr "Rename deployment directory?"
										echo

										read reply

										if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
										then
											image_move
										else
											console.err "Unable to deploy system image with current set of options."
											echo

											console.fwd "Aborting..."
											echo

											exit 1
										fi
									fi
								fi
							fi
						fi
					fi
				fi
			fi
		fi
	fi
fi


console.download "${iso_url}" "${ISO_DIRECTORY}" "${iso_archive}"

image_unpack "${ISO_DIRECTORY}/${iso_archive}"
