#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Creating bookmarks [ ${script%-*} ]"
echo

# variables #

# set defaults

# write bookmarks

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bookmarks
file:///media/Internal
FILE

if [ -d /media/External ]
then
	cat <<- 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bookmarks
	file:///media/External
	FILE
fi

# create bookmarks directory

console.directory "${ROOT_DIRECTORY}"/home/"${user_name}" .config/gtk-3.0

ln -s -f "${ROOT_DIRECTORY}"/home/"${user_name}"/.bookmarks "${ROOT_DIRECTORY}"/home/"${user_name}"/.gtk-bookmarks
ln -s -f "${ROOT_DIRECTORY}"/home/"${user_name}"/.bookmarks "${ROOT_DIRECTORY}"/home/"${user_name}"/.config/gtk-3.0/bookmarks
