#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Transferring unregistered group IDs [ ${script%-*} ]"
echo

# variables #

# set defaults

# set IFS

IFS=' '

# read android system IDs

read uid gid groups <<< $(id)

uid=${uid/uid=}
gid=${gid/gid=}
groups=${groups/groups=}

# set IFS

IFS=','

# parse existing groups

read -r -a groups_list <<< "${groups}"

for line in "${groups_list[@]}"
do
	line=${line/(/ }
	line=${line/)}

	# set IFS

	IFS=' '

	# transfer unregistered IDs

	read group_number group_name <<< ${line}

	[ -f "${ROOT_DIRECTORY}"/etc/group ]   && echo "${group_name}:x:${group_number}:" >> "${ROOT_DIRECTORY}"/etc/group
	[ -f "${ROOT_DIRECTORY}"/etc/gshadow ] && echo "${group_name}:x:${group_number}:" >> "${ROOT_DIRECTORY}"/etc/gshadow

done

# reset IFS

IFS=''
