#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="09-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up packages [ ${script%-*} ]"
echo

# variables #

# set defaults

# update packages list

console.update

# upgrade installed packages

console.upgrade

# values #

administration_list=(
	sudo
)

display_list=(
	dbus-x11
	x11-apps
	x11-common
	x11-session-utils
	x11-touchscreen-calibrator
	x11-utils
	x11-xfs-utils
	x11-xkb-utils
	x11-xserver-utils
)

documentation_list=(
	man
	man-db
)

locales_list=(
	keyboard-configuration
	locales
	locales-all
)

security_list=(
	ca-certificates
	openssl
)

vnc_list=(
	tigervnc-common
	tigervnc-standalone-server
)

themes_list=(
	arc-theme
	tango-icon-theme
	qt5-style-platform-gtk2
	qt5-style-plugin-gtk2
)

kde_list=(
	plasma-desktop
	plasma-framework
	plasma-integration
	plasma-workspace
	plasma-workspace-wallpapers
	plasma-wallpapers-addons
	plasma-discover
	plasma-discover-backend-flatpak
	plasma-discover-backend-snap
	plasma-discover-common
	plasma-discover-flatpak-backend
	plasma-discover-snap-backend
	ark
	dolphin
	kate
	kdialog
	keditbookmarks
	kfind
	konsole
	konqueror
	kwin
	gwenview
	okular
	systemsettings
)

kde_fonts_list=(
	fonts-hack
	fonts-noto-cjk
	fonts-noto-hinted
	fonts-noto-mono
	fonts-noto-unhinted
)

kde_themes_ist=(
	breeze
)

kde_addons_list=(
	plasma-browser-integration
	plasma-calendar-addons
	plasma-dataengines-addons
	plasma-kdevelop
	plasma-marble
	plasma-nm
	plasma-runner-installer
	plasma-runner-telepathy-contact
	plasma-runners-addons
	plasma-vault
	elisa
	kcalc
	kcharselect
	kgamma5
	khelpcenter
	khotkeys
	kinfocenter
	kio
	kio-extras
	kio-extras-data
	kmenuedit
	konversation
	kscreen
	ksshaskpass
	ksysguard
	ktorrent
	kwalletmanager
	kwrite
	milou
)

xfce_list=(
	xfce4
	xfce4-appfinder
	xfce4-clipman
	xfce4-dict
	xfce4-notes
	xfce4-notifyd
	xfce4-panel
	xfce4-screensaver
	xfce4-screenshooter
	xfce4-session
	xfce4-settings
	xfce4-taskmanager
	xfce4-terminal
	thunar
	thunar-archive-plugin
	thunar-media-tags-plugin
	mousepad
	midori
	ristretto
)

xfce_fonts_list=(
)

xfce_themes_list=(
	blackbird-gtk-theme
	bluebird-gtk-theme
	greybird-gtk-theme
	elementary-xfce-icon-theme
)

xfce_addons_list=(
	xfce4-appmenu-plugin
	xfce4-battery-plugin
	xfce4-clipman-plugin
	xfce4-cpufreq-plugin
	xfce4-cpugraph-plugin
	xfce4-datetime-plugin
	xfce4-diskperf-plugin
	xfce4-equake-plugin
	xfce4-eyes-plugin
	xfce4-fsguard-plugin
	xfce4-genmon-plugin
	xfce4-indicator-plugin
	xfce4-mailwatch-plugin
	xfce4-mount-plugin
	xfce4-mpc-plugin
	xfce4-netload-plugin
	xfce4-notes-plugin
	xfce4-panel-profiles
	xfce4-places-plugin
	xfce4-sensors-plugin
	xfce4-smartbookmark-plugin
	xfce4-sntray-plugin
	xfce4-sntray-plugin-common
	xfce4-statusnotifier-plugin
	xfce4-systemload-plugin
	xfce4-time-out-plugin
	xfce4-timer-plugin
	xfce4-verve-plugin
	xfce4-wavelan-plugin
	xfce4-weather-plugin
	xfce4-whiskermenu-plugin
	xfce4-xkb-plugin
)

base_list=(
	${administration_list[@]}
	${display_list[@]}
	${documentation_list}
	${locales_list[@]}
	${security_list[@]}
	${vnc_list[@]}
)

# initialize desktop environment list

desktop_environment_list=()

# initialize install list

install_list=()

# options #

# desktops

# kde

if [[ "${desktop_option}" = "kde" ]]
then
	desktop_environment_list=(
		${kde_list[@]}
		${kde_fonts_list[@]}
		${kde_themes_list[@]}
	)
	
	if [[ "${install_option}" = "full" ]]
	then
		desktop_environment_list+=(
			${kde_addons_list[@]}
		)
	fi
fi

# xfce

if [[ "${desktop_option}" = "xfce" ]]
then
	desktop_environment_list=(
		${xfce_list[@]}
		${xfce_fonts_list[@]}
		${xfce_themes_list[@]}
	)
	
	if [[ "${install_option}" = "full" ]]
	then
		desktop_environment_list+=(
			${xfce_addons_list[@]}
		)
	fi
fi

# install

# full

if [[ "${install_option}" = "full" ]]
then
	install_list+=(
		${base_list[@]}
		${desktop_environment_list[@]}
		${themes_list[@]}
	)
fi

# lite

if [[ "${install_option}" = "lite" ]]
then
	install_list+=(
		${base_list[@]}
		${desktop_environment_list[@]}
	)
fi

# base

if [[ "${install_option}" = "base" ]]
then
	install_list+=(
		${base_list[@]}
	)
fi

# install #

console.install ${install_list[@]}