#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/termux-globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# initial prompt clear #

clear

# download #

# applications

applications_list=(
	leocad-configuration
	leocad-download
	leocad-launcher
	leocad-position
)

console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin ${applications_list[]}

console.clear


# console.get https://yt-dl.org/downloads/latest								youtube-dl				/usr/bin
