#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# silence login prompt

console.inf "Silencing login messages."
echo

cat <<- 'FILE' >> "${PROOT_DIRECTORY}"/home/"${user_name}"/.hushlogin

FILE

# write welcome message - replaces motd

cat <<- 'FILE' >> "${PROOT_DIRECTORY}"/home/"${user_name}"/.profile
# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

console.fwd "Welcome to Ubuntu Dextop!"
echo

if [ -f "${HOME}"/.vnc/selection ]
then
	console.inf "You've already logged in, your selection has been saved:"
	console.inf "Automatic vnc startup on shell login is enabled."
else
	console.inf "This is your first login:"
	console.inf "Run 'vnc-start' to start your session."
fi

echo

console.wait 1

FILE