#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="05-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# variables #

option="${1}"

# binaries #

core_utilities_list=(
	b2sum
	base32
	base64
	basename
	basenc
	cat
	chcon
	chgrp
	chmod
	chown
	chroot
	cksum
	comm
	cp
	csplit
	cut
	date
	dd
	dir
	dircolors
	dirname
	du
	echo
	env
	expand
	expr
	factor
	false
	fmt
	fold
	ginstall
	groups
	head
	id
	join
	kill
	link
	ln
	logname
	ls
	md5sum
	mkdir
	mkfifo
	mknod
	mktemp
	mv
	nice
	nl
	nohup
	nproc
	numfmt
	od
	paste
	pathchk
	pr
	printenv
	printf
	ptx
	pwd
	readlink
	realpath
	rm
	rmdir
	runcon
	seq
	sha1sum
	sha224sum
	sha256sum
	sha384sum
	sha512sum
	shred
	shuf
	sleep
	sort
	split
	stat
	stdbuf
	stty
	sum
	sync
	tac
	tail
	tee
	test
	timeout
	touch
	tr
	true
	truncate
	tsort
	tty
	uname
	unexpand
	uniq
	unlink
	vdir
	wc
	whoami
	yes
)

binaries_list=(
	top
)

console.fwd "Linking binaries..."
echo

for binary in ${core_utilities_list[@]}
do
	if [ -f "${BINARIES_DIRECTORY}"/"${binary}" ]
	then
		console.inf "Linking '${binary}'."
		echo

		ln -s -f "${BINARIES_DIRECTORY}"/"$binary" /usr/bin/"${binary}"
	fi
done
