#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# set defaults

# set path:
# in order of retreival

PATH=""

# proot container

[ -d "${ROOT_DIRECTORY}"/usr/local/sbin ]										&& PATH+="/usr/local/sbin:"
[ -d "${ROOT_DIRECTORY}"/usr/local/bin ]										&& PATH+="/usr/local/bin:"
[ -d "${ROOT_DIRECTORY}"/usr/sbin ]												&& PATH+="/usr/sbin:"
[ -d "${ROOT_DIRECTORY}"/usr/sbin ]												&& PATH+="/usr/bin:"
[ -d "${ROOT_DIRECTORY}"/sbin ]													&& PATH+="/sbin:"
[ -d "${ROOT_DIRECTORY}"/bin ]													&& PATH+="/bin:"

# termux shell

[ -d "${PREFIX}"/sbin ]															&& PATH+="${PREFIX}/sbin:"
[ -d "${PREFIX}"/bin ]															&& PATH+="${PREFIX}/bin:"

# android subsystem

[ -d /system/sbin ]																&& PATH+="/system/sbin:"
[ -d /system/bin ]																&& PATH+="/system/bin:"

# environment #

cat << "FILE" -> "${ROOT_DIRECTORY}"/etc/environment
PATH="${PATH}"

FILE

# export variables

echo "# ${script} #"															>> "${PREFIX}"/bin/dextop

echo "export iso_architecture=${img_architecture}"								>> "${PREFIX}"/bin/dextop