#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="05-03-2021"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# settings #

console.inf "Setting desktop preferences."
echo

xfconf-query --create -c keyboard-layout -p /Default/XkbDisable                                   -t bool   -s false
xfconf-query --create -c keyboard-layout -p /Default/XkbLayout                                    -t string -s ca
xfconf-query --create -c keyboard-layout -p /Default/XkbVariant                                   -t string -s fr-legacy
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace0/color-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace0/image-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace0/last-image  -t string -s ""
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace1/color-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace1/image-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace1/last-image  -t string -s ""
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace2/color-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace2/image-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace2/last-image  -t string -s ""
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace3/color-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace3/image-style -t int    -s 0
xfconf-query --create -c xfce4-desktop   -p /backdrop/screen0/monitorVNC-0/workspace3/last-image  -t string -s ""
xfconf-query --create -c xfce4-desktop   -p /desktop-icons/file-icons/show-filesystem             -t bool   -s false
xfconf-query --create -c xfce4-desktop   -p /desktop-icons/file-icons/show-home                   -t bool   -s false
xfconf-query --create -c xfce4-desktop   -p /desktop-icons/file-icons/show-removable              -t bool   -s false
xfconf-query --create -c xfce4-desktop   -p /desktop-icons/file-icons/show-trash                  -t bool   -s false
xfconf-query --create -c xsettings       -p /Gtk/CursorThemeName                                  -t string -s breeze_cursors
xfconf-query --create -c xsettings       -p /Gtk/CursorThemeSize                                  -t int    -s 16
xfconf-query --create -c xsettings       -p /Gtk/GtkFontName                                      -t string -s Sans 10
xfconf-query --create -c xsettings       -p /Gtk/MonospaceFontName                                -t string -s Monospace 10
xfconf-query --create -c xsettings       -p /Net/ThemeName                                        -t string -s Arc-Dark
xfconf-query --create -c xfwm4           -p /general/theme                                        -t string -s Arc-Dark
xfconf-query --create -c xfwm4           -p /general/title_font                                   -t string -s Sans 10
xfconf-query --create -c xfwm4           -p /general/snap_to_border                               -t bool   -s true
xfconf-query --create -c xfwm4           -p /general/snap_to_windows                              -t bool   -s true
xfconf-query --create -c xfwm4           -p /general/snap_width                                   -t int    -s 10
xfconf-query --create -c xfwm4           -p /general/use_compositing                              -t bool   -s false
