#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="09-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Initializing setup [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# initialize #

# create self-terminating script file:
# execute on first login to complete proot setup
# and terminate when checkpoint is reached

# write automatic setup transition [ termux >>> [ proot ] ]

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/root/.profile

# proot initialize #

if [ ! -f "${BINARIES_DIRECTORY}"/proot-initialize-complete ]
then
	# dependencies #
	
	. /data/data/com.termux/files/usr/bin/console
	. /data/data/com.termux/files/usr/bin/dextop
	
	# continue proot setup
	
	"${BINARIES_DIRECTORY}"/proot-setup

	# confirm uninterrupted setup
	
	echo "yes" > "${BINARIES_DIRECTORY}"/proot-initialize-complete
	
	# clear #
	
	console.clear
	
	# exit proot after successful setup:
	# continue with vnc setup on Termux shell
	
	console.fwd "Logging out..."
	echo
	
	exit
else
	:
fi
FILE