#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="09-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Writing login greeter [ ${script%-*} ]"

# variables #

# set defaults

# write welcome message: replaces motd

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

console.fwd "Welcome to Dextop [ Ubuntu ]"
echo

if [ -f "${HOME}"/.vnc/selection ]
then
	console.inf "You have already logged in - vnc selection has been saved:"
	console.inf "Automatic session launch on shell login is enabled."
	echo
else
	console.wrn "This is your first login:"
	console.wrn "Run 'vnc-start' to launch session [ ${SESSION_NAME} ]."
	echo
fi

echo
FILE
