#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.inf "Downloading utilities [ proot ]."
echo

# variables #

# set defaults

# source

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && source "${BINARIES_DIRECTORY}"/console

# values #

binaries_list=(
	proot-aliases
	proot-architecture
	proot-bookmarks
	proot-checkpoint
	proot-clean
	proot-configuration
	proot-download
	proot-environment
	proot-expand
	proot-proc
	proot-groups
	proot-image
	proot-information
	proot-initialize
	proot-launch
	proot-libraries
	proot-links
	proot-locales
	proot-message
	proot-network
	proot-packages
	proot-setup
	proot-silent
	proot-superuser
	proot-timezones
	proot-user
	proot-welcome
)

# download #

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}
