#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-26-2021"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# get user information

console.fwd "The following information is required to set up your environment."
echo

console.wrn "The information will be used to set up the user account."
console.wrn "The fields cannot be empty."
echo

# values #

information_list=(
	user_name
	first_name
	last_name
	user_email
	user_password
)

# manage user input for information_list

console_rtn=()

console.input ${information_list[@]}

eval ${console_rtn[@]}

# export variables

cat << FILE ->> "${BINARIES_DIRECTORY}"/globals

# user information #

export first_name="${first_name}"
export last_name="${last_name}"
export full_name="${first_name} ${last_name}"
export user_name="${user_name}"
export user_email"${user_email}"
export user_password="${user_password}"
FILE
