#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Finalizing setup [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

[ -f "${PREFIX}"/bin/dextop ] && source "${PREFIX}"/bin/dextop

# setup #

setup_list=(
	# setup proot expansion to default system
	proot-expand
	# setup proot package requirements
	proot-packages
	# setup proot binary fixes and links
	proot-links
	# setup proot user
	"proot-user ${user_name}"
	# setup proot user superuser privileges
	"proot-superuser ${user_name}"
	# setup proot file manager bookmarks
	proot-bookmarks
	# setup proot silent login
	proot-silent
	# setup proot environment files
	proot-environment
	# setup proot command aliases
	proot-aliases
	# setup proot login messages
	proot-welcome
	# setup proot initial login configuration steps
	proot-configuration
	# setup checkpoint
	proot-checkpoint
	# setup cleanup
	proot-clean
)

# setup #

for setup in ${setup_list[@]}
do
	console.run "${BINARIES_DIRECTORY}"/"${setup}"
done