#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# directories #

# files #

console.inf "Creating configuration files."
echo

# .bash_aliases

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_aliases

FILE

# .bash_logout

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_logout

FILE

# .bashrc

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bashrc
for file in .*_aliases
do
	. ~/"${file}"
done

FILE

# .profile

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

FILE
