#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# set IFS

IFS=' '

read uid gid groups <<< $(id)

# variables

uid=${uid/uid=}
gid=${gid/gid=}
groups=${groups/groups=}

# parse existing groups

console.inf "Transferring unregistered group IDs."
echo

# set IFS

IFS=','

read -r -a groups_list <<< "${groups}"

for line in "${groups_list[@]}"
do
	line=${line/(/ }
	line=${line/)}

	# set IFS

	IFS=' '

	# transfer unregistered IDs

	read group_number group_name <<< ${line}

	[ -f "${ROOT_DIRECTORY}"/etc/group ]   && echo "${group_name}:x:${group_number}:" >> "${ROOT_DIRECTORY}"/etc/group
	[ -f "${ROOT_DIRECTORY}"/etc/gshadow ] && echo "${group_name}:x:${group_number}:" >> "${ROOT_DIRECTORY}"/etc/gshadow

done

# reset IFS

IFS=''
