#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# silence login prompt

console.inf "Writing intial login configuration routine."
echo

# write initial login configuration routine

cat << "FILE" ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile
# system configuration #

sudo dpkg-reconfigure locales

sudo dpkg-reconfigure tzdata

# remove system configuration routine after first run

sed -i '/# system configuration #/,$d' "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

FILE
