#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

first_name="${1}"
last_name="${2}"

while (($#))
do
        case "${3}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${0} | [First Name] [Last Name] | [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                "")
                        # handle empty argument
                        # use default values specified in 'proot' command

                        :
                ;;

                *)
                        echo
                        echo -e "Usage: ${0} | [First Name] [Last Name] | [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

if [[ $# -lt 2 ]]
then
	echo
	echo -e "Usage: ${0} | [First Name] [Last Name] | [OPTION]"
	echo

	exit 1
fi

# variables #

user_name="${first_name,,}"

# add user

console.inf "Creating user account."
echo

useradd -m -s "${SHELL}" ${user_name}

# get IDs

uid="$(id -u ${user_name})"
gid="$(id -g ${user_name})"

# home #

# populate home directory with standard folders

console.inf "Setting up user home directory."
echo

list=(
	Desktop
	Documents
	Downloads
	Git
	Music
	Pictures
	Public
	Templates
	Videos
)

console.directory "${ROOT_DIRECTORY}"/home/"${user_name}"/ ${list[@]}

# runtime #

console.inf "Setting up user runtime directory."
echo

# create directory and set permissions

mkdir -p /run/user/"${uid}" -m 700
mkdir -p /run/user/"${user_name}" -m 700

# set ownership

chown "${uid}":"${gid}" -R /run/user/"${uid}"
chown "${uid}":"${gid}" -R /run/user/"${user_name}"
