#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Setting up packages [ ${script%-*} ]"
echo

# variables #

# set defaults

# update packages list

console.update

# upgrade installed packages

console.upgrade

# values #

administration_list=(
	sudo
)

applications_list=(
	leocad
	povray
	youtube-dl
)

frameworks_list=(
	libqt5concurrent5
	libqt5opengl5
	libqt5printsupport5
	libqt5xml5
)

locales_list=(
	keyboard-configuration
	locales
	locales-all
)

security_list=(
	ca-certificates
	openssl
)

display_list=(
	dbus-x11
	x11-utils
	x11-xserver-utils
	x11-xkb-utils
	x11-xfs-utils
)

documentation_list=(
	man
	man-db
)

themes_list=(
	arc-theme
	breeze-cursor-theme
	qt5-style-platform-gtk2
	qt5-style-plugin-gtk2
	tango-icon-theme
)

vnc_list=(
	tigervnc-common
	tigervnc-standalone-server
)

xfce4_list=(
	xfce4
	xfce4-goodies
	xfce4-appfinder
	xfce4-appmenu-plugin
	xfce4-battery-plugin
	xfce4-clipman
	xfce4-clipman-plugin
	xfce4-cpufreq-plugin
	xfce4-cpugraph-plugin
	xfce4-datetime-plugin
	xfce4-dev-tools
	xfce4-dict
	xfce4-diskperf-plugin
	xfce4-equake-plugin
	xfce4-eyes-plugin
	xfce4-fsguard-plugin
	xfce4-genmon-plugin
	xfce4-goodies
	xfce4-indicator-plugin
	xfce4-mailwatch-plugin
	xfce4-mount-plugin
	xfce4-mpc-plugin
	xfce4-netload-plugin
	xfce4-notes
	xfce4-notes-plugin
	xfce4-notifyd
	xfce4-panel
	xfce4-panel-profiles
	xfce4-places-plugin
	xfce4-power-manager
	xfce4-power-manager-data
	xfce4-power-manager-plugins
	xfce4-pulseaudio-plugin
	xfce4-screensaver
	xfce4-screenshooter
	xfce4-sensors-plugin
	xfce4-session
	xfce4-settings
	xfce4-smartbookmark-plugin
	xfce4-sntray-plugin
	xfce4-sntray-plugin-common
	xfce4-statusnotifier-plugin
	xfce4-systemload-plugin
	xfce4-taskmanager
	xfce4-terminal
	xfce4-time-out-plugin
	xfce4-timer-plugin
	xfce4-verve-plugin
	xfce4-volumed
	xfce4-wavelan-plugin
	xfce4-weather-plugin
	xfce4-whiskermenu-plugin
	xfce4-xkb-plugin
	midori
	elementary-xfce-icon-theme
	blackbird-gtk-theme
	bluebird-gtk-theme
	greybird-gtk-theme
)

# initialize install list

install_list=()

# options #

# full

if [[ "${install_option}" = "full" ]]
then
	desktop_environment_list=(
		${xfce4_list[@]}
	)

	install_list+=(
		${desktop_environment_list[@]}
		${themes_list[@]}
	)
fi

# minimal

if [[ "${install_option}" = "minimal" ]]
then
	desktop_environment_list=(
		${xfce4_list[@]}
	)

	install_list+=(
		${desktop_environment_list[@]}
	)
fi

# populate install list

install_list+=(
	${administration_list[@]}
	${applications_list[@]}
	${frameworks_list[@]}
	${locales_list[@]}
	${documentation_list}
	${display_list[@]}
	${security_list[@]}
	${vnc_list[@]}
)

# install #

console.install ${install_list[@]}
