#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Gathering setup information [ ${script%-*} ] ."
echo

# variables #

# set defaults

# get user information
console.inf "This information will be used to set up the user account."
echo

console.wrn "Information is required to set up your environment:"
console.wrn "Fields cannot be empty."
echo

# values #

information_list=(
	user_name
	first_name
	last_name
	user_email
	user_password
)

# handle user input for information_list

console_rtn=()

console.input ${information_list[@]}

eval ${console_rtn[@]}

# export variables

echo '# information #'															>> "${PREFIX}"/bin/dextop

echo "export first_name=${first_name}"											>> "${PREFIX}"/bin/dextop
echo "export last_name=${last_name}"											>> "${PREFIX}"/bin/dextop
echo "export full_name=${first_name} ${last_name}"								>> "${PREFIX}"/bin/dextop
echo "export user_name=${user_name}"											>> "${PREFIX}"/bin/dextop
echo "export user_email=${user_email}"											>> "${PREFIX}"/bin/dextop
echo "export user_password=${user_password}"									>> "${PREFIX}"/bin/dextop
