#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Writing command aliases [ ${script%-*} ]"
echo

# variables #

# set defaults

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_aliases
# shell #

[[ $(id -u) = 0 ]] && PS1="$(tput setaf 1[ D ] )>_ # $(tput sgr 0)" || PS1="[ D ] >_ $ "

# sudo #

alias sudo='sudo -p "$(tput setaf 3)[ D ] >_ ? $(tput sgr 0)"'

# directories #

alias '..'='cd ..'
alias '...'='cd ../../../'
alias '....'='cd ../../../../'
alias '.....'='cd ../../../../'

alias 'hd'='cd "${HOME}"'
alias 'gd'='cd "${HOME}"/Git'
alias 'vd'='cd "${HOME}"/.vnc'
alias 'rd'='cd /'
alias 'md'='cd /media'
alias 'id'='cd /media/Internal'
alias 'ed'='cd /media/External'

alias 'directory'='echo ${PWD}'
alias 'mkdir'='mkdir -p'

# files #

alias 'count'='find . -type f | wc -l'

# list #

alias 'ls'='ls -a -c -h -l --color=auto --group-directories-first'

# apt-get #

alias 'autoclean'='sudo apt-get autoclean'
alias 'autoremove'='sudo apt-get autoremove'
alias 'check'='sudo apt-get check'
alias 'clean'='sudo apt-get clean'
alias 'distribution-upgrade'='sudo apt-get dist-upgrade'
alias 'download'='sudo apt-get download'
alias 'install'='sudo apt-get install --no-install-recommends --no-upgrade'
alias 'purge'='sudo apt-get purge'
alias 'reinstall'='sudo apt-get reinstall'
alias 'repair'='sudo apt-get -f install'
alias 'remove'='sudo apt-get remove'
alias 'source'='sudo apt-get source'
alias 'update'='sudo apt-get update'
alias 'upgrade'='sudo apt-get upgrade'

# apt-cache #

alias 'depends'='apt-cache depends'
alias 'reverse'='apt-cache rdepends'
alias 'search'='apt-cache search'
alias 'status'='apt-cache stats'

# cp #

alias 'cp'='rsync -a -r --progress -h'

# dd #

alias 'dd'="dd if=${1} of=${2} bs=${3} status=progress"

# du #

alias 'usage'='du -a -d 1 -h -S --time 2> /dev/null | sort -n -r'

# dpkg #

alias 'd-install'='sudo dpkg -i'
alias 'd-force-install'='sudo dpkg -i --force-all'

# git #

alias 'gc'='git clone'
alias 'gi'='git init'
alias 'gp'='git pull'

alias 'ga'='git add *'
alias 'gm'="git commit -a -m ${1}"
alias 'gs'='git push'

alias 'gu'='ga && gm "Code & Features Update" && gs'

# kill #

alias 'kill'="sudo pkill -9 ${1}"

# nano #

alias 'nano'='nano -c -g -i -l -m -D -F -J80 -T4'

# ping #

alias 'ping'='ping -c 5'

# services #

alias 'kill'='sudo pkill -9'
alias 'start'='sudo systemctl start'
alias 'stop'='sudo systemctl stop'
alias 'enable'='sudo systemctl enable'
alias 'disable'='sudo systemctl disable'
alias 'status'='sudo systemctl status'

# ip #

alias 'address'='echo "External IP address: $(curl ipinfo.io/ip)"'

# weather #

alias 'weather'='curl wttr.in'
FILE