#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

if [[ $# -lt 1 ]] || [[ $# -gt 3 ]]
then
	echo
	echo -e "Usage: ${script} [User Name] | [First Name] [Last Name] | [OPTION]"
	echo

	exit 1
fi

if [[ $# -eq 1 ]]
then
	user_name="${1}"
fi

if [[ $# -eq 2 ]]
then
	first_name="${1}"
	last_name="${2}"
	user_name="${first_name,,}"
fi

if [[ $# -eq 3 ]]
then
	user_name="${1}"
	first_name="${2}"
	last_name="${3}"
fi

while (($#))
do
	case "${4}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} | [First Name] [Last Name] | [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} | [First Name] [Last Name] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Generating user account [ ${script%-*} ]"
echo

# variables #

full_name="${first_name} ${last_name}"

# set defaults

room_number=""
work_number=""
home_number=""

# functions #

add_user () {
	# silent configuration:
	# set --gecos and --disabled-password for fully silent execution
	
	adduser																					\
		--gecos "${full_name},${room_number},${work_number},${home_number},${user_email}"	\
		--shell "${SHELL}"																	\
		--disabled-password "${user_name}"
	
}

add_password () {
	# use 'chpasswd' to append user password to account for fully silent execution
	
	chpasswd <<< "${user_name}:${user_password}"
}

# create user acount

console.fwd "Creating account..."
echo

# generate user entry
# use /dev/null redirection:
# adduser prevents stdout error redirect - cannot use 'console.silence'

add_user > /dev/null

console.fwd "Setting password..."
echo

# generate password credential for user entry
# use /dev/null redirection:
# chpasswd prevents stdout error redirect - cannot use 'console.silence'

add_password > /dev/null

# get IDs

uid="$(id -u ${user_name})"
gid="$(id -g ${user_name})"

console.fwd "Setting up home directory..."
echo

# populate directory list:
# use standard home directories

directories_list=(
	Desktop
	Documents
	Downloads
	Music
	Pictures
	Public
	Templates
	Videos
)

# create home directory

console.directory "${HOME_DIRECTORY}" ${directories_list[@]}

# runtime #

console.fwd "Setting up runtime directory..."
echo

# create runtime directory

console.directory /run/user "${uid}"
console.directory /run/user "${user_name}"

# set runtime directory permission

chmod 700 /run/user/"${uid}"
chmod 700 /run/user/"${user_name}"

# set runtime directory ownership

chown "${uid}":"${gid}" -R /run/user/"${uid}"
chown "${uid}":"${gid}" -R /run/user/"${user_name}"