#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# environment

console.inf "Setting library preload."
echo

cat << "FILE" ->> "${ROOT_DIRECTORY}"/etc/environment
LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1:/lib/libandroid-shmem-aarch64.so
FILE
