#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# variables #

console.fwd "Writing configuration..."
echo

# write configuration

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

# proot configuration #

commands_list=(
	proot-locales
	proot-timezones
	leocad-download
	leocad-configuration
	xfconf-desktop
)

for command in ${commands_list[@]}
do
	sudo -H -u "${USER}" xfce4-terminal --fullscreen --hide-menubar --hide-scrollbar -x "${command}"

	wait
done
FILE

# purge configuration

cat << "FILE" ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

# remove configuration commands after execution

sed -i '/# proot configuration #/,$d' "${ROOT_DIRECTORY}"/home/"${USER}"/.profile
FILE
