#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# initial prompt clear #

clear

# enable quiet package install

export DEBIAN_FRONTEND=noninteractive

# update packages list

console.update

# upgrade installed packages

console.upgrade

# packages #

applications_list=(
	blender
	leocad
	povray
	youtube-dl
)

frameworks_list=(
	libqt5concurrent5
	libqt5opengl5
	libqt5printsupport5
	libqt5xml5
)

utilities_list=(
	curl
	dialog
	ffmpeg
	git
	hub
	jq
	nano
	net-tools
	nmap
	openssh-server
	p7zip
	python
	rsync
	spell
	ssh
	sudo
	unrar
	wmctrl
	xdotool
	zip
)

# install list #

install_list=()

# core packages lists to load and install

install_list+=(
	${applications_list[@]}
	${frameworks_list[@]}
	${utilities_list[@]}
)

# install #

console.install ${install_list[@]}

# update #

# set additional repository updates for installed applications and utilities

# youtube-dl #

console.get https://yt-dl.org/downloads/latest					youtube-dl		/usr/bin

# leocad #

console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main	leocad-configuration	/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main	leocad-download		/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main	leocad-launcher		/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main	leocad-position		/usr/bin
