#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

while (($#))
do
	case "${1}" in
		-f|--full)
			option="full"
		;;
		-u|--update)
			option="update"
		;;
		-h|--help)
			echo -e ""
			echo -e "USAGE:"
			echo -e ""
			echo -e "-f, --full \t Full setup: download and install full applications list and utilities."
			echo -e "-u, --update \t Update setup: update applications list and utilities."
			echo -e ""
			exit
		;;
		-v|--version)
			echo -e ""
			echo -e "${script} [ Version ${version} ]"
			echo -e ""
			exit
		;;
		*)
			echo -e ""
			echo "Usage: ${0} <install option>"
			echo -e ""
			echo -e "${script}: Unknown option ${1}"
			echo -e "Type './${script} --help' for help and usage information."
			echo -e ""
			exit 1
		;;
	esac

	shift
done

# set defaults

option="${1}"

[ -z "${option}" ] && option="full" || :

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

version="01-15-2020"

# enable quiet package install

export DEBIAN_FRONTEND=noninteractive

if [[ "${option}" = "full" ]] || [[ "${option}" = "update" ]]
then
	# update packages list

	console.update

	# upgrade installed packages

	console.upgrade
fi

# packages #

applications_list=(
	blender
	leocad
	povray
	youtube-dl
)

frameworks_list=(
	libqt5concurrent5
	libqt5opengl5
	libqt5printsupport5
	libqt5xml5
)

utilities_list=(
	curl
	dialog
	ffmpeg
	git
	hub
	jq
	nano
	net-tools
	nmap
	openssh-server
	p7zip
	python
	rsync
	spell
	ssh
	unrar
	wmctrl
 	xclip
	xdotool
	zip
)

# install list #

install_list=()

# core packages lists to load and install

install_list+=(
	${applications_list[@]}
	${frameworks_list[@]}
	${utilities_list[@]}
)

if [[ "${option}" = "full" ]]
then
	# install #
	
	console.install ${install_list[@]}
fi


if [[ "${option}" = "full" ]] || [[ "${option}" = "update" ]]
then
	# update #
	
	# set additional repository updates for installed applications and utilities
	
	# youtube-dl #
	
	console.download https://yt-dl.org/downloads/latest								/usr/bin				youtube-dl
	
	# leocad #
	
	console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin				leocad-build
	console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin				leocad-configuration
	console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin				leocad-download
	console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin				leocad-launcher
	console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main	/usr/bin				leocad-position
	
	# local install #
	
	# dwm #
	
	console.download https://raw.githubusercontent.com/nathaneltitane/dwm/main	/usr/bin				dwm-build
	
	# st #
	
	console.download https://raw.githubusercontent.com/nathaneltitane/st/main	/usr/bin				st-build
fi
