#!/bin/bash

# dependencies #

curl -sL get.cnsl.app/console > "${PREFIX}"/bin/console && source "${PREFIX}"/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

if [[ $# -gt 3 ]]
then
	echo
	echo -e "Usage: ${script} [Distribution Name] | [Distribution Version] | [OPTION]"
	echo

	exit 1
fi

if [[ $# -eq 1 ]]
then
	distribution_name="${1}"
fi

if [[ $# -eq 2 ]]
then
	distribution_name="${1}"
	distribution_version="${2}"
fi

if [[ $# -eq 3 ]]
then
	distribution_name="${1}"
	distribution_version="${2}"

	install_option="${3}"
fi

while (($#))
do
	case "${3}" in
		-f|--full)
			install_option="full"
		;;

		-m|--minimal)
			install_option="minimal"
		;;

		-h|--help)
			echo
			echo -e "USAGE:"
			echo
			echo -e "-f, --full \t\t Full setup: download and install full desktop environment and utilities."
			echo -e "-m, --minimal \t\t Minimal setup: download and install minimal desktop environment and utilities."
			echo
			echo -e "-h, --help \t\t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} [Distribution Name] | [Distribution Version] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# prompt #

console.script "Starting setup [ ${script%-*} ]"
echo

# variables #

# set defaults

[ -z "${distribution_name}" ]				&& distribution_name="ubuntu"
[ -z "${distribution_version}" ]			&& distribution_version="20.04.2"

[ -z "${install_option}" ]					&& install_option="full"

# handle distribution code markup

# set IFS

IFS='.'

read code_year code_month code_revision <<< "${distribution_version}"

if [ -z "${code_revision}" ]
then
	distribution_release="${distribution_version}"
else
	distribution_release="${distribution_version%.*}"
fi

# reset IFS

IFS=''

# export variables

echo '# proot variables #'														>> "${PREFIX}"/bin/globals

echo "export DISTRIBUTION_NAME=${distribution_name}"							>> "${PREFIX}"/bin/globals
echo "export DISTRIBUTION_VERSION=${distribution_version}"						>> "${PREFIX}"/bin/globals
echo "export DISTRIBUTION_RELEASE=${distribution_release}"						>> "${PREFIX}"/bin/globals

echo 'export LOAD_DIRECTORY="${DISTRIBUTION_NAME}/${DISTRIBUTION_RELEASE}"'		>> "${PREFIX}"/bin/globals
echo 'export ROOT_DIRECTORY="${IMAGE_DIRECTORY}/${LOAD_DIRECTORY}"'				>> "${PREFIX}"/bin/globals

echo '# installation #'															>> "${PREFIX}"/bin/globals

echo "export install_option=${install_option}"									>> "${PREFIX}"/bin/globals

# source variables

[ -f "${PREFIX}"/bin/globals ] && source "${PREFIX}"/bin/globals

# setup #

# setup proot utilities

console.run "${BINARIES_DIRECTORY}"/proot-download

# welcome message

console.run "${BINARIES_DIRECTORY}"/proot-message

# verify architecture compatibility

console.run "${BINARIES_DIRECTORY}"/proot-architecture

# setup proot user information

console.run "${BINARIES_DIRECTORY}"/proot-information

# setup proot proc /proc entries

console.run "${BINARIES_DIRECTORY}"/proot-proc

# setup proot image

console.run "${BINARIES_DIRECTORY}"/proot-image

# setup proot group IDs

console.run "${BINARIES_DIRECTORY}"/proot-groups

# setup proot network requirements  - [ device < // > [ termux < // > [ proot ] ] ]

console.run "${BINARIES_DIRECTORY}"/proot-network

# setup proot initialization routine

console.run "${BINARIES_DIRECTORY}"/proot-initialize

# setup proot session

console.run "${BINARIES_DIRECTORY}"/proot-launch