#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="04-12-2021"

# usage #

if [[ $# -lt 1 ]] || [[ $# -gt 3 ]]
then
	echo
	echo -e "Usage: ${script} [User Name] | [First Name] [Last Name] | [OPTION]"
	echo

	exit 1
fi

if [[ $# -eq 1 ]]
then
	user_name="${1}"
fi

if [[ $# -eq 2 ]]
then
	first_name="${1}"
	last_name="${2}"
	user_name="${first_name,,}"
fi

if [[ $# -eq 3 ]]
then
	user_name="${1}"
	first_name="${2}"
	last_name="${3}"
fi

while (($#))
do
	case "${4}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} | [First Name] [Last Name] | [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ${script} | [First Name] [Last Name] | [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# variables #

full_name="${first_name} ${last_name}"

# set defaults

room_number=""
work_number=""
home_number=""

# add user

console.inf "Creating user account."
echo

echo -e "${user_password}\n${user_password}\n" | adduser "${user_name}" --gecos "${full_name},${room_number},${work_number},${home_number},${user_email}" --shell "${SHELL}"

# useradd -m -p "${user_password}" -s "${SHELL}" "${user_name}"

console.inf "Setting password."
echo

users_list=(
	root
	"${user_name}"
)

for users in ${users_list[@]}
do
	# clear any default passwords present in /etc/passwd from image setup

	passwd -d "${user_name}"

	# add password to user account

	echo -e "${user_password}\n${user_password}\n" | passwd "${user_name}"
done

# get IDs

uid="$(id -u ${user_name})"
gid="$(id -g ${user_name})"

# home #

# populate home directory with standard folders

console.inf "Setting up user home directory."
echo

directories_list=(
	Desktop
	Documents
	Downloads
	Git
	Music
	Pictures
	Public
	Templates
	Videos
)

console.directory "${ROOT_DIRECTORY}"/home/"${user_name}"/ ${directories_list[@]}

# runtime #

console.inf "Setting up user runtime directory."
echo

# create directory and set permissions

mkdir -p /run/user/"${uid}" -m 700
mkdir -p /run/user/"${user_name}" -m 700

# set ownership

chown "${uid}":"${gid}" -R /run/user/"${uid}"
chown "${uid}":"${gid}" -R /run/user/"${user_name}"
