#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# initial prompt clear #

clear

# list supported processor architectures

cpu_architectures=(
	aarch64
	arm
	amd64
	i*86
	x86_64
)

# list supported image architechtures

img_architectures=(
	arm64
	armhf
	amd64
	i386
	amd64
)

# test processor architecture string

console.inf "Checking system architecture."
echo

print_architecture="$(dpkg --print-architecture)"

for i in ${!cpu_architectures[@]}
do
	if [[ "$print_architecture" == "${cpu_architectures[i]}" ]]
	then
		img_architecture=${img_architectures[i]}

		console.scs "Valid architecture detected [ ${img_architecture} ]."
		echo

		break
	fi
done

# test image architecture string

if [ -z "$img_architecture" ]
then
	console.wrn "Unknown architecture:"
	console.wrn "Aborting."
	echo

	console.stp "Exiting."
	echo

	exit 1
fi

# export variables

export iso_architecture="${img_architecture}"