#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Setting up packages [ ${script%-*} ]"
echo

# variables #

# set defaults

# update packages list

console.update

# upgrade installed packages

console.upgrade

# values #

administration_list=(
	sudo
)

applications_list=(
	leocad
	povray
	youtube-dl
)

locales_list=(
	keyboard-configuration
	locales
	locales-all
)

security_list=(
	ca-certificates
	openssl
)

display_list=(
	dbus-x11
	x11-apps
	x11-common
	x11-session-utils
	x11-touchscreen-calibrator
	x11-utils
	x11-xfs-utils
	x11-xkb-utils
	x11-xserver-utils
)

documentation_list=(
	man
	man-db
)

themes_list=(
	arc-theme
	breeze-cursor-theme
	tango-icon-theme
	
	qt5-style-platform-gtk2
	qt5-style-plugin-gtk2
)

vnc_list=(
	tigervnc-common
	tigervnc-standalone-server
)

kde_list=(
	plasma-desktop
	plasma-applet-redshift-control
	plasma-browser-integration
	plasma-calendar-addons
	plasma-dataengines-addons
	plasma-desktop
	plasma-discover
	plasma-discover-backend-flatpak
	plasma-discover-backend-snap
	plasma-discover-common
	plasma-discover-flatpak-backend
	plasma-discover-snap-backend
	plasma-framework
	plasma-integration
	plasma-kdevelop
	plasma-marble
	plasma-nm
	plasma-runner-installer
	plasma-runner-telepathy-contact
	plasma-runners-addons
	plasma-vault
	plasma-wallpapers-addons
	plasma-widgets-addons
	plasma-workspace
	plasma-workspace-wallpapers
	ark
	dolphin
	elisa
	fonts-hack
	fonts-noto-cjk
	fonts-noto-hinted
	fonts-noto-mono
	fonts-noto-unhinted
	kate
	kcalc
	kcharselect
	kdialog
	keditbookmarks
	kfind
	kgamma5
	khelpcenter
	khotkeys
	kinfocenter
	kio
	kio-extras
	kio-extras-data
	kmenuedit
	kscreen
	ksshaskpass
	ksysguard
	ktorrent
	kwin-x11
	kwin
	kwalletmanager
	konqueror
	konsole
	konversation
	kwin
	kwrite
	kwrited
	milou
	muon
	okular
	systemsettings
)

xfce4_list=(
	xfce4
	xfce4-goodies
	xfce4-appfinder
	xfce4-appmenu-plugin
	xfce4-battery-plugin
	xfce4-clipman
	xfce4-clipman-plugin
	xfce4-cpufreq-plugin
	xfce4-cpugraph-plugin
	xfce4-datetime-plugin
	xfce4-dev-tools
	xfce4-dict
	xfce4-diskperf-plugin
	xfce4-equake-plugin
	xfce4-eyes-plugin
	xfce4-fsguard-plugin
	xfce4-genmon-plugin
	xfce4-goodies
	xfce4-indicator-plugin
	xfce4-mailwatch-plugin
	xfce4-mount-plugin
	xfce4-mpc-plugin
	xfce4-netload-plugin
	xfce4-notes
	xfce4-notes-plugin
	xfce4-notifyd
	xfce4-panel
	xfce4-panel-profiles
	xfce4-places-plugin
	xfce4-power-manager
	xfce4-power-manager-data
	xfce4-power-manager-plugins
	xfce4-pulseaudio-plugin
	xfce4-screensaver
	xfce4-screenshooter
	xfce4-sensors-plugin
	xfce4-session
	xfce4-settings
	xfce4-smartbookmark-plugin
	xfce4-sntray-plugin
	xfce4-sntray-plugin-common
	xfce4-statusnotifier-plugin
	xfce4-systemload-plugin
	xfce4-taskmanager
	xfce4-terminal
	xfce4-time-out-plugin
	xfce4-timer-plugin
	xfce4-verve-plugin
	xfce4-volumed
	xfce4-wavelan-plugin
	xfce4-weather-plugin
	xfce4-whiskermenu-plugin
	xfce4-xkb-plugin
	elementary-xfce-icon-theme
	blackbird-gtk-theme
	bluebird-gtk-theme
	greybird-gtk-theme
	midori
)

# initialize install list

install_list=()

# options #

# desktop

if [[ "${desktop_option}" = "kde" ]]
then
	desktop_environment_list=(
		${kde_list[@]}
	)
fi

if [[ "${desktop_option}" = "xfce" ]]
then
	desktop_environment_list=(
		${xfce4_list[@]}
	)
fi

# full

if [[ "${install_option}" = "full" ]]
then
	install_list+=(
		${desktop_environment_list[@]}
		${themes_list[@]}
	)
fi

# minimal

if [[ "${install_option}" = "minimal" ]]
then
	install_list+=(
		${desktop_environment_list[@]}
	)
fi

# populate install list

install_list+=(
	${administration_list[@]}
	${applications_list[@]}
	${locales_list[@]}
	${documentation_list}
	${display_list[@]}
	${security_list[@]}
	${vnc_list[@]}
)

# install #

console.install ${install_list[@]}
