#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Finalizing setup [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

[ -f "${PREFIX}"/bin/dextop ] && source "${PREFIX}"/bin/dextop

# setup #

# setup user:
# keep outside of array to pass and handle arguments

# setup proot user

"${BINARIES_DIRECTORY}"/proot-user "${user_name}"

# setup proot superuser privilege

"${BINARIES_DIRECTORY}"/proot-superuser "${user_name}"

# clear

console.clear

# continue setup

setup_list=(
	proot-expand
	proot-repositories
	proot-packages
	proot-links
	proot-bookmarks
	proot-silent
	proot-environment
	proot-welcome
	proot-configuration
	proot-checkpoint
	proot-clean
)

# setup #

for setup in ${setup_list[@]}
do
	"${BINARIES_DIRECTORY}"/"${setup}"
	
	console.clear
done