#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading utilities [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && source "${BINARIES_DIRECTORY}"/console

# values #

binaries_list=(
	proot-architecture
	proot-bookmarks
	proot-checkpoint
	proot-clean
	proot-compositing
	proot-configuration
	proot-environment
	proot-expand
	proot-groups
	proot-image
	proot-information
	proot-initialize
	proot-keyboard
	proot-links
	proot-locales
	proot-network
	proot-packages
	proot-preload
	proot-repositories
	proot-session
	proot-setup
	proot-shell
	proot-silent
	proot-superuser
	proot-timezones
	proot-user
	proot-utilities
	proot-welcome
)

# download #

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}
