#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="04-14-2021"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# download #

# youtube-dl

console.download https://yt-dl.org/downloads/latest							/usr/bin	youtube-dl

# leocad

console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin	leocad-build
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin	leocad-configuration
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin	leocad-download
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin	leocad-launcher
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin	leocad-position

# xfce

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/templates/utilities	/usr/bin	xfconf-read
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/templates/utilities	/usr/bin	xfconf-write

# run  #

binaries_list=(
	leocad-configuration
)

for binary in ${binaries_list[@]}
do
	bash "${binary}"
done
