#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up shell [ ${script%-*} ]"
echo

# variables #

# set defaults

# .bash_aliases

cat << 'FILE' -> "${HOME}"/.bash_aliases

if [ -d "${HOME}"/.bash-aliases ]
then
	for alias in "${HOME}"/.bash-aliases/*
	do
		test -x "${alias}" && . "${alias}"
	done
fi
FILE

# .bash functions

cat << 'FILE' -> "${HOME}"/.bash_functions

if [ -d "${HOME}"/.bash-functions ]
then
	for function in "${HOME}"/.bash-functions/*
	do
		test -x "${function}" && . "${function}"
	done
fi
FILE

# .bash_logout

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_logout

FILE

# .bashrc

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bashrc

shopt -s checkwinsize
shopt -s histappend
shopt -s histverify

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

if ! shopt -oq posix
then
	if [ -f /usr/share/bash-completion/bash_completion ]
	then
		. /usr/share/bash-completion/bash_completion

	elif [ -f /etc/bash_completion ]
	then
		. /etc/bash_completion
	fi
fi

INITIAL=${USER::1}

if [[ $(id -u) = 0 ]]
then
	PS1="$(tput setaf 1)[ ${INITIAL} ] >_ # $(tput sgr 0)"
else
	PS1="$(tput setaf 7)[ ${INITIAL} ] >_ $ $(tput sgr 0)"
fi

if [ -f "${HOME}"/.bash_aliases ]
then
	. "${HOME}"/.bash_aliases
fi

if [ -f "${HOME}"/.bash_functions ]
then
	. "${HOME}"/.bash_functions
fi
FILE

# .profile

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

if [ -n "${BASH_VERSION}" ]
then
	if [ -f "{$HOME}"/.bashrc ]
	then
		. "${HOME}"/.bashrc
	fi
fi

if [ -d "${HOME}"/bin ]
then
	PATH="${HOME}/bin:${PATH}"
fi

if [ -d "${HOME}"/.local/bin ]
then
	PATH="${HOME}/.local/bin:${PATH}"
fi
FILE
