#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Configuring network [ ${script%-*} ]"
echo

# variables #

# set defaults

# set hostname

console.fwd "Setting up [ hostname ]..."
echo

cat << FILE -> "${ROOT_DIRECTORY}"/etc/hostname 
"${hostname}"
FILE

# set hosts

console.fwd "Setting up [ hosts ]..."
echo

cat << FILE -> "${ROOT_DIRECTORY}"/etc/hosts
# IPv4 #

127.0.0.1	localhost.localdomain
127.0.0.1	localhost

# IPv6 #

::1			localhost.localdomain
::1			localhost
::1			ip6-localhost
::1			ip6-loopbak
fe00::0		ip6-localnet
fe00::0		ip6-mcastprefix
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
ff02::3		ip6-allhosts

FILE

# set nameserver

console.fwd "Setting up [ nameserver ]..."
echo

cat << 'FILE' -> "${ROOT_DIRECTORY}"/etc/resolv.conf
nameserver 1.1.1.1
nameserver 1.0.0.1
FILE

