#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="10-24-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

failsafe_install () {

	frobulator.stp "Please wait..."
	echo

	yes | pkg install ${@} 2>&1 &

	frobulator.progress "process"

}

# update packages list

frobulator.update

# upgrade installed packages

frobulator.upgrade

# values #

display_list+=(
	xorg-server-xvfb
	xwayland
)

documentation_list+=(
	man
)

extensions_list+=(
	termux-am
	termux-am-socket
	termux-api
	termux-apt-repo
	termux-auth
	termux-create-package
	termux-elf-cleaner
	termux-exec
	termux-gui-bash
	termui-gui-c
	termux-gui-package
	termux-gui-pm
	termux-keyring
	termux-licenses
	termux-services
	termux-tools
	termux-x11-nightly
)

fonts_list+=(
)

i3_list+=(
	i3
	i3status
)

i3_addons_list+=(
	rofi
)

icon_themes_list+=(
	papirus-icon-theme
)

multimedia_list+=(
	ffmpeg
	flac
	gstreamer
	gst-plugins-good
	gst-plugins-bad
	gst-plugins-ugly
	gst-plugins-base
)

repositories_list+=(
	game-repo
	root-repo
	science-repo
	termux-apt-repo
	unstable-repo
	x11-repo
)

security_list+=(
)

utilities_list+=(
	fakeroot
	git
	hub
	htop
	ncurses
	ncurses-utils
	openssh
	proot
	ranger
	zip
	unzip
	bzip2
	gzip
	lzip
	p7zip
	rsync
	wget
)

vnc_list+=(
	x11vnc
)

xfce_list+=(
	xfce4
	xfce4-appfinder
	xfce4-dict
	xfce4-notifyd
	xfce4-panel
	xfce4-screenshooter
	xfce4-session
	xfce4-settings
	xfce4-taskmanager
	xfce4-terminal
	galculator
	gigolo
	mousepad
	parole
	thunar
	thunar-archive-plugin
	ristretto
	tumbler
)

xfce_fonts_list+=(
)

xfce_themes_list+=(
#	arc-theme
	adwaita-icon-theme
	adwaita-icon-theme-full
	papirus-icon-theme
#	blackbird-gtk-theme
#	bluebird-gtk-theme
#	greybird-gtk-theme
#	elementary-xfce-icon-theme
#	gnome-themes-standard
#	gnome-themes-extra
#	gnome-themes-extra-data
#	tango-icon-theme
#	tango-icon-theme-common
#	tango-icon-theme-extras
)

xfce_addons_list+=(
	xfce4-calculator-plugin
	xfce4-clipman-plugin
	xfce4-datetime-plugin
	xfce4-eyes-plugin
	xfce4-mailwatch-plugin
	xfce4-netload-plugin
	xfce4-notes-plugin
	xfce4-places-plugin
	xfce4-timer-plugin
	xfce4-wavelan-plugin
	xfce4-whiskermenu-plugin
)

# environment #

# console

if [[ $(cat "${HOME}"/.dextop/dextop-environment) = "console" ]]
then
	desktop_environment_list+=()
fi

# i3

if [[ $(cat "${HOME}"/.dextop/dextop-environment) = "i3" ]]
then
	desktop_environment_list+=(
		${i3_list[@]}
		${i3_addons_list[@]}
	)
fi

# xfce

if [[ $(cat "${HOME}"/.dextop/dextop-environment) = "xfce" ]]
then
	desktop_environment_list+=(
		${xfce_list[@]}
		${xfce_fonts_list[@]}
		${xfce_themes_list[@]}
	)

	#	${xfce_addons_list[@]}
fi

# install #

install_list+=(
	${display_list[@]}
	${documentation_list[@]}
	${extensions_list[@]}
	${fonts_list[@]}
	${multimedia_list[@]}
	${repositories_list[@]}
	${security_list[@]}
	${utilities_list[@]}
	${vnc_list[@]}
	${desktop_environment_list[@]}
)

# run failsafe install:
# mitigate termux package management fetch issues

failsafe_install ${install_list[@]}

# run normal install

frobulator.install ${install_list[@]}
