#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading additional utilities [ ${script%-*} ]"
echo

# bash aliases

console.directory "${HOME}" .bash-aliases

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			apt
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			command
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			copy
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			count
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			directory
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			duplicate
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			git
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			grep
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			kill
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			list
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			nano
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			ping
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			sudo
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			shortcuts
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			system
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			usage
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${HOME}"/.bash-aliases			where

# .bash-functions

console.directory "${HOME}" .bash-functions

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		address
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		extract
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		record
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		speed
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		sprunge
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		weather
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${HOME}"/.bash-functions		youtube

# youtube-dl

console.download https://yt-dl.org/downloads/latest											"${BINARIES_DIRECTORY}"			youtube-dl
