#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-22-2021"

# usage #

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# functions #

# add system directories

directories_list+=(
	bkp
	cnt
	img
	mnt
	media
	storage
)

console.directory "${PREFIX}" "${directory}"

directories_list=()

# add home directories

directories_list+=(
	Desktop
	Documents
	Downloads
	Music
	Pictures
	Public
	Templates
	Videos
)

console.directory "${HOME}" "${directory}"

directories_list=()

# fix directory structure

directories_list+=(
	bin
	bkp
	cnt
	etc
	img
	lib
	mnt
	opt
	tmp
	media
	storage
)

for directory in ${directories_list[@]}
do
	ln -s -f "${PREFIX}"/"${directory}" "${PREFIX%/*}"/"${directory}"
done

directories_list=()

# cleanup temporary build files

[ -f "${PREFIX%/*}"/rList ] && rm -rf "${PREFIX%/*}"/rList
