#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading utilities [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && . "${BINARIES_DIRECTORY}"/console

# values #

binaries_list=(
	termux-addons
	termux-bookmarks
	termux-checkpoint
	termux-clean
	termux-links
	termux-packages
	termux-properties
	termux-repositories
	termux-setup
	termux-shell
	termux-silent
	termux-storage
	termux-update
	termux-utilities
	termux-welcome
)

# download #

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}
