#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# directories #

# files #

cat << 'FILE' ->> "${HOME}"/.hushlogin

FILE

console.fwd "Setting up environment [ termux ]..."
echo

console.inf "Creating files."
echo

# .bash_aliases

cat << 'FILE' ->> "${HOME}"/.bash_aliases

FILE

# .bash_logout

cat << 'FILE' ->> "${HOME}"/.bash_logout

FILE

# .bashrc

cat << 'FILE' ->> "${HOME}"/.bashrc

FILE

# .profile

cat << 'FILE' ->> "${HOME}"/.profile

FILE

# termux properties

[ ! -d "${HOME}"/.termux ] && mkdir "${HOME}"/.termux || :

cat << FILE ->> "${HOME}"/.termux/termux.properties

# use black for drawer and dialogs - Android 9.0+ default

use-black-ui = true

# enforce character based input - workaround for word-based input keyboards

enforce-char-based-input = true

# handle the bell character - vibrate | beep | ignore

bell-character=beep

# handle the escape key - escape | back

back-key=back

# rename current terminal session

shortcut.rename-session = ctrl + n

# open a new terminal with ctrl + t (volume down + t)

shortcut.create-session = ctrl + t

# move to previous terminal session

shortcut.previous-session = ctrl + 1

# move to next terminal session

shortcut.next-session = ctrl + 2


# configure keyboard shortcut keys

extra-keys = [																	\
	['ESC', '|',    '/',   'HOME', 'UP',   'END',   'PGUP', '_', 'BKSP'		],	\
	['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN', '-', 'RETURN'	]	\
																				]
FILE

# apply termux properties

console.fwd "Applying changes..."

termux-reload-settings
