#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2021"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# download #

# console #

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && source "${BINARIES_DIRECTORY}"/console

# binaries

binaries_list=(
	proot-aliases
	proot-applications
	proot-architecture
	proot-bookmarks
	proot-checkpoint
	proot-clean
	proot-configuration
	proot-download
	proot-environment
	proot-expand
	proot-fake
	proot-groups
	proot-image
	proot-information
	proot-initialize
	proot-launch
	proot-libraries
	proot-message
	proot-network
	proot-packages
	proot-setup
	proot-superuser
	proot-system
	proot-user
	proot-welcome
	termux-clean
	termux-download
	termux-environment
	termux-message
	termux-packages
	termux-storage
	termux-welcome
	vnc-pass
	vnc-setup
	vnc-start
	vnc-stop
)

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}
