#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/termux-globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# initial prompt clear #

clear

# download #

# console #

curl -sL https://raw.githubusercontent.com/nathaneltitane/console/master/console > "${BINARIES_DIRECTORY}"/console && source "${BINARIES_DIRECTORY}"/console

# binaries

binaries_list=(
	proot-aliases
	proot-applications
	proot-architecture
	proot-download
	proot-environment
	proot-groups
	proot-image
	proot-information
	proot-launch
	proot-libraries
	proot-network
	proot-packages
	proot-setup
	proot-superuser
	proot-system
	proot-user
	proot-welcome
	termux-download
	termux-environment
	termux-globals
	termux-packages
	termux-storage
	termux-welcome
	vnc-pass
	vnc-setup
	vnc-start
	vnc-stop
)

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}

console.clear