#!/bin/bash

# author #

# Nathanel Titane - nathanel.titane@gmail.com

# Termux // Dextop // Ubuntu #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

version="01-15-2020"

# usage #

while (($#))
do
	case "${1}" in
		-f|--full)
			install_option="full"
			;;
		-m|--minimal)
			install_option="minimal"
			;;
		-h|--help)
			echo -e ""
			echo -e "USAGE:"
			echo -e ""
			echo -e "-f, --full \t Full setup: download and install full desktop environment and utilities."
			echo -e "-m, --minimal \t Minimal setup: download and install minimal desktop environment and utilities."
			echo -e ""
			echo -e "-a, --applications: Download a set of optimized and precompiled arm64 applications."
			echo -e ""
			echo -e "-h, --help \t Show help and usage."
			echo -e "-v, --version \t Show ${script} version."
			echo -e ""
			exit
			;;
		-v|--version)
			echo -e ""
			echo -e "${script} [ Version ${version} ]"
			echo -e ""
			exit
			;;
		*)
			echo -e ""
			echo "Usage: ${0} <install option>"
			echo -e ""
			echo -e "${script}: Unknown option ${1}"
			echo -e "Type './${script} --help' for help and usage information."
			echo -e ""
			exit 1
			;;
		esac
	shift
done

# set defaults

install_option="${1}"

[ -z "${install_option}" ] && install_option="minimal" || :

# dependencies #

# explicit console.download for preload

curl -sL get.cnsl.app/console > "${PREFIX}"/bin/console && source "${PREFIX}"/bin/console
curl -sL get.dxtp.app/globals > "${PREFIX}"/bin/globals && source "${PREFIX}"/bin/globals

# export variables

echo "export version=${version}"				>> "${PREFIX}"/bin/globals
echo "export install_option=${install_option}"	>> "${PREFIX}"/bin/globals

# download

console.fwd "Initializing..."
echo

console.download get.dxtp.app "${BINARIES_DIRECTORY}" termux-download

console.run "${BINARIES_DIRECTORY}"/termux-download

# welcome #

console.title "Linux on Android" "Termux // Dextop // Ubuntu" "${version}"

console.fwd "Initializing setup [ termux ]..."
echo

# setup #

# setup termux package requirements

console.run "${BINARIES_DIRECTORY}"/termux-packages

# setup environments

console.fwd "Setting up environments [ [ termux <<< ] | [ >>> proot ] ]..."
echo

# setup termux environment files

console.run "${BINARIES_DIRECTORY}"/termux-environment

# setup transient storage - [ device <<>> [ termux <<>> [ proot ] ] ]

console.run "${BINARIES_DIRECTORY}"/termux-storage

# setup termux login messages

console.run "${BINARIES_DIRECTORY}"/termux-welcome

# verify architecture compatibility

console.run "${BINARIES_DIRECTORY}"/proot-architecture

# setup proot user information

console.run "${BINARIES_DIRECTORY}"/proot-information

# setup proot image

console.run "${BINARIES_DIRECTORY}"/proot-image

# setup proot group IDs

console.run "${BINARIES_DIRECTORY}"/proot-groups

# setup proot libraries preload for enhanced performance

console.run "${BINARIES_DIRECTORY}"/proot-libraries

# setup proot network requirements  - [ device <<>> [ termux <<>> [ proot ] ] ]

console.run "${BINARIES_DIRECTORY}"/proot-network

# setup proot install routin

console.run "${BINARIES_DIRECTORY}"/proot-setup

# automatic setup transition [ termux >>> [ proot ] ]

cat <<- 'FILE' >> "${PROOT_DIRECTORY}"/root/.profile

bash /root/proot-setup
FILE

# run 'proot-launch' as 'root' - continue setup in proot environment

console.run "${BINARIES_DIRECTORY}"/proot-launch

exit
