#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# update packages list

console.update

# upgrade installed packages

console.upgrade

# packages #

libraries_list=(
	libandroid-glob
	libandroid-glob-static
	libandroid-shmem
	libandroid-shmem-static
	libandroid-spawn
	libandroid-spawn-static
	libandroid-support
	libandroid-support-static
)

repositories_list=(
	game-repo
	root-repo
	science-repo
	termux-apt-repo
	unstable-repo
	x11-repo
)

termux_list=(
	termux-am
	termux-api
	termux-auth
	termux-create-package
	termux-elf-cleaner
	termux-exec
	termux-keyring
	termux-licenses
	termux-services
	termux-tools
)

utilities_list=(
	curl
	dialog
	jq
	nano
	openssh
	proot
	rsync
	spell
	wget
)

install_list=(
	${libraries_list[@]}
	${utilities_list[@]}
)

# install #

console.install ${install_list[@]}
