#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# silence login prompt

console.inf "Silencing login messages."
echo

cat <<- 'FILE' >> "${HOME}"/.hushlogin

FILE

# write welcome message - replaces motd

cat <<- 'FILE' > "${HOME}"/.bashrc
# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

console.fwd "Welcome to Termux Dextop!"
echo

console.inf "Run 'proot-launch <username>' to start your session."
console.inf "Run 'proot-launch <username> <application>' to start an application with your session."
echo

console.wait 1

FILE