#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up packages [ ${script%-*} ]"
echo

# variables #

# set defaults

# update packages list

console.update

# upgrade installed packages

console.upgrade

# values #

documentation_list=(
	man
)

libraries_list=(
	libandroid-glob
	libandroid-glob-static
	libandroid-shmem
	libandroid-shmem-static
	libandroid-spawn
	libandroid-spawn-static
	libandroid-support
	libandroid-support-static
	libandroid-wordexp
	libandroid-wordexp-static
)

termux_list=(
	termux-am
	termux-api
	termux-apt-repo
	termux-auth
	termux-create-package
	termux-elf-cleaner
	termux-exec
	termux-keyring
	termux-licenses
	termux-services
	termux-tools
)

utilities_list=(
	aspell
	curl
	dialog
	ffmpeg
	git
	hub
	htop*
	jq
	nano
	ncurses-utils
	net-tools
	nmap
	openssh
	p7zip
	proot
	python
	rsync
	sshpass
	unrar
	wget
	zip
)
# initialize install list

install_list=()

# populate install list

install_list=(
	${documentation_list[@]}
	${libraries_list[@]}
	${termux_list[@]}
	${utilities_list[@]}
)

# install #

console.install ${install_list[@]}
