#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Creating bookmarks [ ${script%-*} ]"
echo

# variables #

# set defaults

# write bookmarks

cat << 'FILE' ->> "${HOME_DIRECTORY}"/.bookmarks
file:///media/internal Internal
FILE

if [ -d /media/external ]
then
	cat <<- 'FILE' ->> "${HOME_DIRECTORY}"/.bookmarks
	file:///media/external External
	FILE
fi

# link bookmarks

if [ "${SESSION}" = "kde" ] || [ "${SESSION}" = "xfce" ]
then
	console.directory "${HOME_DIRECTORY}" .config/gtk-3.0
	
	ln -s -f "${HOME_DIRECTORY}"/.bookmarks "${HOME_DIRECTORY}"/.gtk-bookmarks
	ln -s -f "${HOME_DIRECTORY}"/.bookmarks "${HOME_DIRECTORY}"/.config/gtk-3.0/bookmarks
fi