#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.inf "Cleaning up [ proot ]."
echo

# variables #

# set defaults

# initialize cleanup: find setup completion flag

if [[ "$(cat ${BINARIES_DIRECTORY}/termux-setup-complete)" = "yes" ]]
then
	console.fwd "Setup complete [ proot ]..."
	echo

	if [ ! -f "${HOME}"/setup ]
	then
		console.fwd "Setup complete [ termux ]..."
		echo
		console.scs "System deployment and configuration complete."
		echo
		console.inf "Run 'proot-launch -u <username>' to start your session."
		console.inf "Run 'proot-launch -u <username> -a <application>' to start an application with your session."
		echo
	
	else
		console.err "Some errors were encountered during setup."
		echo
		console.inf "Consult setup logs at '"${PREFIX}"/var/log/' for details."
		echo
	fi
fi

console.wait 5