#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		 -h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Updating packages [ ${script%-*} ]"
echo

# variables #



packages_url="https://f-droid.org/en/packages"
repository_url="https://f-droid.org/repo"

# packages #

packages_list=(
	com.termux
	com.termux.api
	)

# notice

console.err "Google Play Store updates deprecated since November 2020:"
echo

console.wrn "Back up and uninstall the Google Play Store version of Termux."
echo

console.inf "Visit the following wiki pages on how to proceed:"
echo

console.inf "Backing up Termux: https://wiki.termux.com/wiki/Backing_up_Termux"
console.inf "Installing Termux: https://wiki.termux.com/wiki/installation"
echo

console.usr "Select 'Package Installer' when prompted to proceed."
echo

# process update

for package in ${packages_list[@]}
do
	archive=$(curl -sL "${packages_url}"/"${package}" | grep -o "${package}"[aA0-zZ9-_]*.apk | head -n 1)
	
	archive_version=$(echo "${archive}" | cut -d '_' -f 2 | sed 's/\..*//g')
	
	archive_url="${repository_url}/${archive}"
	
	if [ "${package}" = "com.termux" ]
	then
		# com.termux apk
		
		installed_version=$(echo "${TERMUX_VERSION}" | cut -d '.' -f 2)
	else
		# com.termux.api apk
		
		installed_version=$(echo "${TERMUX_API_VERSION}" | cut -d '.' -f 2)
	fi
	
		# pplication version is deprecated
		
		if [ "${installed_version}" != "${archive_version}" ]
		then
			console.inf "Application version has been updated [ "${package}" // ${archive_version} ]."
			echo

			# request update permission
			
			console.ask "Update packages"
			
			read reply
			echo

			if [[ "${reply}" = [yY] ]] || [[ "${reply}" = [yY][eE][sS] ]]
			then
				console.inf "Dowloading updates."
				echo
	
				# download
			
				console.download "${repository_url}" "${PWD}" ${archive}
	
				# update
				
				xdg-open "${archive}"
				
				console.fwd "Updating..."
				echo
			else
				# continue without application update
				
				console.wrn "Proceeding without update."
				console.err "Setup process may encounter errors."
				echo
				
				console.inf "1 - Follow wiki pages stated above to correct issues."
				console.inf "2 - Restart setup on a fresh Termux installation to proceed."
				echo
			
				console.countdown "Continuing in" 3
				echo
			fi
				
			# termux application version is up to date
		else
			if [ "${installed_version}" == "${archive_version}" ]
			then
				console.inf "Application version is up to date [ "${package}" // ${archive_version} ]."
				echo
				
				console.fwd "Continuing..."
				echo
			fi
		fi
	fi
done