#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

# variables #

# message #

console.title "Linux on Android" "Termux // Dextop // Ubuntu" "${version}"

console.fwd "Initializing setup [ termux ]..."
echo
