#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	curl -s -L get.frbltr.app > "${PREFIX}"/bin/frobulator
fi

. "${PREFIX}"/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="03-01-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# override main source list file

echo "deb https://grimler.se/termux-packages-24 stable main" > "${PREFIX}"/etc/apt/sources.list

# create sources directory

frobulator.directory "${PREFIX}"/etc/apt/ sources.list.d

# write sources list files

repositories_list=(
	"deb https://grimler.se/termux-root-packages-24 root stable"
	"deb https://grimler.se/science-packages-24 science stable"
	"deb https://grimler.se/unstable-packages unstable main"
	"deb https://grimler.se/x11-packages x11 main"
)

# set IFS

IFS=$'\n'

# setup repositories

while read line
do
	for repository in ${repositories_list[@]}
	do
		# set file name

		source_name=$(echo ${repository} | cut -d ' ' -f 3)
		source_file="${source_name}.list"

		# write file

		echo "${repository}" > "${PREFIX}"/etc/apt/sources.list.d/"${source_file}"
	done

done <<< ${repositories_list[@]}

# reset IFS

 IFS=''

# update lists

frobulator.log "apt-get update" &

frobulator.progress "Forcing refresh..."
echo
