#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# variables #

# directories #

# files #

console.fwd "Setting up environment [ termux ]..."
echo

console.inf "Creating files."
echo

# silence login prompt

cat << 'FILE' ->> "${HOME}"/.hushlogin

FILE

# .bash_aliases

cat << 'FILE' ->> "${HOME}"/.bash_aliases

FILE

# .bash_logout

cat << 'FILE' ->> "${HOME}"/.bash_logout

FILE

# .bashrc

cat << 'FILE' ->> "${HOME}"/.bashrc

FILE

# .profile

cat << 'FILE' ->> "${HOME}"/.profile

FILE
