#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="10-24-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

storage_intent () {

	unset storage_command

	storage_command+="am broadcast"
	storage_command+=" -e com.termux.app.reload_style storage"
	storage_command+=" -a com.termux.app.reload_style com.termux"

	frobulator.silence "${storage_command}"
}

# verify termux storage directory existence

if [ ! -d "${HOME}"/storage ]
then
	# does not exist:
	# enable storage permissions: requires user touch input

	frobulator.wrn "User permission required to access storage on this device:"
	frobulator.wrn "Internal and external storage locations are made available."
	echo

	frobulator.inf "Storage is made accessible through container."
	echo

	frobulator.ins "Select 'Allow' when prompted to proceed."
	echo

	frobulator.separate

	# storage permissions dialog

	storage_intent

	frobulator.countdown 5 "Continuing" "[ ${script} ]"

else
	# exists:
	# proceed with setup

	frobulator.scs "Storage directory detected" "[ "${HOME}" ]"
	echo

	frobulator.fwd "Continuing..."
	echo
fi

frobulator.fwd "Setting up storage..."
echo

# handle storage mount locations

# /home

if [ -d "${HOME}"/storage ]
then
	rm					\
		--recursive		\
		--force			 "${HOME}"/storage
fi

# /media

if [ -d "${PREFIX}"/media ]
then
	rm					\
		--recursive		\
		--force			 "${PREFIX}"/media/*
fi

# /storage

if [ -d "${PREFIX}"/storage ]
then
	rm					\
		--recursive		\
		--force			 "${PREFIX}"/storage/*
fi

# generate symbolic links

# link internal storage

frobulator.fwd "Linking..."
echo

if [ ! -f "${PREFIX}"/media/internal ]
then
	ln -s -f /storage/emulated/0 "${PREFIX}"/media/internal
fi

if [ ! -f "${PREFIX}"/storage/internal ]
then
	ln -s -f /storage/emulated/0 "${PREFIX}"/storage/internal
fi

# link external storage

# use /proc/mounts to detect mounted media:
# circumvents /storage access issues and DAC policy (Android 11+)

external_storage=$(cat /proc/mounts | sed -r '/[A0-Z9][-][A0-Z9]/!d' | grep "/storage" | cut -d ' ' -f 2)

uuid="${external_storage/\/storage\//}"

if [ ! -z "${external_storage}" ]
then
	frobulator.scs "Storage media detected" "[ ${uuid} ]"
	echo

	if [ ! -f "${PREFIX}"/media/external ]
	then
		ln -s -f /storage/"${uuid}" "${PREFIX}"/media/external
	fi

	if [ ! -f "${PREFIX}"/storage/external ]
	then
		ln -s -f /storage/"${uuid}" "${PREFIX}"/storage/external
	fi
else
	uuid="N/A"

	frobulator.err "No storage media detected" "[ ${uuid} ]"
	echo

	frobulator.fwd "Continuing..."
	echo
fi
