#!/bin/bash

# author #

# Nathanel Titane - nathanel.titane@gmail.com

# Termux // Dextop // Ubuntu #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

version="02-07-2020"

# usage #

while (($#))
do
	case "${1}" in
		-f|--full)
			install_option="full"
		;;

		-m|--minimal)
			install_option="minimal"
		;;

		-h|--help|?)
			echo
			echo -e "USAGE:"
			echo
			echo -e "-f, --full \t Full setup: download and install full desktop environment and utilities."
			echo -e "-m, --minimal \t Minimal setup: download and install minimal desktop environment and utilities."
			echo
			echo -e "-a, --applications: Download a set of optimized and precompiled arm64 applications."
			echo
			echo -e "-h, --help, ? \t Show help and usage information."
			echo -e "-v, --version \t Show ${script} version."
			echo

			exit
		;;

		-v|--version)
			echo
			echo -e "${script} [ Version ${version} ]"
			echo
			exit
		;;

		*)
			echo
			echo "Usage: ${0} <option>"
			echo
			echo -e "${script}: Unknown option ${1}"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# set defaults

install_option="${1}"

[ -z "${install_option}" ] && install_option="minimal" || :

# dependencies #

# explicit console.download for preload

curl -sL get.cnsl.app/console > "${PREFIX}"/bin/console && source "${PREFIX}"/bin/console
curl -sL get.dxtp.app/globals > "${PREFIX}"/bin/globals && source "${PREFIX}"/bin/globals

# export variables

echo "export version=${version}"				>> "${PREFIX}"/bin/globals
echo "export install_option=${install_option}"	>> "${PREFIX}"/bin/globals

# download #

console.fwd "Initializing..."
echo

console.download get.dxtp.app "${BINARIES_DIRECTORY}" termux-download

# welcome #

console.title "Linux on Android" "Termux // Dextop // Ubuntu" "${version}"

console.fwd "Initializing setup [ termux ]..."
echo

# setup #

# setup termux and proot utilities

console.run "${BINARIES_DIRECTORY}"/termux-download

# setup termux package requirements

console.run "${BINARIES_DIRECTORY}"/termux-packages

# setup termux environment files

console.run "${BINARIES_DIRECTORY}"/termux-environment

# setup transient storage - [ device <<>> [ termux <<>> [ proot ] ] ]

console.run "${BINARIES_DIRECTORY}"/termux-storage

# setup termux login messages

console.run "${BINARIES_DIRECTORY}"/termux-welcome

# verify architecture compatibility

console.run "${BINARIES_DIRECTORY}"/proot-architecture

# setup proot user information

console.run "${BINARIES_DIRECTORY}"/proot-information

# setup proot fake /proc entries

console.run "${BINARIES_DIRECTORY}"/proot-fake

# setup proot image

console.run "${BINARIES_DIRECTORY}"/proot-image

# setup proot group IDs

console.run "${BINARIES_DIRECTORY}"/proot-groups

# setup proot libraries preload for enhanced performance

console.run "${BINARIES_DIRECTORY}"/proot-libraries

# setup proot network requirements  - [ device <<>> [ termux <<>> [ proot ] ] ]

console.run "${BINARIES_DIRECTORY}"/proot-network

# setup proot install routine

console.run "${BINARIES_DIRECTORY}"/proot-setup

# continue setup in proot environment - run 'proot-launch' as 'root'

console.run "${BINARIES_DIRECTORY}"/proot-launch

# setup cleanup #

"${BINARIES_DIRECTORY}"/termux-clean
