#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# termux #

console.directory "${HOME_DIRECTORY}" .termux

console.download get.trmnl.me/termux											"${HOME_DIRECTORY}"/.termux				termux.properties

# home #

console.directory "${HOME_DIRECTORY}" Desktop
console.directory "${HOME_DIRECTORY}" Documents
console.directory "${HOME_DIRECTORY}" Downloads
console.directory "${HOME_DIRECTORY}" Music
console.directory "${HOME_DIRECTORY}" Pictures
console.directory "${HOME_DIRECTORY}" Public
console.directory "${HOME_DIRECTORY}" Templates
console.directory "${HOME_DIRECTORY}" Videos

# bash #

console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.bash_aliases
console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.bash_functions
console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.bash_logout
console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.bashrc
console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.hushlogin
console.download get.trmnl.me/bash												"${HOME_DIRECTORY}"						.profile

# bash aliases #

console.directory "${HOME_DIRECTORY}" .bash-aliases

console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		apt
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		command
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		copy
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		count
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		directory
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		duplicate
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		git
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		grep
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		kill
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		list
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		nano
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		ping
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		sudo
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		shortcuts
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		system
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		usage
console.download get.trmnl.me/aliases											"${HOME_DIRECTORY}"/.bash-aliases		where

# bash functions #

console.directory "${HOME_DIRECTORY}" .bash-functions

console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		address
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		audio
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		extract
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		record
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		speed
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		sprunge
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		weather
console.download get.trmnl.me/functions											"${HOME_DIRECTORY}"/.bash-functions		youtube

# vnc #

console.directory "${HOME_DIRECTORY}" .vnc

console.download get.trmnl.me/vnc												"${HOME_DIRECTORY}"/.vnc				passwd
console.download get.trmnl.me/vnc												"${HOME_DIRECTORY}"/.vnc				xstartup

# i3wm #

console.directory "${HOME_DIRECTORY}"/.config i3
console.directory "${HOME_DIRECTORY}"/.config i3status
console.directory "${HOME_DIRECTORY}"/.config ranger

console.download get.trmnl.me/i3wm/i3											"${HOME_DIRECTORY}"/.config/i3			config
console.download get.trmnl.me/i3wm/i3status										"${HOME_DIRECTORY}"/.config/i3status	config

# ranger #

console.download get.trmnl.me/i3wm/ranger										"${HOME_DIRECTORY}"/.config/ranger		rc.conf

 # dmenu #

console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-change-background
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-confirm
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-exit-session
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-i3-shortcuts
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-open-directory
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-open-file
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-open-file-manager
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-open-manual
console.download get.trmnl.me/dmenu												"${BINARIES_DIRECTORY}"					dmenu-show-shortcuts

# leocad #

console.download get.trmnl.me/leocad											"${BINARIES_DIRECTORY}"					leocad-build
console.download get.trmnl.me/leocad											"${BINARIES_DIRECTORY}"					leocad-configuration
console.download get.trmnl.me/leocad											"${BINARIES_DIRECTORY}"					leocad-download
console.download get.trmnl.me/leocad											"${BINARIES_DIRECTORY}"					leocad-position

# youtube-dl #

console.download https://yt-dl.org/downloads/latest								"${BINARIES_DIRECTORY}"					youtube-dl