#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up properties [ ${script%-*} ]"
echo

# variables #

# set defaults

# remove default properties directory

[ -d "${HOME_DIRECTORY}"/.termux ] && rm -rf "${HOME_DIRECTORY}"/.termux

# create properties directory

console.directory "${HOME_DIRECTORY}" .termux

# write properties

cat << FILE ->> "${HOME_DIRECTORY}"/.termux/termux.properties

# use black for drawer and dialogs - Android 9.0+ default

use-black-ui = true

# enforce character based input - workaround for word-based input keyboards

enforce-char-based-input = true

# handle the bell character - vibrate | beep | ignore

bell-character=beep

# handle the escape key - escape | back

back-key=back

# rename current terminal session

shortcut.rename-session = ctrl + n

# open a new terminal with ctrl + t (volume down + t)

shortcut.create-session = ctrl + t

# move to previous terminal session

shortcut.previous-session = ctrl + 1

# move to next terminal session

shortcut.next-session = ctrl + 2

# configure keyboard shortcut keys

extra-keys = [																	\
	['ESC', '|',    '/',   'HOME', 'UP',   'END',   'PGUP', '_', 'BKSP'		],	\
	['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN', '-', 'RETURN'	]	\
																				]
FILE