#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# set defaults

# update packages list

console.update

# upgrade installed packages

console.upgrade

# values #

applications_list=(
	freecad
	leocad
	povray
	puddletag
)

development_list=(
	git
	hub
	python
)

multimedia_list=(
	ffmpeg
)

utilities_list=(
	fstl
	youtube-dl
)

# initialize install list

install_list=()

# populate install list

install_list+=(
	${applications_list[@]}
	${development_list_list[@]}
	${multimedia_list_list[@]}
	${utilities_list_list[@]}
)

# install #

console.install ${install_list[@]}