#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# defaults #

# export variables

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# configuration #

cat << 'FILE' ->> "${HOME_DIRECTORY}"/.profile

# user configuration #

if [ ! -f "${BINARIES_DIRECTORY}"/user-configuration-complete ]
then
	# configure system for user session:
	# keyboard / locales /timezones
	
	"${BINARIES_DIRECTORY}"/proot-configuration
	
	# confirm uninterrupted configuration
	
	echo "yes" > "${BINARIES_DIRECTORY}"/user-configuration-complete
fi
FILE