#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading utilities [ ${script%-*} ]"
echo

# variables #

# set defaults

# export variables

# source variables

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && source "${BINARIES_DIRECTORY}"/console

# download #

# bash aliases

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"						.bash_aliases

# bash functions

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		address
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		extract
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		record
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		speed
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		sprunge
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		weather
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		/home/"${USER}"/.bash_functions		youtube

# leocad

console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin							leocad-build
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin							leocad-configuration
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin							leocad-download
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin							leocad-launcher
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				/usr/bin							leocad-position

# youtube-dl

console.download https://yt-dl.org/downloads/latest											/usr/bin							youtube-dl