#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"

# variables #

[ "${dextop_option}" = "termux" ]												&& HOME_DIRECTORY="${HOME}"
[ "${dextop_option}" = "proot" ]												&& HOME_DIRECTORY="${ROOT_DIRECTORY}/home/${USER}"

# set defaults

# export variables

echo "# ${script} #"															>> "${PREFIX}"/bin/dextop

echo 'export HOME_DIRECTORY="${HOME_DIRECTORY}"'								>> "${PREFIX}"/bin/dextop

# clear #

console.clear

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# setup #

# in order of execution

if [ ! -f "${BINARIES_DIRECTORY}"/user-checkpoint-complete ]
then
	"${BINARIES_DIRECTORY}"/user-checkpoint
	
	"${BINARIES_DIRECTORY}"/user-startup

	"${BINARIES_DIRECTORY}"/proot-session
else

	"${BINARIES_DIRECTORY}"/user-configuration
	"${BINARIES_DIRECTORY}"/user-packages
	"${BINARIES_DIRECTORY}"/user-addons
	"${BINARIES_DIRECTORY}"/user-clean
fi

# confirm uninterrupted setup

echo "yes" > "${BINARIES_DIRECTORY}"/user-setup-complete