#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading additional utilities [ ${script%-*} ]"
echo

# bash aliases

console.directory "${ROOT_DIRECTORY}"/home/"${USER}" .bash_aliases

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		apt
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		copy
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		count
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		directory
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		duplicate
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		git
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		grep
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		kill
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		list
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		nano
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		ping
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		sudo
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		system
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		usage
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_aliases		where

# bash functions

console.directory "${ROOT_DIRECTORY}"/home/"${USER}" .bash_functions

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		address
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		extract
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		record
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		speed
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		sprunge
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		weather
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash_functions		youtube

# leocad

console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-build
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-configuration
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-download
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-launcher
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-position

# youtube-dl

console.download https://yt-dl.org/downloads/latest											"${ROOT_DIRECTORY}"/usr/bin								youtube-dl
