#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# set defaults

# export variables

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# startup #

cat << 'FILE' ->> "${ROOT_HOME_DIRECTORY}"/.profile

# user startup #

if [ ! -f "${BINARIES_DIRECTORY}"/user-startup-complete ]
then
	# dependencies #
	
	. /data/data/com.termux/files/usr/bin/console
	. /data/data/com.termux/files/usr/bin/dextop
	
	# continue proot setup
	
	"${BINARIES_DIRECTORY}"/user-setup

	# confirm uninterrupted setup
	
	echo "yes" > "${BINARIES_DIRECTORY}"/user-startup-complete
	
	# clear #
	
	console.clear
	
	# exit proot after successful setup
	
	console.fwd "Logging out..."
	echo
	
	exit
fi
FILE