#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Starting setup [ ${script%-*} ]"

# variables #

[ "${dextop_option}" = "termux" ]												&& HOME_DIRECTORY="${HOME}"
[ "${dextop_option}" = "proot" ]												&& HOME_DIRECTORY="${ROOT_DIRECTORY}/home/${USER}"

# set defaults

# export variables

echo '# user #'																	>> "${PREFIX}"/bin/dextop

echo 'export HOME_DIRECTORY="${HOME_DIRECTORY}"'								>> "${PREFIX}"/bin/dextop

# clear #

console.clear

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# setup #

# in order of execution

if [ ! -f "${BINARIES_DIRECTORY}"/user-checkpoint-complete ]
then
	setup_list+=(
		user-utilities
		user-addons
		user-checkpoint
	)
else
	setup_list+=(
		user-clean
	)
		
		# setup packages:
		# keep outside of array to run as root
		
		# setup user packages
		
		sudo /data/data/com.termux/files/usr/bin/user-packages
fi

# setup #

for setup in ${setup_list[@]}
do
	"${BINARIES_DIRECTORY}"/"${setup}"
	
	console.clear
done

# confirm uninterrupted setup

echo "yes" > "${BINARIES_DIRECTORY}"/user-setup-complete