#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Downloading additional utilities [ ${script%-*} ]"
echo

# bash aliases

console.directory "${ROOT_DIRECTORY}"/home/"${USER}" .bash-aliases

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		apt
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		command
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		copy
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		count
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		directory
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		duplicate
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		git
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		grep
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		kill
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		list
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		nano
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		ping
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		sudo
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		shortcuts
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		system
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		usage
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/aliases		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-aliases		where

# bash functions

console.directory "${ROOT_DIRECTORY}"/home/"${USER}" .bash-functions

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		address
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		extract
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		record
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		speed
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		sprunge
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		weather
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/functions		"${ROOT_DIRECTORY}"/home/"${USER}"/.bash-functions		youtube

# dmenu #

console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/dmenu			"${ROOT_DIRECTORY}"/usr/bin								dmenu-change-background
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/dmenu			"${ROOT_DIRECTORY}"/usr/bin								dmenu-exit-session
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/dmenu			"${ROOT_DIRECTORY}"/usr/bin								dmenu-open-stl
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/dmenu			"${ROOT_DIRECTORY}"/usr/bin								dmenu-show-cheats
console.download https://raw.githubusercontent.com/nathaneltitane/bash/master/dmenu			"${ROOT_DIRECTORY}"/usr/bin								dmenu-i3-shortcuts

# i3wm #

console.directory "${ROOT_DIRECTORY}"/home/"${USER}"/.config i3
console.directory "${ROOT_DIRECTORY}"/home/"${USER}"/.config i3status

console.download https://raw.githubusercontent.com/nathaneltitane/i3wm/main/i3				"${ROOT_DIRECTORY}"/home/"${USER}"/.config/i3			config
console.download https://raw.githubusercontent.com/nathaneltitane/i3wm/main/i3status		"${ROOT_DIRECTORY}"/home/"${USER}"/.config/i3status		config

# leocad

console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-build
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-configuration
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-download
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-launcher
console.download https://raw.githubusercontent.com/nathaneltitane/leocad/main				"${ROOT_DIRECTORY}"/usr/bin								leocad-position

# youtube-dl

console.download https://yt-dl.org/downloads/latest											"${ROOT_DIRECTORY}"/usr/bin								youtube-dl
