#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up ${script#*-}"
echo

# variables #

# set defaults

# export variables

echo "# ${script} #"															>> "${PREFIX}"/bin/dextop

# source variables

curl -sL get.cnsl.app/console > "${BINARIES_DIRECTORY}"/console && . "${BINARIES_DIRECTORY}"/console

# values #

binaries_list=(
	vnc-checkpoint
	vnc-clean
	vnc-environment
	vnc-pass
	vnc-setup
	vnc-session
	vnc-utilities
)

# download #

console.download get.dxtp.app "${BINARIES_DIRECTORY}" ${binaries_list[@]}
