#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Writing configuration [ ${script%-*} ]"
echo

# variables #

# set defaults

# write configuration

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc/xstartup

# vnc configuration #

# wait for session process start

while ! pgrep -f "${SESSION_MANAGER}" > /dev/null
do
	sleep 0.25
done

# confirm session process and execute

if [ ! -z $(pgrep -f "${SESSION_MANAGER}") ]
then
	xfconf-desktop
fi

# remove after execution  

sed -i '/# vnc configuration #/,$d' "${ROOT_DIRECTORY}"/home/"${USER}"/.vnc/xstartup
FILE