#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# check for PID and kill / cleanup

if [ ! -z "$(pgrep -f vnc)" ]
then
	# kill active and stale vnc output processes

	console.silence "vncserver -kill :*" &
	
	console.progress "Stopping display server..."
	echo

	# clean display server runtime files

	rm -rf /tmp/.X*
fi