#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="11-18-2021"

# usage #

while (($#))
do
	case "${1}" in
		-o|--start)
			option="start"
		;;

		-x|--stop)
			option="stop"
		;;
		
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-o, --start \t Start vnc session server."
			echo -e "-x, --stop \t Stop vnc session server."
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Session display [ ${script%-*} ]"
echo

# variables #

PORT="590${DISPLAY:1}"

# set defaults

# export variables

# /etc/os-release: source distribution codename variables (e.g. $NAME)

[ -f /etc/os-release ] && . /etc/os-release

# functions #

vnc_start () {
	console.fwd "Starting display server [ ${format} // ${GEOMETRY} // ${PORT} ]..."
	echo

	# 'vncserver' uses $DISPLAY instead of $PORT

	unset "${command}"

	command+="vncserver"
	command+=" -IdleTimeout 0"
	command+=" -SecurityTypes none"
	command+=" -localhost yes"
	command+=" -depth 32"
	command+=" -cleanstale"
	command+=" -name $NAME // Dextop"
	command+=" -geometry ${GEOMETRY} ${DISPLAY}"
	[ "${desktop_option}" = "i3wm" ] && command+=" -xstartup /usr/bin/i3"                 || :
	[ "${desktop_option}" = "ede" ]  && command+=" -xstartup /usr/bin/enlightenment"      || :
	[ "${desktop_option}" = "kde" ]  && command+=" -xstartup /home/${USER}/.vnc/xstartup" || :
	[ "${desktop_option}" = "xfce" ] && command+=" -xstartup /home/${USER}/.vnc/xstartup" || :

	console.silence "exec ${command}"

	# make selection available for automatic start:
	# verify user id - do not write selection when 'root' user is logged in

	if [[ $(id -u) -ne 0 ]]
	then
		# integer check: do not write non numerical values to file

		if [[ "${selection}" =~ ˆ[0-9]+$ ]]
		then
			echo "${selection}" > /home/"${USER}"/.vnc/selection
		fi
	fi

	# am start							\
	#	-a andoird.intent.action.VIEW	\
	#	-d vnc://${LOCALHOST}:${PORT}	\
	#	-S application/activity"
	
	# explicit VNC viewer application to kill:
	# used when vncserver is stopped or restarted using vnc:// intent
	# when launched via the activity manager [ 'am start -d {URI} -S {ACTIVITY}' ]
	
	# reference vnc session activity for known applications:
	
	# FreebVNC: com.iiordanov.freebVNC/com.iiordanov.bVNC.RemoteCanvasActivity
	# RealVNC:  com.realvnc.viewer.android/.app.DesktopActivity
	# Remotix:  com.nulana.android.remotix/.Viewer

	# start android vnc intent and force-stop existing activity

	# console.silence "am start -a android.intent.action.VIEW -d vnc://${LOCALHOST}:${PORT} -S ${VNC}"

	# start android vnc intent and set to view session with supported application

	console.silence "
				am start							\
					-a android.intent.action.VIEW	\
					-d vnc://${LOCALHOST}:${PORT}"
}

vnc_resolutions () {
	console.msg "Select geometry to start the display server"
	console.msg "or input [c]ustom properties:"
	echo

	# list supported display resolutions

	monitors=(
		VGA		 0640    0480
		WVGA	 0768    0480
		SVGA	 0800    0600
		FWVGA	 0854    0480
		qHD		 0960    0540
		DVGA	 0960    0640
		WSVGA	 1024    0576
		WSVGA	 1024    0600
		XGA		 1024    0768
		XGA+	 1152    0864
		HD		 1280    0720
		WXGA	 1366    0768
		WXGA+	 1440    0900
		HD+		 1600    0900

		SXGA	 1280    1024
		SXGA+	 1400    1050
		UXGA	 1600    1200
		WSXGA+	 1680    1050
		FHD		 1920    1080
		WUXGA	 1920    1200
		DCI2K	 2048    1080
		QWXGA	 2048    1152
		QXGA	 2048    1536
		UWFHD	 2560    1080
		QHD		 2560    1440
		WQXGA	 2560    1600
		QSXGA	 2560    2048
		QHD+	 3200    1800
		WQSXGA	 3200    2048
		QUXGA	 3200    2400
		UWQHD	 3440    1440
		UW4K	 3840    1600
		4KUHD	 3840    2160
		WQUXGA	 3840    2400
		DCI4K	 4096    2160
		UW5K	 5120    2160
		5K		 5120    2880
		8KUHD	 7680    4320
	)

	phones=(
		GN6P	 2560    1440
		GN6		 2560    1440
		GN5X	 1920    1080
		GN5		 1920    1080
		GP5		 2340    1080
		GP4XL	 3040    1440
		GP4a	 2340    1080
		GP4		 2280    1080
		GP3aXL	 2160    1080
		GP3a	 2220    1080
		GP3XL	 2960    1440
		GP3		 2160    1080
		GP2XL	 2880    1440
		GP2		 1920    1080
		GPXL	 2560    1440
		GP		 1920    1080

		SGN20+	 3088    1440
		SGN20	 3200    1440
		SGN10+	 3040    1440
		SGN10	 2280    1080
		SGN9	 2960    1440
		SGN8	 2960    1440
		SGN7	 2560    1440

		SGS10+	 3040    1440
		SGS10	 3040    1440
		SGS9+	 2960    1440
		SGS9	 2960    1440
		SGS8+	 2960    1440
		SGS8	 2960    1440
		SGS7E	 2560    1440
		SGS7	 2560    1440
		SGS6E+	 2560    1440
		SGS6E	 2560    1440
		SGS6	 2560    1440
	)

	tablets=(
		GN9	     2048    1536
		GN7-2013 1920    1200
		GPC	     2560    1800

		SGTS7+	 2800    1752
		SGTS7	 2560    1600
		SGTS6	 2560    1600
		SGTS5E	 2560    1600
		)

	devices=(
		${phones[@]}
		${tablets[@]}
	)

	resolutions=(
		${monitors[@]}
		${devices[@]}
	)

	printf '\n'

	# set padding for uniform output

	pad_length=10

	# continue list using array selection of suppported values

	for (( i=0 ; i<${#resolutions[@]} ; i+=3 ))
	do
		format="${resolutions[$i]}"
		width="${resolutions[$i+1]}"
		height="${resolutions[$i+2]}"
		resolution="${width}x${height}"

		number=$((($i/3) + 1))

		if (( $i/3 >= 0 && $i/3 <= 8 ))
		then
			# handle number spacing for entries 1-9

			printf '\t[  %s ] %s' ${number} ${format}
		else
			# handle number spacing for entries 10+

			printf '\t[ %s ] %s' ${number} ${format}
		fi

		printf '%*s' $((pad_length - ${#format}))
		printf '%s\n' ${resolution}
	done

	printf '\n'
}

vnc_stop () {
	console.silence "
		vncserver		\
			-kill		\
			-clean		:*" &

	console.progress "Killing display server..."
	echo

	# clean display server runtime files

	rm -rf "${TMPDIR}"/.X*
}

vnc_list () {
	# get values from 'vncserver -list'
	
	read vnc_display vnc_port vnc_process vnc_server <<< $(echo $(vncserver -list | tail -n 1))

	if [[ "${vnc_process}" = ˆ[0-9]+$ ]]
	then
		# set values for list output

		empty="N/A"

		vnc_display="${empty}"
		vnc_port="${empty}"
		vnc_process="${empty}"
		vnc_server="${empty}"

		console.wrn "No active servers detected."
		echo
	fi
	
	console.fwd "Listing servers..."
	echo

	console.inf "Display" "${vnc_display}" "-"
	console.inf "Port"    "${vnc_port}"    "-"
	console.inf "Process" "${vnc_process}" "-"
	console.inf "Server"  "${vnc_server}"  "-"
	echo
}

if [ "${option}" = "start" ]
then
	# handle selections display
	
	if [ -f /home/"${USER}"/.vnc/selection ]
	then
		# hide if selection file is present
	
		vnc_resolutions > /dev/null
	else
		# show if selection file is not present
		
		vnc_resolutions
	fi
	
	# values #
	
	values_list=(
		selection
	)
	
	# handle user input for values_list
	
	console_rtn=()
	
	if [ -f /home/"${USER}"/.vnc/selection ]
	then
		selection=$(cat /home/"$USER"/.vnc/selection)
	else
		console.input ${values_list[@]}
	fi
	
	eval ${console_rtn[@]}
	
	# check selection input against selection list
	
	while true
	do
		# range #
	
		if [[ "${selection}" -lt 1 ]] || [[ "${selection}" -gt "${number}" ]]
		then
			echo
			console.err "Invalid selection:"
			console.wrn "Select geometry ranging from [ 1 - ${number} ]"
			console.wrn "or input [c]ustom properties."
			echo
	
			console.ipt "Selection:"
			
			read selection
			echo
		else
			break
		fi
	
		# custom #
	
		if [[ "${selection}" != "c" ]]
		then
			echo
			console.err "Invalid selection:"
			console.wrn "Input [c]ustom properties"
			console.wrn "or select geometry ranging from [ 1 - ${number} ]."
			echo
	
			console.ipt "Selection:"
			
			read selection
			echo
		else
			selection=custom
	
			break
		fi
	
	done
	
	# handle numerical selection
	
	unset resolution
	
	if [[ "${selection}" =~ ^[0-9]+$ ]]
	then
		i=$((${selection}))
		i=$(($i*3))
	
		format="${resolutions[$i-3]}"
		width="${resolutions[$i-2]}"
		height="${resolutions[$i-1]}"
		resolution="${width}x${height}"
	
		GEOMETRY="${resolution}"
	fi
	
	# handle custom selection
	
	if [[ "${selection}" = "custom" ]]
	then
		console.inf "Setting custom properties."
		echo
	
		console.ipt "Geometry WIDTH in pixels:"
		
		read width
		echo
	
		console.ipt "Geometry HEIGHT in pixels:"
		
		read height
		echo
	
		console.ipt "Port NUMBER (e.g. 1):"
		
		read custom_port
		echo
	
		format="Custom"
		custom_resolution="${width}x${height}"
	
		DISPLAY=":${custom_port}"
		GEOMETRY="${custom_resolution}"
		PORT="590${DISPLAY:1}"
	fi
	
	# start vnc session
	
	vnc_start
fi

if [ "${option}" = "stop" ]
then
	# stop vnc session

	vnc_stop
fi

# list vnc session

vnc_list