#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up environment"
echo

# variables #

# set defaults

# create vnc directory

console.directory "${HOME_DIRECTORY}" .vnc

# write user vnc password file

cat << FILE -> "${HOME_DIRECTORY}"/.vnc/passwd

FILE

# write user vnc startup file

cat << 'FILE' -> "${HOME_DIRECTORY}"/.vnc/xstartup
#!/bin/bash

# uncomment if using 'dbus-launch'

# unset DBUS_SESSION_BUS_ADDRESS
# unset SESSION_MANAGER

if [ ! -z "${APPLICATION}" ]
then
	"${SETTINGS_MANAGER}" &
	"${WINDOW_MANAGER}" &
	"${APPLICATION}" &
else
	"${SESSION_LOADER}" &
	"${WINDOW_MANAGER}" &
fi

if [ -z $(pgrep -x "${RUNNER}") ]
then
	"${RUNNER}" -d &
fi

if [ "${SESSION}" = "KDE" ] || [ "${SESSION}" = "xfce" ]
then
	if [ ! -z $(pgrep -f "${SESSION}") ]
	then
		proot-compositing
	fi
fi
FILE

# append automatic vnc session stop on shell logout

cat << 'FILE' ->> "${HOME_DIRECTORY}"/.bash_logout

# automatic vnc session stop on shell logout

vnc-session -x
FILE

# append automatic vnc session start from selection value

cat << 'FILE' ->> "${HOME_DIRECTORY}"/.profile

# automatic vnc session start on shell login

if [ -f "${HOME}"/.vnc/selection ]
then
	echo $(cat "${HOME}"/.vnc/selection) | vnc-session -o
else
	vnc-session -o
fi
FILE
