#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="02-07-2020"

# usage #

while (($#))
do
        case "${1}" in
                -h|--help)
                        echo
                        echo -e "Usage: ${script} [OPTION]"
                        echo
                        echo -e "Options:"
                        echo
                        echo -e "-h, --help \t Show help and usage information."
                        echo
                        echo -e "'${script}' [ Version ${version} ]"
                        echo

                        exit
                ;;

                *)
                        echo
                        echo "Usage: ${script} [OPTION]"
                        echo
                        echo -e "${script}: Unknown option '${1}'"
                        echo -e "Type './${script} --help' for help and usage information."
                        echo

                        exit 1
                ;;
        esac

        shift
done

# variables #

# setup

console.inf "Configuring display output [ vnc ]."
echo

# create user home vnc directory

mkdir -p "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc

# write user vnc password file

cat << FILE -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc/passwd

FILE

# write user vnc startup file

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc/xstartup
#!/bin/bash

unset DBUS_SESSION_BUS_ADDRESS
unset SESSION_MANAGER

if [ "${SESSION}" = "dwm" ]
then
	if [ ! -z $(which dwm-status) ]
	then
		dwm-status &
	fi
fi

if [ ! -z "${APPLICATION}" ]
then
	"${SESSION}" &

	LD_PRELOAD=/lib/libandroid-shmem-aarch64.so $APPLICATION &
else
	dbus-launch --exit-with-session "${SESSION}" &
fi
FILE

# append automatic vnc session stop on shell exit

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_logout

# automatic vnc session stop on shell logout

vnc-stop && clear
FILE

# append automatic vnc session start from selection value

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

# automatic vnc session start on shell login

if [ -f "${HOME}"/.vnc/selection ]
then
	echo $(cat "${HOME}"/.vnc/selection) | vnc-start
else
	vnc-start
fi

FILE
