#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="09-14-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Setting up environment [ ${script%-*} ]"
echo

# variables #

# set defaults

# create vnc directory

console.directory "${ROOT_DIRECTORY}"/home/"${user_name}" .vnc

# write user vnc password file

cat << FILE -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc/passwd

FILE

# write user vnc startup file

cat << 'FILE' -> "${ROOT_DIRECTORY}"/home/"${user_name}"/.vnc/xstartup
#!/bin/bash

if [ ! -z "${APPLICATION}" ]
then
	"${SETTINGS_MANAGER}" &
	"${WINDOW_MANAGER}" &
	"${APPLICATION}" &
else
	"${SESSION_MANAGER}" &
	"${WINDOW_MANAGER}" &
fi

if [ ! -z $(pgrep -f "${SESSION}) ]
then
	proot-compositing
fi
FILE

# append automatic vnc session stop on shell logout

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.bash_logout

# automatic vnc session stop on shell logout

vnc-stop
FILE

# append automatic vnc session start from selection value

cat << 'FILE' ->> "${ROOT_DIRECTORY}"/home/"${user_name}"/.profile

# automatic vnc session start on shell login

if [ -f "${HOME}"/.vnc/selection ]
then
	echo $(cat "${HOME}"/.vnc/selection) | vnc-start
else
	vnc-start
fi
FILE
