#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Cleaning up"
echo

# variables #

# set defaults

# initialize cleanup: find setup completion flag

if [ -f "${BINARIES_DIRECTORY}"/vnc-checkpoint-complete ]
then
	# message #

	console.scs "Setup complete"
	echo
	
	console.fwd "Removing setup files..."
	echo

	# remove setup files

	remove_list=(
	)

	console.delete ${remove_list[@]}

else
	console.err "Setup errors were encountered"
	echo
	
	console.inf "Consult setup logs at '"${PREFIX}"/var/log/' for details."
	echo
fi
