#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
		esac

	shift
done

# prompt #

console.script "Stopping display [ ${script%-*} ]"
echo

# variables #

# set defaults

# functions #

vnc_stop () {
	console.silence "
				vncserver		\
					-kill		\
					-clean		:*" &

	console.progress "Killing display server..."
	echo
	
	# clean display server runtime files

	rm -rf "${TMPDIR}"/.X*
}

# verify PID and stop display server

if [ ! -z "$(pgrep -f vnc)" ]
then
	vnc_stop
fi