#!/bin/bash

# dependencies #

. /data/data/com.termux/files/usr/bin/console
. /data/data/com.termux/files/usr/bin/dextop

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="12-03-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
		
	esac

	shift
done

# prompt #

console.script "Starting setup"

# variables #

# set defaults

# export variables

echo '# vnc #'														>> "${PREFIX}"/bin/dextop

# clear #

console.clear

# source variables

[ -f "${PREFIX}"/bin/dextop ] && . "${PREFIX}"/bin/dextop

# setup #

# in order of execution

if [ ! -f "${BINARIES_DIRECTORY}"/vnc-checkpoint-complete ]
then
	bash "${BINARIES_DIRECTORY}"/vnc-utilities
	bash "${BINARIES_DIRECTORY}"/vnc-environment
	bash "${BINARIES_DIRECTORY}"/vnc-checkpoint
	bash "${BINARIES_DIRECTORY}"/vnc-clean
fi

# confirm uninterrupted setup

echo "yes" > "${BINARIES_DIRECTORY}"/vnc-setup-complete