#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="08-12-2021"

# usage #

while (($#))
do
	case "${1}" in
		-h|--help)
			echo
			echo -e "Usage: ${script} [OPTION]"
			echo
			echo -e "Options:"
			echo
			echo -e "-h, --help \t Show help and usage information."
			echo
			echo -e "'${script}' [ Version ${version} ]"
			echo

			exit
		;;

		*)
			echo
			echo "Usage: ${script} [OPTION]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1
		;;
	esac

	shift
done

# prompt #

console.script "Starting setup [ ${script%-*} ]"

# variables #

# set defaults

# export variables

echo '# vnc variables #'														>> "${PREFIX}"/bin/globals

# source variables

[ -f "${PREFIX}"/bin/globals ] && source "${PREFIX}"/bin/globals

# setup #

# setup vncutilities

console.run "${BINARIES_DIRECTORY}"/vnc-utilities

# welcome message

console.run "${BINARIES_DIRECTORY}"/vnc-message

# setup vnc environment files

console.run "${BINARIES_DIRECTORY}"/vnc-environment