#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# directories #

console.directory "LeoCAD Software" "$PROOT_DIRECTORY"/home/"${user_name}"/.config

# write configuration files

console.info "Writing configuration files [ applications ]."
echo

bash "$PROOT_DIRECTORY"/usr/bin/leocad-configuration
bash "$PROOT_DIRECTORY"/usr/bin/youtube-dl-configuration
