#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# directories #

# blackbox

console.info "Creating directories [ leocad ]."
echo

system_directories_list=(
	.config/"LeoCAD Software"
)

for directory in ${system_directories_list[@]}
do
	console.fwd "Creating directory [ ${directory} ]."
	echo

	# create directory and set permissions

	[ ! -d "$PROOT_DIRECTORY"/home/"$user_name"/"${directory}" ] && mkdir -p "$PROOT_DIRECTORY"/usr/share/"${directory}" || :
	
	# set ownership
	
	chown ${uid}:${gid} -R "$PROOT_DIRECTORY"/home/"$user_name"/"${directory}"
done

# write configuration files

console.info "Writing configuration files [ leocad ]."
echo

bash "$PROOT_DIRECTORY"/tmp/leocad-configuration
