#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# create directory

console.directory "LeoCAD Software" "$PROOT_DIRECTORY"/home/"${user_name}"/.config

# link configuration

[ -d /media/Internal/MEGA/Lego/leocad/ ] && \
	ln -s -f \
		/media/Internal/MEGA/Lego/leocad/leocad.conf \
		"$PROOT_DIRECTORY"/home/"$user_name"/.config/"LeoCAD Software"/LeoCAD.conf || :
			
# .bashrc

cat <<- 'FILE' >> "$PROOT_DIRECTORY"/home/"$user_name"/.bash_profile

# leocad #

console.get app.dxtp.app leocad /usr/bin
FILE