#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# leocad #

console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad					/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad-configuration	/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad-get				/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad-launcher		/usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad-position		/usr/bin

# .profile

# cat <<- 'FILE' >> "${PROOT_DIRECTORY}"/home/"${user_name}"/.profile

# FILE