#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# .bashrc

cat <<- 'FILE' >> "$PROOT_DIRECTORY"/home/"$user_name"/.bash_profile

# youtube-dl #

console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main/ leocad /usr/bin
console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main/ leocad-position /usr/bin
FILE