#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# link configuration

[ -d /media/Internal/MEGA/Lego/leocad/ ] && \
	ln -s -f \
		/media/Internal/MEGA/Lego/leocad/leocad.conf \
		"$PROOT_DIRECTORY"/home/"$user_name"/.config/"LeoCAD Software"/LeoCAD.conf || :