#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# .bashrc

cat <<- 'FILE' >> "$HOME"/.bashrc

console.get https://yt-dl.org/downloads/latest/ youtube-dl /usr/bin
FILE