#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# youtube-dl #

console.get https://yt-dl.org/downloads/latest youtube-dl /usr/bin

# .profile

# cat <<- 'FILE' >> "${PROOT_DIRECTORY}"/home/"${user_name}"/.profile

# FILE