#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# applications # 

applications_list=(
	applications-setup
	leocad
	leocad-arm64
	leocad-position
	leocad-configuration
)

# download #

for application in ${applications_list[@]}
do
	console.get app.dxtp.app "${application}" "$PROOT_DIRECTORY"/usr/bin

	console.download "Downloading application [ ${application} ]."
	echo

	chmod +x "$PROOT_DIRECTORY"/usr/bin/"${application}"
done