#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# applications # 

applications_list=(
	leocad
)

# download #

for application in ${applications_list[@]}
do
	console.get app-dex.ntttn.me "${application}" "$BINARES_DIRECTORY"

	console.download "Downloading application [ ${application} ]."
	echo

	chmod +x "$BINARIES_DIRECTORY/${application}"
done