#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# binaries # 

binaries_list=(
	proot-architecture
	proot-environment
	proot-image
	proot-information
	proot-launch
	proot-packages
	proot-preferences
	proot-setup
	proot-superuser
	proot-user
	termux-environment
	termux-groups
	termux-packages
	termux-storage
	vnc-pass
	vnc-setup
	vnc-start
	vnc-stop
	xfconf-read
	xfconf-write
	xorg-setup
)

# download #

for binary in ${binaries_list[@]}
do
	binary_url=bin-dex.ntttn.me/"${binary}"

	curl -sL ${binary_url} > "$BINARIES_DIRECTORY/${binary}"

	console.download "Downloading binary [ ${binary} ]."
	echo

	chmod +x "$BINARIES_DIRECTORY/${binary}"
done