#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# binaries # 

downloads_list=(
	proot-aliases
	proot-architecture
	proot-environment
	proot-image
	proot-information
	proot-launch
	proot-libraries
	proot-network
	proot-packages
	proot-setup
	proot-superuser
	proot-system
	proot-user
	proot-welcome
	termux-environment
	termux-groups
	termux-packages
	termux-storage
	termux-welcome
	vnc-pass
	vnc-setup
	vnc-start
	vnc-stop
	xfconf-read
	xfconf-write
	xorg-setup
)

# download #

console.download bin.dxtp.app "$BINARIES_DIRECTORY" ${downloads_list[@]}