#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# configurations #

downloads_list=(
	blackbox-configuration
	blackbox-menu
	blackbox-setup
	blackbox-theme
)

# download #

console.download cfg.dxtp.app "$PROOT_DIRECTORY"/tmp ${downloads_list[@]}