#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# configurations #

configurations_list=(
	blackbox-configuration
	blackbox-menu
	blackbox-setup
	blackbox-theme
	i3-configuration
	i3status-configuration
	xfce4-configuration
)

# download #

for configuration in ${configurations_list[@]}
do
	console.get cfg.dxtp.app "${configuration}" "$PROOT_DIRECTORY"/tmp

	console.download "Downloading configuration [ ${configuration} ]."
	echo

done