#!/bin/bash

# colors #

if [ -z $(command -v tput) ]
then
	if [[ -t 1 ]]
	then
		black=$(echo -e \\e\[30m)
		red=$(echo -e \\e\[31m)
		green=$(echo -e \\e\[32m)
		yellow=$(echo -e \\e\[33m)
		blue=$(echo -e \\e\[34m)
		magenta=$(echo -e \\e\[35m)
		cyan=$(echo -e \\e\[36m)
		white=$(echo -e \\e\[97m)
		reset=$(echo -e \\e\[39m)
	fi
else
	if [[ -t 1 ]]
	then
		black=$(tput setaf 0)
		red=$(tput setaf 1)
		green=$(tput setaf 2)
		yellow=$(tput setaf 3)
		blue=$(tput setaf 4)
		magenta=$(tput setaf 5)
		cyan=$(tput setaf 6)
		white=$(tput setaf 7)
		reset=$(tput sgr0)
	fi
fi

# symbols #

#	⋀⋁
#	△▷▽◁

# markers

marker_batsu='[ ✕ ]'
marker_download='[ ⋁ ]'
marker_fwd='[ > ]'
marker_info='[ i ]'
marker_input='[ + ]'
marker_maru='[ ○ ]'
marker_bako='[ □ ]'
marker_no='[ ✕ ]'
marker_question='[ ? ]'
marker_rev='[ < ]'
marker_sankaku='[ △ ]'
marker_stp='[ - ]'
marker_upload='[ ⋀ ]'
marker_warning='[ ! ]'
marker_yes='[ ✓ ]'
marker_yes_no='[ Y/N ]'

# highlights #

# red

console.red () {
	echo "${red}"$@"${reset}"
}

# green

console.green () {
	echo "${green}"$@"${reset}"
}

# yellow

console.yellow () {
	echo "${yellow}"$@"${reset}"
}

# blue

console.blue () {
	echo "${blue}"$@"${reset}"
}

# magenta

console.magenta () {
	echo "${magenta}"$@"${reset}"
}

# cyan

console.cyan () {
	echo "${cyan}"$@"${reset}"
}

# prompts #

# marker_batsu

console.batsu () {
	echo "${red}${marker_batsu}" $@"${reset}"
}

# marker_download

console.download () {
	echo "${magenta}${marker_download}" $@"${reset}"
}

# marker_fwd

console.fwd () {
	echo "${white}${marker_fwd}" $@"${reset}"
}

# marker_info

console.info () {
	echo "${cyan}${marker_info}" $@"${reset}"
}

# marker_input

console.input () {
	echo -n "${magenta}${marker_input}" $@"${reset}"
}

# marker_maru

console.maru () {
	echo "${green}${marker_maru}" $@"${reset}"
}

# marker_no

console.error () {
	echo "${red}${marker_no}" $@"${reset}"
}

# marker_question

console.question () {
	echo "${magenta}${marker_question}" $@"${reset}"
}

# marker_rev

console.rev () {
	echo "${white}${marker_rev}" $@"${reset}"
}

# marker_sankaku

console.sankaku () {
	echo "${blue}${marker_sankaku}" $@"${reset}"
}

# marker_stp

console.stp () {
	echo "${white}${marker_stp}" $@"${reset}"
}

# marker_upload

console.upload () {
	echo "${magenta}${marker_upload}" $@"${reset}"
}

# marker_warning

console.warning () {
	echo "${yellow}${marker_warning}" $@"${reset}"
}

# marker_yes

console.success () {
	echo "${green}${marker_yes}" $@"${reset}"
}

# marker_yes_no

console.choice () {
	echo "${magenta}${marker_yes_no}" $@"${reset}"
}

# triggers #

# countdown

console.countdown () {
	seconds=$1
	
	shift

	while [ ${seconds} -gt 0 ]
	do
		echo -e "\r${marker_warning} Waiting [ ${yellow}$((seconds--))${reset} ] seconds...\c"
		
		sleep 1
	done
}

# spinner

console.spinner () {
	# catch PID of last command

	PID=$!

	# spinner string content

	spinner_1="+×"
	spinner_2="/—\|"
	spinner_4="◸◹◿◺"
	spinner_5="◰◳◲◱"
	spinner_6="◜◝◞◟"
	spinner_7="◴◷◶◵"
	spinner_8="◑◒◐◓"
	
	# parse spinner
	
	spinner="${spinner_4}"
	before="[ "
	after="]"
	message="$1"

	i=1

	while [ -d /proc/$PID ]
	do
		echo -ne "\r${before} \b${spinner:i++%${#spinner}:1} ${after} ${message}\c "
		
		sleep 0.125
	done
}