#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# images #

images_list=(
	bird.png
	bird.svg
)

# download #

for image in ${images_list[@]}
do
	console.get img-dex.ntttn.me "${image}" "$PROOT_DIRECTORY"/usr/share/backgrounds

	console.download "Downloading image [ ${image} ]."
	echo

done
