#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# images #

downloadss_list=(
	bird.png
	bird.svg
)

# download #

console.download \
		img.dxtp.app \
		"$PROOT_DIRECTORY"/usr/share/backgrounds \
		"chmod +x" 