#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# libraries #

libraries_list=(
	libandroid-shmem-aarch64.so
)

# download #

for library in ${libraries_list[@]}
do
	console.get lib-dex.ntttn.me "${library}" "$PROOT_DIRECTORY"/lib

	console.download "Downloading library [ ${library} ]."
	echo

done
