#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# libraries #

downloads_list=(
	libandroid-shmem-aarch64.so
)

# download #

console.download lib.dxtp.app "$PROOT_DIRECTORY"/lib