#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# libraries #

libraries_list=(
	libandroid-shmem-aarch64.so
)

# download #

for library in ${libraries_list[@]}
do
	library_url=lib-dex.ntttn.me/"$library"

	curl -sL ${library_url} > "$PROOT_DIRECTORY"/lib/"$library"

	console.download "Downloading library [ $library ]."
	echo

done
